(()=>{
const OWNER='Kale1205',REPO='fde-site',BRANCH='main';
const API=`https://api.github.com/repos/${OWNER}/${REPO}`;
const RAW=`https://raw.githubusercontent.com/${OWNER}/${REPO}/${BRANCH}`;
const $=s=>document.querySelector(s);
let token='',cms=null,cmsSha='';
const status=(msg,type='')=>{const el=$('#adminStatus');el.textContent=msg;el.className=`status ${type}`.trim();el.hidden=false};
const headers=()=>({'Accept':'application/vnd.github+json','Authorization':`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28'});
const bytesToBase64=bytes=>{let bin='';const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)bin+=String.fromCharCode(...bytes.subarray(i,i+chunk));return btoa(bin)};
const utf8ToBase64=text=>bytesToBase64(new TextEncoder().encode(text));
const decodeBase64Utf8=b64=>new TextDecoder().decode(Uint8Array.from(atob(b64.replace(/\n/g,'')),c=>c.charCodeAt(0)));
const fileBase64=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file)});
const safeExt=file=>{const name=file.name.toLowerCase();if(name.endsWith('.png'))return'png';if(name.endsWith('.webp'))return'webp';if(name.endsWith('.gif'))return'gif';return'jpg'};
const safeName=file=>{const base=file.name.replace(/\.[^.]+$/,'').normalize('NFKD').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,42)||'image';const now=new Date();const stamp=`${now.getFullYear()}${String(now.getMonth()+1).padStart(2,'0')}${String(now.getDate()).padStart(2,'0')}-${String(now.getHours()).padStart(2,'0')}${String(now.getMinutes()).padStart(2,'0')}${String(now.getSeconds()).padStart(2,'0')}`;const rand=crypto.getRandomValues(new Uint32Array(1))[0].toString(16).slice(0,6);return`${stamp}-${base}-${rand}.${safeExt(file)}`};
const today=()=>new Date().toLocaleDateString('sv-SE');
const slug=s=>String(s||'news').normalize('NFKD').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,45)||'news';
async function api(path,options={}){const res=await fetch(`${API}${path}`,{...options,headers:{...headers(),...(options.headers||{})}});if(!res.ok){let detail='';try{const j=await res.json();detail=j.message||''}catch{}throw new Error(`${res.status} ${detail}`.trim())}return res.status===204?null:res.json()}
async function loadCms(){const r=await api(`/contents/content/site-content.json?ref=${encodeURIComponent(BRANCH)}`);cmsSha=r.sha;cms=JSON.parse(decodeBase64Utf8(r.content));renderNewsOptions()}
function renderNewsOptions(){const sel=$('#newsTarget');sel.innerHTML='';(cms?.news||[]).slice().sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))).forEach(n=>{const o=document.createElement('option');o.value=n.id;o.textContent=`${n.date||''} — ${(n.title&&n.title.ja)||n.id}`;sel.appendChild(o)});sel.disabled=!sel.options.length;toggleTarget()}
function toggleTarget(){const target=document.querySelector('input[name=target]:checked')?.value||'news';$('#newsField').classList.toggle('hidden',target!=='news');const help={news:'選択したNews記事のメイン画像として設定します。',fallback:'画像が設定されていないNewsに共通で表示するデフォルト画像として設定します。',instagram:'Newsページ下部のInstagram紹介画像として設定します。'};$('#targetHelp').textContent=help[target]||help.news}
async function connect(){token=$('#token').value.trim();if(!token){status('GitHub tokenを入力してください。','error');return}const btn=$('#connectBtn');btn.disabled=true;try{const me=await fetch('https://api.github.com/user',{headers:headers()});if(!me.ok)throw new Error('GitHub認証に失敗しました');const user=await me.json();await loadCms();$('#uploaderCard').classList.remove('hidden');$('#newsCreateCard').classList.remove('hidden');status(`${user.login} として接続しました。News投稿と画像管理を利用できます。`,'success')}catch(e){token='';status(`接続できませんでした: ${e.message}`,'error')}finally{btn.disabled=false}}
function validateImage(file){if(!file)return true;if(!file.type.startsWith('image/'))throw new Error('画像ファイルを選択してください。');if(file.size>8*1024*1024)throw new Error('画像は8MB以下にしてください。');return true}
function previewFile(inputSelector,boxSelector){const file=$(inputSelector).files[0];const box=$(boxSelector);if(!file){box.innerHTML='<div class="preview-placeholder">画像を選択すると、ここにプレビューが表示されます。</div>';return}try{validateImage(file)}catch(e){status(e.message,'error');$(inputSelector).value='';return}const u=URL.createObjectURL(file);box.innerHTML=`<img src="${u}" alt="preview">`}
async function uploadAsset(file){validateImage(file);const filename=safeName(file);const now=new Date();const path=`assets/cms/${now.getFullYear()}/${String(now.getMonth()+1).padStart(2,'0')}/${filename}`;const content=await fileBase64(file);await api(`/contents/${path}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`CMS: upload ${filename}`,content,branch:BRANCH})});return `${RAW}/${path}`}
async function saveCms(message){const body={message,content:utf8ToBase64(JSON.stringify(cms,null,2)+'\n'),sha:cmsSha,branch:BRANCH};await api('/contents/content/site-content.json',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await loadCms()}
async function uploadAndApply(){if(!token){status('先にGitHubへ接続してください。','error');return}const file=$('#imageFile').files[0];if(!file){status('画像を選択してください。','error');return}const target=document.querySelector('input[name=target]:checked')?.value||'news';if(target==='news'&&!$('#newsTarget').value){status('画像を設定するNewsを選択してください。','error');return}const btn=$('#uploadBtn');btn.disabled=true;try{status('画像をアップロードしています…');const imageUrl=await uploadAsset(file);await loadCms();if(target==='news'){const id=$('#newsTarget').value;const item=(cms.news||[]).find(n=>n.id===id);if(!item)throw new Error('選択したNewsが見つかりません');item.image=imageUrl;await saveCms(`CMS: set image for ${id}`)}else if(target==='fallback'){cms.newsFallbackImage=imageUrl;await saveCms('CMS: update News fallback image')}else{cms.instagram=cms.instagram||{};cms.instagram.image=imageUrl;await saveCms('CMS: update Instagram image')}$('#resultUrl').textContent=imageUrl;$('#resultUrl').classList.remove('hidden');status('アップロードとCMSへの反映が完了しました。公開Newsページを再読み込みすると表示されます。','success')}catch(e){status(`処理に失敗しました: ${e.message}`,'error')}finally{btn.disabled=false}}
async function removeImage(){if(!token){status('先にGitHubへ接続してください。','error');return}const target=document.querySelector('input[name=target]:checked')?.value||'news';const btn=$('#removeBtn');btn.disabled=true;try{await loadCms();if(target==='news'){const id=$('#newsTarget').value;const item=(cms.news||[]).find(n=>n.id===id);if(!item)throw new Error('選択したNewsが見つかりません');item.image='';await saveCms(`CMS: remove image for ${id}`)}else if(target==='fallback'){cms.newsFallbackImage='';await saveCms('CMS: reset News fallback image')}else{cms.instagram=cms.instagram||{};cms.instagram.image='';await saveCms('CMS: remove Instagram image')}status('CMS上の画像指定を解除しました。アップロード済みファイル自体は削除していません。','success')}catch(e){status(`画像指定を解除できませんでした: ${e.message}`,'error')}finally{btn.disabled=false}}
async function createNews(){if(!token){status('先にGitHubへ接続してください。','error');return}const titleJa=$('#createTitleJa').value.trim(),titleEn=$('#createTitleEn').value.trim(),bodyJa=$('#createBodyJa').value.trim(),bodyEn=$('#createBodyEn').value.trim(),category=$('#createCategory').value,date=$('#createDate').value||today(),featured=$('#createFeatured').checked,file=$('#createImageFile').files[0];if(!titleJa||!bodyJa){status('Newsの日本語タイトルと本文を入力してください。','error');return}const btn=$('#createNewsBtn');btn.disabled=true;try{status('Newsを投稿しています…');let image='';if(file)image=await uploadAsset(file);await loadCms();cms.news=Array.isArray(cms.news)?cms.news:[];let base=`${date.replaceAll('-','')}-${slug(titleEn||titleJa)}`,id=base,i=2;while(cms.news.some(n=>n.id===id))id=`${base}-${i++}`;if(featured)cms.news.forEach(n=>n.featured=false);cms.news.push({date,category,featured,link:'news.html',image,title:{ja:titleJa,en:titleEn},body:{ja:bodyJa,en:bodyEn},id});await saveCms(`CMS: add News ${titleJa}`);$('#createTitleJa').value='';$('#createTitleEn').value='';$('#createBodyJa').value='';$('#createBodyEn').value='';$('#createCategory').value='Product';$('#createDate').value=today();$('#createFeatured').checked=false;$('#createImageFile').value='';$('#createPreview').innerHTML='<div class="preview-placeholder">画像を選択すると、ここにプレビューが表示されます。</div>';status(`News「${titleJa}」を投稿しました。公開Newsページを再読み込みすると表示されます。`,'success')}catch(e){status(`News投稿に失敗しました: ${e.message}`,'error')}finally{btn.disabled=false}}
document.addEventListener('DOMContentLoaded',()=>{$('#createDate').value=today();$('#connectBtn').addEventListener('click',connect);$('#imageFile').addEventListener('change',()=>previewFile('#imageFile','#preview'));$('#createImageFile').addEventListener('change',()=>previewFile('#createImageFile','#createPreview'));document.querySelectorAll('input[name=target]').forEach(r=>r.addEventListener('change',toggleTarget));$('#uploadBtn').addEventListener('click',uploadAndApply);$('#removeBtn').addEventListener('click',removeImage);$('#createNewsBtn').addEventListener('click',createNews);toggleTarget()});
})();