(()=>{
const OWNER='Kale1205',REPO='fde-site',BRANCH='main';
const API=`https://api.github.com/repos/${OWNER}/${REPO}`;
const RAW=`https://raw.githubusercontent.com/${OWNER}/${REPO}/${BRANCH}`;
const FULFILLMENT_ENDPOINT=String(window.FDE_CONTACT_API||'').trim();
const $=s=>document.querySelector(s);
let token='',cms=null,cmsSha='';
const status=(msg,type='')=>{const el=$('#adminStatus');el.textContent=msg;el.className=`status ${type}`.trim();el.hidden=false;el.scrollIntoView({behavior:'smooth',block:'nearest'})};
const headers=()=>({'Accept':'application/vnd.github+json','Authorization':`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28'});
const bytesToBase64=bytes=>{let bin='';const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)bin+=String.fromCharCode(...bytes.subarray(i,i+chunk));return btoa(bin)};
const utf8ToBase64=text=>bytesToBase64(new TextEncoder().encode(text));
const decodeBase64Utf8=b64=>new TextDecoder().decode(Uint8Array.from(atob(b64.replace(/\n/g,'')),c=>c.charCodeAt(0)));
const fileBase64=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file)});
const safeExt=file=>{const name=file.name.toLowerCase();if(name.endsWith('.png'))return'png';if(name.endsWith('.webp'))return'webp';if(name.endsWith('.gif'))return'gif';return'jpg'};
const safeName=file=>{const base=file.name.replace(/\.[^.]+$/,'').normalize('NFKD').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,42)||'image';const now=new Date();const stamp=`${now.getFullYear()}${String(now.getMonth()+1).padStart(2,'0')}${String(now.getDate()).padStart(2,'0')}-${String(now.getHours()).padStart(2,'0')}${String(now.getMinutes()).padStart(2,'0')}${String(now.getSeconds()).padStart(2,'0')}`;const rand=crypto.getRandomValues(new Uint32Array(1))[0].toString(16).slice(0,6);return`${stamp}-${base}-${rand}.${safeExt(file)}`};
const today=()=>new Date().toLocaleDateString('sv-SE');
const slug=s=>String(s||'item').normalize('NFKD').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,45)||'item';
const sortedNews=()=>[...(cms?.news||[])].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));
const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
async function api(path,options={}){const res=await fetch(`${API}${path}`,{...options,headers:{...headers(),...(options.headers||{})}});if(!res.ok){let detail='';try{const j=await res.json();detail=j.message||''}catch{}throw new Error(`${res.status} ${detail}`.trim())}return res.status===204?null:res.json()}
async function loadCms(newsSelectId='',faqSelectId=''){const r=await api(`/contents/content/site-content.json?ref=${encodeURIComponent(BRANCH)}`);cmsSha=r.sha;cms=JSON.parse(decodeBase64Utf8(r.content));cms.news=Array.isArray(cms.news)?cms.news:[];cms.faq=Array.isArray(cms.faq)?cms.faq:[];renderNewsOptions(newsSelectId);renderFaqOptions(faqSelectId)}
function renderNewsOptions(selectId=''){const sel=$('#editNewsTarget');if(!sel)return;const current=selectId||sel.value;sel.innerHTML='';sortedNews().forEach(n=>{const o=document.createElement('option');o.value=n.id;o.textContent=`${n.date||''} — ${(n.title&&n.title.ja)||n.id}${n.featured?' [TOP]':''}`;sel.appendChild(o)});sel.disabled=!sel.options.length;if(current&&[...sel.options].some(o=>o.value===current))sel.value=current;populateEditForm()}
function renderFaqOptions(selectId=''){const sel=$('#editFaqTarget');if(!sel)return;const current=selectId||sel.value;sel.innerHTML='';(cms?.faq||[]).forEach(item=>{const o=document.createElement('option');o.value=item.id;o.textContent=item.question?.ja||item.question?.en||item.id;sel.appendChild(o)});sel.disabled=!sel.options.length;if(current&&[...sel.options].some(o=>o.value===current))sel.value=current;populateFaqForm()}
function showPanel(name){document.querySelectorAll('[data-admin-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.adminPanel!==name));document.querySelectorAll('[data-admin-tab]').forEach(b=>b.classList.toggle('active',b.dataset.adminTab===name))}
function toggleTarget(){const target=document.querySelector('input[name=target]:checked')?.value||'fallback';const help={fallback:'画像が設定されていないNewsに共通で表示するデフォルト画像として設定します。',instagram:'Newsページ下部のInstagram紹介画像として設定します。'};$('#targetHelp').textContent=help[target]||help.fallback}
async function connect(){token=$('#token').value.trim();if(!token){status('GitHub tokenを入力してください。','error');return}const btn=$('#connectBtn');btn.disabled=true;try{const me=await fetch('https://api.github.com/user',{headers:headers()});if(!me.ok)throw new Error('GitHub認証に失敗しました');const user=await me.json();await loadCms();$('#adminTabs').classList.remove('hidden');showPanel('news');status(`${user.login} として接続しました。News・FAQ・メディア・注文後の納品管理を利用できます。`,'success')}catch(e){token='';status(`接続できませんでした: ${e.message}`,'error')}finally{btn.disabled=false}}
function validateImage(file){if(!file)return true;if(!file.type.startsWith('image/'))throw new Error('画像ファイルを選択してください。');if(file.size>8*1024*1024)throw new Error('画像は8MB以下にしてください。');return true}
function previewFile(inputSelector,boxSelector,emptyText='画像を選択すると、ここにプレビューが表示されます。'){const file=$(inputSelector)?.files?.[0];const box=$(boxSelector);if(!box)return;if(!file){box.innerHTML=`<div class="preview-placeholder">${emptyText}</div>`;return}try{validateImage(file)}catch(e){status(e.message,'error');$(inputSelector).value='';return}const u=URL.createObjectURL(file);box.innerHTML=`<img src="${u}" alt="preview">`}
function renderCurrentImage(src){const box=$('#editCurrentImage');if(!box)return;if(src)box.innerHTML=`<img src="${src}" alt="current News image">`;else box.innerHTML='<div class="preview-placeholder">個別画像は未設定です。公開ページではNewsデフォルト画像が使われます。</div>'}
async function uploadAsset(file){validateImage(file);const filename=safeName(file);const now=new Date();const path=`assets/cms/${now.getFullYear()}/${String(now.getMonth()+1).padStart(2,'0')}/${filename}`;const content=await fileBase64(file);await api(`/contents/${path}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`CMS: upload ${filename}`,content,branch:BRANCH})});return `${RAW}/${path}`}
async function saveCms(message,newsSelectId='',faqSelectId=''){const body={message,content:utf8ToBase64(JSON.stringify(cms,null,2)+'\n'),sha:cmsSha,branch:BRANCH};await api('/contents/content/site-content.json',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await loadCms(newsSelectId,faqSelectId)}
function populateEditForm(){const id=$('#editNewsTarget')?.value;const n=(cms?.news||[]).find(x=>x.id===id);const fields=$('#editNewsFields');if(fields)fields.classList.toggle('hidden',!n);if(!n)return;$('#editTitleJa').value=n.title?.ja||'';$('#editTitleEn').value=n.title?.en||'';$('#editBodyJa').value=n.body?.ja||'';$('#editBodyEn').value=n.body?.en||'';$('#editCategory').value=n.category||'Product';$('#editDate').value=n.date||today();$('#editFeatured').checked=!!n.featured;$('#editImageFile').value='';renderCurrentImage(n.image||'');previewFile('#editImageFile','#editPreview','新しい画像を選択すると表示されます。')}
function populateFaqForm(){const id=$('#editFaqTarget')?.value;const item=(cms?.faq||[]).find(x=>x.id===id);const fields=$('#editFaqFields');if(fields)fields.classList.toggle('hidden',!item);if(!item)return;$('#faqEditQJa').value=item.question?.ja||'';$('#faqEditQEn').value=item.question?.en||'';$('#faqEditAJa').value=item.answer?.ja||'';$('#faqEditAEn').value=item.answer?.en||''}
async function uploadAndApply(){if(!token){status('先にGitHubへ接続してください。','error');return}const file=$('#imageFile').files[0];if(!file){status('画像を選択してください。','error');return}const target=document.querySelector('input[name=target]:checked')?.value||'fallback';const btn=$('#uploadBtn');btn.disabled=true;try{status('画像をアップロードしています…');const imageUrl=await uploadAsset(file);if(target==='fallback'){cms.newsFallbackImage=imageUrl;await saveCms('CMS: update News fallback image',$('#editNewsTarget')?.value||'',$('#editFaqTarget')?.value||'')}else{cms.instagram=cms.instagram||{};cms.instagram.image=imageUrl;await saveCms('CMS: update Instagram image',$('#editNewsTarget')?.value||'',$('#editFaqTarget')?.value||'')}$('#resultUrl').textContent=imageUrl;$('#resultUrl').classList.remove('hidden');status('アップロードとCMSへの反映が完了しました。公開ページを再読み込みすると表示されます。','success')}catch(e){status(`処理に失敗しました: ${e.message}`,'error')}finally{btn.disabled=false}}
async function removeImage(){if(!token){status('先にGitHubへ接続してください。','error');return}const target=document.querySelector('input[name=target]:checked')?.value||'fallback';const btn=$('#removeBtn');btn.disabled=true;try{if(target==='fallback'){cms.newsFallbackImage='';await saveCms('CMS: reset News fallback image',$('#editNewsTarget')?.value||'',$('#editFaqTarget')?.value||'')}else{cms.instagram=cms.instagram||{};cms.instagram.image='';await saveCms('CMS: remove Instagram image',$('#editNewsTarget')?.value||'',$('#editFaqTarget')?.value||'')}status('CMS上の画像指定を解除しました。アップロード済みファイル自体は削除していません。','success')}catch(e){status(`画像指定を解除できませんでした: ${e.message}`,'error')}finally{btn.disabled=false}}
async function createNews(){if(!token){status('先にGitHubへ接続してください。','error');return}const titleJa=$('#createTitleJa').value.trim(),titleEn=$('#createTitleEn').value.trim(),bodyJa=$('#createBodyJa').value.trim(),bodyEn=$('#createBodyEn').value.trim(),category=$('#createCategory').value,date=$('#createDate').value||today(),featured=$('#createFeatured').checked,file=$('#createImageFile').files[0];if(!titleJa||!bodyJa){status('Newsの日本語タイトルと本文を入力してください。','error');return}const btn=$('#createNewsBtn');btn.disabled=true;try{status('Newsを投稿しています…');let image='';if(file)image=await uploadAsset(file);let base=`${date.replaceAll('-','')}-${slug(titleEn||titleJa)}`,id=base,i=2;while((cms.news||[]).some(n=>n.id===id))id=`${base}-${i++}`;if(featured)cms.news.forEach(n=>n.featured=false);cms.news.push({date,category,featured,link:'news.html',image,title:{ja:titleJa,en:titleEn},body:{ja:bodyJa,en:bodyEn},id});await saveCms(`CMS: add News ${titleJa}`,id,$('#editFaqTarget')?.value||'');$('#createTitleJa').value='';$('#createTitleEn').value='';$('#createBodyJa').value='';$('#createBodyEn').value='';$('#createCategory').value='Product';$('#createDate').value=today();$('#createFeatured').checked=false;$('#createImageFile').value='';$('#createPreview').innerHTML='<div class="preview-placeholder">画像を選択すると、ここにプレビューが表示されます。</div>';status(`News「${titleJa}」を投稿しました。`,'success')}catch(e){status(`News投稿に失敗しました: ${e.message}`,'error')}finally{btn.disabled=false}}
async function saveEditedNews(){if(!token){status('先にGitHubへ接続してください。','error');return}const id=$('#editNewsTarget').value;const item=(cms?.news||[]).find(n=>n.id===id);if(!item){status('編集するNewsが見つかりません。','error');return}const titleJa=$('#editTitleJa').value.trim(),bodyJa=$('#editBodyJa').value.trim();if(!titleJa||!bodyJa){status('日本語タイトルと本文を入力してください。','error');return}const btn=$('#saveNewsBtn');btn.disabled=true;try{status('Newsの変更を保存しています…');const file=$('#editImageFile').files[0];if(file)item.image=await uploadAsset(file);item.title=item.title||{};item.body=item.body||{};item.title.ja=titleJa;item.title.en=$('#editTitleEn').value.trim();item.body.ja=bodyJa;item.body.en=$('#editBodyEn').value.trim();item.category=$('#editCategory').value;item.date=$('#editDate').value||today();item.link='news.html';const featured=$('#editFeatured').checked;if(featured)(cms.news||[]).forEach(n=>n.featured=n.id===id);else item.featured=false;await saveCms(`CMS: edit News ${titleJa}`,id,$('#editFaqTarget')?.value||'');status(`News「${titleJa}」を更新しました。`,'success')}catch(e){status(`News更新に失敗しました: ${e.message}`,'error')}finally{btn.disabled=false}}
async function removeEditedNewsImage(){if(!token){status('先にGitHubへ接続してください。','error');return}const id=$('#editNewsTarget').value;const item=(cms?.news||[]).find(n=>n.id===id);if(!item)return;const btn=$('#removeNewsImageBtn');btn.disabled=true;try{item.image='';await saveCms(`CMS: remove image for ${id}`,id,$('#editFaqTarget')?.value||'');status('この記事の個別画像を解除しました。Newsデフォルト画像が使用されます。','success')}catch(e){status(`画像解除に失敗しました: ${e.message}`,'error')}finally{btn.disabled=false}}
async function deleteNews(){if(!token){status('先にGitHubへ接続してください。','error');return}const id=$('#editNewsTarget').value;const item=(cms?.news||[]).find(n=>n.id===id);if(!item)return;const title=item.title?.ja||id;if(!window.confirm(`News「${title}」を削除します。\nこの操作を続けますか？`))return;const btn=$('#deleteNewsBtn');btn.disabled=true;try{const wasFeatured=!!item.featured;cms.news=(cms.news||[]).filter(n=>n.id!==id);if(wasFeatured&&cms.news.length&&!cms.news.some(n=>n.featured)){cms.news.sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));cms.news[0].featured=true}const next=[...cms.news].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')))[0]?.id||'';await saveCms(`CMS: delete News ${title}`,next,$('#editFaqTarget')?.value||'');status(`News「${title}」を削除しました。`,'success')}catch(e){status(`News削除に失敗しました: ${e.message}`,'error')}finally{btn.disabled=false}}
async function createFaq(){if(!token){status('先にGitHubへ接続してください。','error');return}const qJa=$('#faqCreateQJa').value.trim(),qEn=$('#faqCreateQEn').value.trim(),aJa=$('#faqCreateAJa').value.trim(),aEn=$('#faqCreateAEn').value.trim();if(!qJa||!aJa){status('FAQの日本語の質問と回答を入力してください。','error');return}const btn=$('#createFaqBtn');btn.disabled=true;try{let base=slug(qEn||qJa),id=base,i=2;while((cms.faq||[]).some(x=>x.id===id))id=`${base}-${i++}`;cms.faq.push({id,question:{ja:qJa,en:qEn},answer:{ja:aJa,en:aEn}});await saveCms(`CMS: add FAQ ${qJa}`,$('#editNewsTarget')?.value||'',id);$('#faqCreateQJa').value='';$('#faqCreateQEn').value='';$('#faqCreateAJa').value='';$('#faqCreateAEn').value='';status(`FAQ「${qJa}」を追加しました。`,'success')}catch(e){status(`FAQ追加に失敗しました: ${e.message}`,'error')}finally{btn.disabled=false}}
async function saveFaq(){if(!token){status('先にGitHubへ接続してください。','error');return}const id=$('#editFaqTarget').value;const item=(cms?.faq||[]).find(x=>x.id===id);if(!item){status('FAQが見つかりません。','error');return}const qJa=$('#faqEditQJa').value.trim(),qEn=$('#faqEditQEn').value.trim(),aJa=$('#faqEditAJa').value.trim(),aEn=$('#faqEditAEn').value.trim();if(!qJa||!aJa){status('FAQの日本語の質問と回答を入力してください。','error');return}const btn=$('#saveFaqBtn');btn.disabled=true;try{item.question=item.question||{};item.answer=item.answer||{};item.question.ja=qJa;item.question.en=qEn;item.answer.ja=aJa;item.answer.en=aEn;await saveCms(`CMS: edit FAQ ${qJa}`,$('#editNewsTarget')?.value||'',id);status(`FAQ「${qJa}」を更新しました。`,'success')}catch(e){status(`FAQ更新に失敗しました: ${e.message}`,'error')}finally{btn.disabled=false}}
async function deleteFaq(){if(!token){status('先にGitHubへ接続してください。','error');return}const id=$('#editFaqTarget').value;const item=(cms?.faq||[]).find(x=>x.id===id);if(!item)return;const title=item.question?.ja||id;if(!window.confirm(`FAQ「${title}」を削除します。\nこの操作を続けますか？`))return;const btn=$('#deleteFaqBtn');btn.disabled=true;try{cms.faq=(cms.faq||[]).filter(x=>x.id!==id);const next=cms.faq[0]?.id||'';await saveCms(`CMS: delete FAQ ${title}`,$('#editNewsTarget')?.value||'',next);status(`FAQ「${title}」を削除しました。`,'success')}catch(e){status(`FAQ削除に失敗しました: ${e.message}`,'error')}finally{btn.disabled=false}}
function validUrl(value){try{const u=new URL(value);return u.protocol==='https:'||u.protocol==='http:'}catch{return false}}
async function sendFulfillment(){const orderId=$('#fulfillOrderId').value.trim(),product=$('#fulfillProduct').value,name=$('#fulfillName').value.trim(),email=$('#fulfillEmail').value.trim(),invoiceUrl=$('#invoiceUrl').value.trim(),installerUrl=$('#installerUrl').value.trim(),note=$('#fulfillNote').value.trim(),adminKey=$('#fulfillmentKey').value.trim();if(!FULFILLMENT_ENDPOINT){status('Cloudflare WorkerのURLが設定されていません。','error');return}if(!orderId||!name||!email||!product||!invoiceUrl||!installerUrl||!adminKey){status('注文番号・購入者・メール・製品・請求書URL・インストーラーURL・Admin keyは必須です。','error');return}if(!emailPattern.test(email)){status('購入者メールアドレスの形式が正しくありません。','error');return}if(!validUrl(invoiceUrl)||!validUrl(installerUrl)){status('請求書URLとインストーラーURLは http/https の有効なURLを入力してください。','error');return}const btn=$('#sendFulfillmentBtn');btn.disabled=true;try{status('請求書とインストーラー案内を送信しています…');const res=await fetch(FULFILLMENT_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({type:'fulfillment',adminKey,orderId,product,name,email,invoiceUrl,installerUrl,note,lang:'ja'})});const data=await res.json().catch(()=>({}));if(!res.ok||data.ok===false)throw new Error(data.error||`HTTP ${res.status}`);status(`注文 ${orderId} の納品メールを ${email} へ送信しました。`,'success')}catch(e){status(`納品メールを送信できませんでした: ${e.message}`,'error')}finally{btn.disabled=false}}
document.addEventListener('DOMContentLoaded',()=>{$('#createDate').value=today();$('#connectBtn').addEventListener('click',connect);document.querySelectorAll('[data-admin-tab]').forEach(b=>b.addEventListener('click',()=>showPanel(b.dataset.adminTab)));$('#imageFile').addEventListener('change',()=>previewFile('#imageFile','#preview'));$('#createImageFile').addEventListener('change',()=>previewFile('#createImageFile','#createPreview'));$('#editImageFile').addEventListener('change',()=>previewFile('#editImageFile','#editPreview','新しい画像を選択すると表示されます。'));$('#editNewsTarget').addEventListener('change',populateEditForm);$('#editFaqTarget').addEventListener('change',populateFaqForm);document.querySelectorAll('input[name=target]').forEach(r=>r.addEventListener('change',toggleTarget));$('#uploadBtn').addEventListener('click',uploadAndApply);$('#removeBtn').addEventListener('click',removeImage);$('#createNewsBtn').addEventListener('click',createNews);$('#saveNewsBtn').addEventListener('click',saveEditedNews);$('#removeNewsImageBtn').addEventListener('click',removeEditedNewsImage);$('#deleteNewsBtn').addEventListener('click',deleteNews);$('#createFaqBtn').addEventListener('click',createFaq);$('#saveFaqBtn').addEventListener('click',saveFaq);$('#deleteFaqBtn').addEventListener('click',deleteFaq);$('#sendFulfillmentBtn').addEventListener('click',sendFulfillment);toggleTarget()});
})();