(()=>{
const OWNER='Kale1205',REPO='fde-site',BRANCH='main';
const API=`https://api.github.com/repos/${OWNER}/${REPO}`;
const RAW=`https://raw.githubusercontent.com/${OWNER}/${REPO}/${BRANCH}`;
const $=s=>document.querySelector(s);
let token='',cms=null,cmsSha='';
const status=(msg,type='')=>{const el=$('#adminStatus');if(!el)return;el.textContent=msg;el.className=`status ${type}`.trim();el.hidden=false};
const headers=()=>({'Accept':'application/vnd.github+json','Authorization':`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28'});
const bytesToBase64=bytes=>{let bin='';for(let i=0;i<bytes.length;i+=0x8000)bin+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(bin)};
const utf8ToBase64=text=>bytesToBase64(new TextEncoder().encode(text));
const decodeBase64Utf8=b64=>new TextDecoder().decode(Uint8Array.from(atob(String(b64).replace(/\n/g,'')),c=>c.charCodeAt(0)));
const fileBase64=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file)});
const today=()=>new Date().toLocaleDateString('sv-SE');
const slug=s=>String(s||'item').normalize('NFKD').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,45)||'item';
const sortedNews=()=>[...(cms?.news||[])].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));
function safeExt(file){const name=file.name.toLowerCase();if(name.endsWith('.png'))return'png';if(name.endsWith('.webp'))return'webp';if(name.endsWith('.gif'))return'gif';return'jpg'}
function safeName(file){const base=file.name.replace(/\.[^.]+$/,'').normalize('NFKD').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,42)||'image';const now=new Date();const stamp=`${now.getFullYear()}${String(now.getMonth()+1).padStart(2,'0')}${String(now.getDate()).padStart(2,'0')}-${String(now.getHours()).padStart(2,'0')}${String(now.getMinutes()).padStart(2,'0')}${String(now.getSeconds()).padStart(2,'0')}`;const rand=crypto.getRandomValues(new Uint32Array(1))[0].toString(16).slice(0,6);return`${stamp}-${base}-${rand}.${safeExt(file)}`}
async function api(path,options={}){const res=await fetch(`${API}${path}`,{...options,headers:{...headers(),...(options.headers||{})}});if(!res.ok){let detail='';try{detail=(await res.json()).message||''}catch{}throw new Error(`${res.status} ${detail}`.trim())}return res.status===204?null:res.json()}
async function loadCms(newsSelectId=''){const r=await api(`/contents/content/site-content.json?ref=${encodeURIComponent(BRANCH)}`);cmsSha=r.sha;cms=JSON.parse(decodeBase64Utf8(r.content));cms.news=Array.isArray(cms.news)?cms.news:[];renderNewsOptions(newsSelectId)}
async function saveCms(message,newsSelectId=''){const body={message,content:utf8ToBase64(JSON.stringify(cms,null,2)+'\n'),sha:cmsSha,branch:BRANCH};await api('/contents/content/site-content.json',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await loadCms(newsSelectId)}
function showPanel(name){document.querySelectorAll('[data-admin-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.adminPanel!==name));document.querySelectorAll('[data-admin-tab]').forEach(b=>b.classList.toggle('active',b.dataset.adminTab===name))}
function renderNewsOptions(selectId=''){const sel=$('#editNewsTarget');if(!sel)return;const current=selectId||sel.value;sel.innerHTML='';sortedNews().forEach(n=>{const o=document.createElement('option');o.value=n.id;o.textContent=`${n.date||''} — ${(n.title&&n.title.ja)||n.id}${n.featured?' [TOP]':''}`;sel.appendChild(o)});sel.disabled=!sel.options.length;if(current&&[...sel.options].some(o=>o.value===current))sel.value=current;populateEditForm()}
function populateEditForm(){const n=(cms?.news||[]).find(x=>x.id===$('#editNewsTarget')?.value);const fields=$('#editNewsFields');if(fields)fields.classList.toggle('hidden',!n);if(!n)return;$('#editTitleJa').value=n.title?.ja||'';$('#editTitleEn').value=n.title?.en||'';$('#editBodyJa').value=n.body?.ja||'';$('#editBodyEn').value=n.body?.en||'';$('#editCategory').value=n.category||'Product';$('#editDate').value=n.date||today();$('#editFeatured').checked=!!n.featured;$('#editImageFile').value='';renderCurrentImage(n.image||'');previewFile('#editImageFile','#editPreview','新しい画像を選択すると表示されます。')}
async function connect(){token=$('#token')?.value.trim()||'';if(!token){status('GitHub tokenを入力してください。','error');return}const btn=$('#connectBtn');btn.disabled=true;try{const me=await fetch('https://api.github.com/user',{headers:headers()});if(!me.ok)throw new Error('GitHub認証に失敗しました');const user=await me.json();await loadCms();$('#adminTabs')?.classList.remove('hidden');showPanel('news');status(`${user.login} として接続しました。News・FAQ・メディア管理を利用できます。`,'success')}catch(e){token='';status(`接続できませんでした: ${e.message}`,'error')}finally{btn.disabled=false}}
function validateImage(file){if(!file)return true;if(!file.type.startsWith('image/'))throw new Error('画像ファイルを選択してください。');if(file.size>8*1024*1024)throw new Error('画像は8MB以下にしてください。');return true}
function previewFile(inputSelector,boxSelector,emptyText='画像を選択すると、ここにプレビューが表示されます。'){const file=$(inputSelector)?.files?.[0];const box=$(boxSelector);if(!box)return;if(!file){box.innerHTML=`<div class="preview-placeholder">${emptyText}</div>`;return}try{validateImage(file)}catch(e){status(e.message,'error');$(inputSelector).value='';return}const u=URL.createObjectURL(file);box.innerHTML=`<img src="${u}" alt="preview">`}
function renderCurrentImage(src){const box=$('#editCurrentImage');if(!box)return;box.innerHTML=src?`<img src="${src}" alt="current News image">`:'<div class="preview-placeholder">個別画像は未設定です。公開ページではNewsデフォルト画像が使われます。</div>'}
async function uploadAsset(file){validateImage(file);const filename=safeName(file);const now=new Date();const path=`assets/cms/${now.getFullYear()}/${String(now.getMonth()+1).padStart(2,'0')}/${filename}`;const content=await fileBase64(file);await api(`/contents/${path}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`CMS: upload ${filename}`,content,branch:BRANCH})});return `${RAW}/${path}`}
function toggleTarget(){const target=document.querySelector('input[name=target]:checked')?.value||'fallback';const help={fallback:'画像が設定されていないNewsに共通で表示するデフォルト画像として設定します。',instagram:'Newsページ下部のInstagram紹介画像として設定します。'};if($('#targetHelp'))$('#targetHelp').textContent=help[target]||help.fallback}
async function uploadAndApply(){if(!token){status('先にGitHubへ接続してください。','error');return}const file=$('#imageFile')?.files?.[0];if(!file){status('画像を選択してください。','error');return}const target=document.querySelector('input[name=target]:checked')?.value||'fallback';const btn=$('#uploadBtn');btn.disabled=true;try{status('画像をアップロードしています…');const imageUrl=await uploadAsset(file);if(target==='fallback')cms.newsFallbackImage=imageUrl;else{cms.instagram=cms.instagram||{};cms.instagram.image=imageUrl}await saveCms(target==='fallback'?'CMS: update News fallback image':'CMS: update Instagram image',$('#editNewsTarget')?.value||'');if($('#resultUrl')){$('#resultUrl').textContent=imageUrl;$('#resultUrl').classList.remove('hidden')}status('アップロードとCMSへの反映が完了しました。','success')}catch(e){status(`処理に失敗しました: ${e.message}`,'error')}finally{btn.disabled=false}}
async function removeImage(){if(!token){status('先にGitHubへ接続してください。','error');return}const target=document.querySelector('input[name=target]:checked')?.value||'fallback';const btn=$('#removeBtn');btn.disabled=true;try{if(target==='fallback')cms.newsFallbackImage='';else{cms.instagram=cms.instagram||{};cms.instagram.image=''}await saveCms(target==='fallback'?'CMS: reset News fallback image':'CMS: remove Instagram image',$('#editNewsTarget')?.value||'');status('CMS上の画像指定を解除しました。アップロード済みファイル自体は削除していません。','success')}catch(e){status(`画像指定を解除できませんでした: ${e.message}`,'error')}finally{btn.disabled=false}}
async function createNews(){if(!token){status('先にGitHubへ接続してください。','error');return}const titleJa=$('#createTitleJa').value.trim(),titleEn=$('#createTitleEn').value.trim(),bodyJa=$('#createBodyJa').value.trim(),bodyEn=$('#createBodyEn').value.trim(),category=$('#createCategory').value,date=$('#createDate').value||today(),featured=$('#createFeatured').checked,file=$('#createImageFile').files[0];if(!titleJa||!bodyJa){status('Newsの日本語タイトルと本文を入力してください。','error');return}if(!titleEn||!bodyEn){status('英語版Newsが未生成です。もう一度投稿してください。','error');return}const btn=$('#createNewsBtn');btn.disabled=true;try{status('Newsを投稿しています…');let image='';if(file)image=await uploadAsset(file);let base=`${date.replaceAll('-','')}-${slug(titleEn||titleJa)}`,id=base,i=2;while(cms.news.some(n=>n.id===id))id=`${base}-${i++}`;if(featured)cms.news.forEach(n=>n.featured=false);cms.news.push({date,category,featured,link:'news.html',image,title:{ja:titleJa,en:titleEn},body:{ja:bodyJa,en:bodyEn},translationStatus:'ja-en',id});await saveCms(`CMS: add bilingual News ${titleJa}`,id);$('#createTitleJa').value='';$('#createTitleEn').value='';$('#createBodyJa').value='';$('#createBodyEn').value='';$('#createCategory').value='Product';$('#createDate').value=today();$('#createFeatured').checked=false;$('#createImageFile').value='';$('#createPreview').innerHTML='<div class="preview-placeholder">画像を選択すると、ここにプレビューが表示されます。</div>';status(`News「${titleJa}」を投稿しました。`,'success')}catch(e){status(`News投稿に失敗しました: ${e.message}`,'error')}finally{btn.disabled=false}}
async function saveEditedNews(){if(!token){status('先にGitHubへ接続してください。','error');return}const id=$('#editNewsTarget').value,item=cms.news.find(n=>n.id===id);if(!item){status('編集するNewsが見つかりません。','error');return}const titleJa=$('#editTitleJa').value.trim(),titleEn=$('#editTitleEn').value.trim(),bodyJa=$('#editBodyJa').value.trim(),bodyEn=$('#editBodyEn').value.trim();if(!titleJa||!bodyJa){status('日本語タイトルと本文を入力してください。','error');return}if(!titleEn||!bodyEn){status('英語版Newsが未生成です。もう一度保存してください。','error');return}const btn=$('#saveNewsBtn');btn.disabled=true;try{status('Newsの変更を保存しています…');const file=$('#editImageFile').files[0];if(file)item.image=await uploadAsset(file);item.title={ja:titleJa,en:titleEn};item.body={ja:bodyJa,en:bodyEn};item.translationStatus='ja-en';item.category=$('#editCategory').value;item.date=$('#editDate').value||today();item.link='news.html';const featured=$('#editFeatured').checked;if(featured)cms.news.forEach(n=>n.featured=n.id===id);else item.featured=false;await saveCms(`CMS: edit bilingual News ${titleJa}`,id);status(`News「${titleJa}」を更新しました。`,'success')}catch(e){status(`News更新に失敗しました: ${e.message}`,'error')}finally{btn.disabled=false}}
async function removeEditedNewsImage(){if(!token){status('先にGitHubへ接続してください。','error');return}const id=$('#editNewsTarget').value,item=cms.news.find(n=>n.id===id);if(!item)return;const btn=$('#removeNewsImageBtn');btn.disabled=true;try{item.image='';await saveCms(`CMS: remove image for ${id}`,id);status('この記事の個別画像を解除しました。','success')}catch(e){status(`画像解除に失敗しました: ${e.message}`,'error')}finally{btn.disabled=false}}
async function deleteNews(){if(!token){status('先にGitHubへ接続してください。','error');return}const id=$('#editNewsTarget').value,item=cms.news.find(n=>n.id===id);if(!item)return;const title=item.title?.ja||id;if(!confirm(`News「${title}」を削除します。\nこの操作を続けますか？`))return;const btn=$('#deleteNewsBtn');btn.disabled=true;try{const wasFeatured=!!item.featured;cms.news=cms.news.filter(n=>n.id!==id);if(wasFeatured&&cms.news.length&&!cms.news.some(n=>n.featured)){cms.news.sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));cms.news[0].featured=true}const next=sortedNews()[0]?.id||'';await saveCms(`CMS: delete News ${title}`,next);status(`News「${title}」を削除しました。`,'success')}catch(e){status(`News削除に失敗しました: ${e.message}`,'error')}finally{btn.disabled=false}}
function init(){
 if($('#createDate'))$('#createDate').value=today();
 $('#connectBtn')?.addEventListener('click',connect);
 document.querySelectorAll('[data-admin-tab]').forEach(b=>b.addEventListener('click',()=>showPanel(b.dataset.adminTab)));
 $('#imageFile')?.addEventListener('change',()=>previewFile('#imageFile','#preview'));
 $('#createImageFile')?.addEventListener('change',()=>previewFile('#createImageFile','#createPreview'));
 $('#editImageFile')?.addEventListener('change',()=>previewFile('#editImageFile','#editPreview','新しい画像を選択すると表示されます。'));
 $('#editNewsTarget')?.addEventListener('change',populateEditForm);
 document.querySelectorAll('input[name=target]').forEach(r=>r.addEventListener('change',toggleTarget));
 $('#uploadBtn')?.addEventListener('click',uploadAndApply);
 $('#removeBtn')?.addEventListener('click',removeImage);
 $('#createNewsBtn')?.addEventListener('click',createNews);
 $('#saveNewsBtn')?.addEventListener('click',saveEditedNews);
 $('#removeNewsImageBtn')?.addEventListener('click',removeEditedNewsImage);
 $('#deleteNewsBtn')?.addEventListener('click',deleteNews);
 toggleTarget();
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
