(()=>{
const ENDPOINT=String(window.FDE_CONTACT_API||'').trim();
const $=(s,c=document)=>c.querySelector(s);
const EMAIL=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const ORDER=/^BK-\d{8}-[A-F0-9]{8}$/i;
const STEPS=['order_received','billing_preparation','awaiting_payment','payment_confirmed','preparing_delivery','delivered'];
const COPY={
 ja:{title:'注文状況を確認する',lead:'見積書兼注文書に記載された注文番号と、注文時に使用したメールアドレスを入力してください。',order:'注文番号',email:'購入時メールアドレス',submit:'状況を照会',checking:'確認中…',privacy:'第三者による照会を防ぐため、注文番号と購入時メールアドレスの両方を確認します。',product:'製品',plan:'契約方法',price:'注文金額',valid:'見積有効期限',updated:'最終更新',help:'確認できる内容',help1:'注文受付・見積書送信',help2:'請求・支払い確認の進行状況',help3:'製品の納品状況',helpContact:'内容に相違がある場合はContactからお問い合わせください。',invalid:'注文番号と有効なメールアドレスを入力してください。',notFound:'注文情報を確認できませんでした。注文番号と購入時メールアドレスをご確認ください。',notConfigured:'注文照会機能の保存領域がまだ有効化されていません。',failed:'状況を取得できませんでした。時間をおいて再度お試しください。',one:'買い切り',monthly:'月額プラン',steps:{order_received:['注文受付','見積書兼注文書を送信済みです。'],billing_preparation:['請求準備','請求・支払い方法を準備しています。'],awaiting_payment:['支払い待ち','ご案内した方法での支払いを確認中です。'],payment_confirmed:['支払い確認済み','支払い確認が完了しました。'],preparing_delivery:['納品準備','請求書とインストーラーを準備しています。'],delivered:['納品完了','請求書とインストーラーの案内を送信済みです。']}},
 en:{title:'Check your order status',lead:'Enter the Order ID shown on your quotation/order form and the email address used for the order.',order:'Order ID',email:'Order email address',submit:'Check status',checking:'Checking…',privacy:'For security, both the Order ID and the email address used for the order must match.',product:'Product',plan:'Plan',price:'Order total',valid:'Quote valid until',updated:'Last updated',help:'What you can check',help1:'Order receipt and quotation',help2:'Billing and payment progress',help3:'Product delivery status',helpContact:'If the information looks incorrect, contact us from the Contact page.',invalid:'Enter a valid Order ID and email address.',notFound:'We could not verify the order. Check the Order ID and order email address.',notConfigured:'The order-status storage has not been enabled yet.',failed:'The status could not be retrieved. Please try again later.',one:'One-time purchase',monthly:'Monthly plan',steps:{order_received:['Order received','Your quotation and order form has been sent.'],billing_preparation:['Billing preparation','Billing and payment instructions are being prepared.'],awaiting_payment:['Awaiting payment','We are waiting to confirm payment.'],payment_confirmed:['Payment confirmed','Payment confirmation is complete.'],preparing_delivery:['Preparing delivery','Your invoice and installer are being prepared.'],delivered:['Delivered','The invoice and installer information has been sent.']}}
};
const lang=()=>document.documentElement.lang||localStorage.getItem('fde-lang')||'ja';
const cp=()=>COPY[lang()]||COPY.en;
function applyCopy(){const c=cp();$('#customerTitle').textContent=c.title;$('#customerLead').textContent=c.lead;$('#orderIdLabel').textContent=c.order;$('#emailLabel').textContent=c.email;$('#statusSubmit').textContent=c.submit;$('#privacyNote').textContent=c.privacy;$('#statusProductLabel').textContent=c.product;$('#statusPlanLabel').textContent=c.plan;$('#statusPriceLabel').textContent=c.price;$('#statusValidLabel').textContent=c.valid;$('#statusUpdatedLabel').textContent=c.updated;$('#helpTitle').textContent=c.help;$('#help1').textContent=c.help1;$('#help2').textContent=c.help2;$('#help3').textContent=c.help3;$('#helpContact').textContent=c.helpContact}
function displayDate(iso){if(!iso)return'—';const d=new Date(`${iso}T00:00:00`);return Number.isNaN(d.getTime())?iso:d.toLocaleDateString(lang())}
function render(data){const c=cp(),index=Math.max(0,STEPS.indexOf(data.status));$('#statusError').hidden=true;$('#statusResult').hidden=false;$('#resultOrderId').textContent=data.orderId;$('#resultProduct').textContent=data.product||'—';$('#resultPlan').textContent=data.plan==='monthly'?c.monthly:c.one;$('#resultPrice').textContent=data.price||'—';$('#resultValid').textContent=displayDate(data.validUntil);$('#resultUpdated').textContent=data.updatedAt?new Date(data.updatedAt).toLocaleString(lang()):'—';const current=c.steps[data.status]||c.steps.order_received;$('#statusBadge').textContent=current[0];const box=$('#statusTimeline');box.innerHTML='';STEPS.forEach((key,i)=>{const [title,desc]=c.steps[key];const row=document.createElement('div');row.className=`status-step ${i<index?'done':i===index?'current':''}`;row.innerHTML=`<div class="status-step-marker"><div class="status-step-dot">${i<index?'✓':i+1}</div></div><div class="status-step-copy"><strong></strong><span></span></div>`;row.querySelector('strong').textContent=title;row.querySelector('span').textContent=desc;box.appendChild(row)});$('#statusMessage').textContent=data.message||current[1]}
function showError(text){$('#statusResult').hidden=true;const el=$('#statusError');el.textContent=text;el.hidden=false}
async function lookup(){const c=cp(),orderId=$('#statusOrderId').value.trim().toUpperCase(),email=$('#statusEmail').value.trim().toLowerCase();if(!ORDER.test(orderId)||!EMAIL.test(email)){showError(c.invalid);return}if(!ENDPOINT){showError(c.failed);return}const btn=$('#statusSubmit');btn.disabled=true;btn.textContent=c.checking;try{const res=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({type:'status_lookup',orderId,email,lang:lang()})});const data=await res.json().catch(()=>({}));if(!res.ok||data.ok===false){if(data.error==='ORDER_STATUS_NOT_CONFIGURED')showError(c.notConfigured);else if(data.error==='ORDER_NOT_FOUND')showError(c.notFound);else showError(c.failed);return}render(data)}catch(e){console.warn('Status lookup failed',e);showError(c.failed)}finally{btn.disabled=false;btn.textContent=c.submit}}
function init(){applyCopy();$('#statusForm').addEventListener('submit',e=>{e.preventDefault();lookup()});$('#statusOrderId').addEventListener('input',e=>{e.target.value=e.target.value.toUpperCase();$('#statusError').hidden=true});$('#statusEmail').addEventListener('input',()=>{$('#statusError').hidden=true});$('#lang')?.addEventListener('change',()=>setTimeout(applyCopy,0));new MutationObserver(applyCopy).observe(document.documentElement,{attributes:true,attributeFilter:['lang']})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();