(()=>{
const FAQ_URL='content/faq-content.json';
const $=(s,c=document)=>c.querySelector(s);
const lang=()=>document.querySelector('#lang')?.value||localStorage.getItem('fde-lang')||document.documentElement.lang||'ja';
const UI={
 ja:{search:'質問・回答・関連語から検索',help:'漢字・かな・カナの表記ゆれや関連語も含めて検索します。カテゴリーから探すこともできます。',popular:'よくある質問',popularNote:'特に確認されやすい内容',browse:'カテゴリーから探す',browseNote:'分野を選んでFAQを絞り込みます',all:'すべて',results:'検索結果',found:n=>`${n}件見つかりました`,none:'該当するFAQが見つかりませんでした。',noneHelp:'別の言葉で検索するか、カテゴリーから探してください。',reset:'選択を解除'},
 en:{search:'Search questions, answers and related terms',help:'Search includes related terms and common wording variations. You can also browse by category.',popular:'Popular questions',popularNote:'Frequently checked topics',browse:'Browse by category',browseNote:'Choose a topic to narrow the FAQ list',all:'All',results:'Search results',found:n=>`${n} result${n===1?'':'s'} found`,none:'No matching FAQ was found.',noneHelp:'Try different wording or browse by category.',reset:'Clear selection'},
 'zh-CN':{search:'搜索问题、回答和相关词',help:'搜索会包含相关词和常见表达差异，也可以按分类查找。',popular:'常见问题',popularNote:'最常被确认的内容',browse:'按分类查找',browseNote:'选择主题以缩小FAQ范围',all:'全部',results:'搜索结果',found:n=>`找到 ${n} 项`,none:'未找到匹配的FAQ。',noneHelp:'请更换关键词或按分类查找。',reset:'清除选择'},
 'zh-TW':{search:'搜尋問題、回答與相關詞',help:'搜尋會包含相關詞與常見表達差異，也可以依分類查找。',popular:'常見問題',popularNote:'最常被確認的內容',browse:'依分類查找',browseNote:'選擇主題以縮小FAQ範圍',all:'全部',results:'搜尋結果',found:n=>`找到 ${n} 項`,none:'找不到符合的FAQ。',noneHelp:'請更換關鍵字或依分類查找。',reset:'清除選擇'},
 ko:{search:'질문·답변·관련어 검색',help:'관련 표현과 표기 차이도 함께 검색합니다. 카테고리로도 찾을 수 있습니다.',popular:'자주 묻는 질문',popularNote:'확인이 많은 항목',browse:'카테고리로 찾기',browseNote:'분야를 선택해 FAQ를 좁혀 보세요',all:'전체',results:'검색 결과',found:n=>`${n}개를 찾았습니다`,none:'일치하는 FAQ를 찾지 못했습니다.',noneHelp:'다른 표현으로 검색하거나 카테고리를 이용해 주세요.',reset:'선택 해제'},
 id:{search:'Cari pertanyaan, jawaban, dan istilah terkait',help:'Pencarian mencakup istilah terkait dan variasi kata. Anda juga dapat menelusuri berdasarkan kategori.',popular:'Pertanyaan populer',popularNote:'Topik yang sering diperiksa',browse:'Telusuri berdasarkan kategori',browseNote:'Pilih topik untuk mempersempit FAQ',all:'Semua',results:'Hasil pencarian',found:n=>`${n} hasil ditemukan`,none:'FAQ yang sesuai tidak ditemukan.',noneHelp:'Coba kata lain atau telusuri berdasarkan kategori.',reset:'Hapus pilihan'},
 ms:{search:'Cari soalan, jawapan dan istilah berkaitan',help:'Carian merangkumi istilah berkaitan dan variasi perkataan. Anda juga boleh menyemak mengikut kategori.',popular:'Soalan popular',popularNote:'Topik yang kerap disemak',browse:'Semak mengikut kategori',browseNote:'Pilih topik untuk mengecilkan senarai FAQ',all:'Semua',results:'Hasil carian',found:n=>`${n} hasil ditemui`,none:'Tiada FAQ yang sepadan ditemui.',noneHelp:'Cuba perkataan lain atau semak mengikut kategori.',reset:'Kosongkan pilihan'},
 vi:{search:'Tìm câu hỏi, câu trả lời và từ liên quan',help:'Tìm kiếm bao gồm từ liên quan và các cách diễn đạt khác nhau. Bạn cũng có thể duyệt theo danh mục.',popular:'Câu hỏi phổ biến',popularNote:'Các chủ đề thường được xem',browse:'Tìm theo danh mục',browseNote:'Chọn chủ đề để thu hẹp FAQ',all:'Tất cả',results:'Kết quả tìm kiếm',found:n=>`Tìm thấy ${n} kết quả`,none:'Không tìm thấy FAQ phù hợp.',noneHelp:'Hãy thử cách diễn đạt khác hoặc duyệt theo danh mục.',reset:'Xóa lựa chọn'},
 th:{search:'ค้นหาคำถาม คำตอบ และคำที่เกี่ยวข้อง',help:'การค้นหารวมคำที่เกี่ยวข้องและรูปแบบการเขียนที่ต่างกัน และสามารถเลือกตามหมวดหมู่ได้',popular:'คำถามที่พบบ่อย',popularNote:'หัวข้อที่ถูกตรวจสอบบ่อย',browse:'ค้นหาตามหมวดหมู่',browseNote:'เลือกหัวข้อเพื่อจำกัดรายการ FAQ',all:'ทั้งหมด',results:'ผลการค้นหา',found:n=>`พบ ${n} รายการ`,none:'ไม่พบ FAQ ที่ตรงกัน',noneHelp:'ลองใช้คำอื่นหรือค้นหาตามหมวดหมู่',reset:'ล้างตัวเลือก'},
 hi:{search:'प्रश्न, उत्तर और संबंधित शब्द खोजें',help:'खोज संबंधित शब्दों और अलग-अलग अभिव्यक्तियों को भी देखती है। आप श्रेणी से भी खोज सकते हैं।',popular:'लोकप्रिय प्रश्न',popularNote:'अक्सर देखे जाने वाले विषय',browse:'श्रेणी से खोजें',browseNote:'FAQ को सीमित करने के लिए विषय चुनें',all:'सभी',results:'खोज परिणाम',found:n=>`${n} परिणाम मिले`,none:'मेल खाने वाला FAQ नहीं मिला।',noneHelp:'दूसरे शब्द आज़माएँ या श्रेणी से खोजें।',reset:'चयन हटाएँ'},
 ar:{search:'ابحث في الأسئلة والإجابات والمصطلحات المرتبطة',help:'يشمل البحث الكلمات المرتبطة واختلافات الصياغة، ويمكنك أيضاً التصفح حسب الفئة.',popular:'الأسئلة الشائعة',popularNote:'الموضوعات الأكثر مراجعة',browse:'التصفح حسب الفئة',browseNote:'اختر موضوعاً لتضييق قائمة الأسئلة',all:'الكل',results:'نتائج البحث',found:n=>`تم العثور على ${n} نتيجة`,none:'لم يتم العثور على سؤال مطابق.',noneHelp:'جرّب صياغة أخرى أو تصفح حسب الفئة.',reset:'إلغاء الاختيار'}
};
const JA_ALIAS_GROUPS=[
 ['見積','見積もり','みつもり','ミツモリ'],['料金','りょうきん','リョウキン','費用','ひよう','ヒヨウ'],['支払い','支払','しはらい','シハライ','決済','けっさい'],['注文','ちゅうもん','チュウモン'],['在庫','ざいこ','ザイコ'],['請求書','せいきゅうしょ','セイキュウショ','インボイス'],['領収書','りょうしゅうしょ','リョウシュウショ','レシート'],['納品','のうひん','ノウヒン'],['月額','げつがく','ゲツガク','サブスク','さぶすく'],['買い切り','かいきり','カイキリ'],['価格','かかく','カカク','値段','ねだん'],['キャンセル','きゃんせる','取消','取り消し','とりけし'],['ソースコード','そーすこーど','コード'],['海外','かいがい','カイガイ'],['言語','げんご','ゲンゴ'],['デモ','でも','体験版','たいけんばん'],['保守','ほしゅ','メンテナンス'],['更新','こうしん','アップデート'],['倉庫','そうこ','ソウコ'],['棚卸','棚卸し','たなおろし']
];
let data={faq:[],categories:{},subcategories:{}};
let selectedCategory='';
let selectedSubcategory='';
function ui(){return UI[lang()]||UI.en}
function pick(obj,l=lang()){if(obj==null)return'';if(typeof obj==='string')return obj;if(Array.isArray(obj))return obj.join(' ');return obj[l]??obj.en??obj.ja??Object.values(obj)[0]??''}
function list(obj,l=lang()){const v=obj?.[l]??obj?.en??obj?.ja??[];return Array.isArray(v)?v:String(v||'').split(/[,、;|]/).map(x=>x.trim()).filter(Boolean)}
function hira(s){return String(s).replace(/[ァ-ヶ]/g,ch=>String.fromCharCode(ch.charCodeAt(0)-0x60))}
function baseText(v){return hira(String(v??'').normalize('NFKC').toLocaleLowerCase()).replace(/[\s\p{P}\p{S}]+/gu,'')}
function latinFold(v){return baseText(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function variants(v){const a=baseText(v),b=latinFold(v);return a===b?[a]:[a,b]}
function queryVariants(v){const out=new Set(variants(v));if(lang()==='ja'){const n=baseText(v);for(const group of JA_ALIAS_GROUPS){const normalized=group.map(baseText);if(normalized.some(x=>x===n||x.includes(n)||n.includes(x)))for(const term of group)variants(term).forEach(x=>out.add(x))}}return[...out].filter(Boolean)}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function categoryLabel(key){return pick(data.categories?.[key]?.label)||key}
function subcategoryLabel(key){return pick(data.subcategories?.[key]?.label)||key}
function localized(item,field){return pick(item?.[field])}
function terms(item,field){return list(item?.[field])}
function searchableParts(item){return{question:localized(item,'question'),answer:localized(item,'answer'),keywords:terms(item,'keywords').join(' '),synonyms:terms(item,'synonyms').join(' '),path:`${categoryLabel(item.category)} ${subcategoryLabel(item.subcategory)}`}}
function queryTokens(q){const raw=String(q||'').normalize('NFKC').trim().toLocaleLowerCase();const parts=raw.split(/[\s,、;|/]+/).filter(Boolean);return parts.length?parts:[raw]}
function score(item,q){if(!q.trim())return 0;const parts=searchableParts(item);const fields=[['question',110],['keywords',92],['synonyms',86],['answer',58],['path',42]];let total=0;for(const token of queryTokens(q)){let best=0;const tv=queryVariants(token);for(const [name,weight] of fields){const fv=variants(parts[name]);if(tv.some(t=>t&&fv.some(f=>f.includes(t))))best=Math.max(best,weight)}if(!best)return-1;total+=best}const qv=queryVariants(q),questionV=variants(parts.question);if(qv.some(t=>t&&questionV.some(f=>f===t)))total+=55;else if(qv.some(t=>t&&questionV.some(f=>f.startsWith(t))))total+=20;return total}
function faqCard(item){return`<article class="faq-item" data-faq-id="${escapeHtml(item.id)}"><button class="faq-q" type="button" aria-expanded="false"><span>${escapeHtml(localized(item,'question'))}</span><span class="faq-plus">＋</span></button><div class="faq-path"><span>${escapeHtml(categoryLabel(item.category))}</span><span>${escapeHtml(subcategoryLabel(item.subcategory))}</span></div><div class="faq-a">${escapeHtml(localized(item,'answer')).replace(/\n/g,'<br>')}</div></article>`}
function categoryEntries(){return Object.entries(data.categories||{}).sort((a,b)=>(a[1].order||99)-(b[1].order||99))}
function ensureUi(){const shell=$('.faq-shell');if(!shell||$('#faqDiscovery'))return;const oldSearch=$('#faqSearch'),oldList=$('#cmsFaqList'),oldEmpty=$('#faqEmpty'),discovery=document.createElement('div');discovery.id='faqDiscovery';discovery.className='faq-discovery';discovery.innerHTML=`<div class="faq-search-wrap"><label class="faq-search-label" for="faqSearch"></label><button id="faqSearchClear" class="faq-search-clear" type="button" aria-label="Clear">×</button><div id="faqSearchHelp" class="faq-search-help"></div></div><div id="faqResultMeta" class="faq-result-meta"></div><section id="faqPopularSection" class="faq-section-block"><div class="faq-block-head"><h3 id="faqPopularTitle"></h3><span id="faqPopularNote"></span></div><div id="faqPopularList" class="faq-list"></div></section><section id="faqBrowseSection" class="faq-section-block"><div class="faq-block-head"><div><h3 id="faqBrowseTitle"></h3><span id="faqBrowseNote"></span></div><button id="faqBrowseReset" class="faq-browse-reset" type="button"></button></div><div id="faqCategoryGrid" class="faq-category-grid"></div><div id="faqSubcategories" class="faq-subcategories"></div><div id="faqBrowseList" class="faq-list"></div></section>`;oldSearch?.insertAdjacentElement('beforebegin',discovery);const searchWrap=$('.faq-search-wrap',discovery);if(oldSearch)searchWrap.insertBefore(oldSearch,$('#faqSearchClear',discovery));oldList?.remove();oldEmpty?.remove();$('#faqSearch')?.addEventListener('input',()=>{selectedCategory='';selectedSubcategory='';render()});$('#faqSearchClear')?.addEventListener('click',()=>{const s=$('#faqSearch');if(s){s.value='';s.focus()}render()});$('#faqBrowseReset')?.addEventListener('click',()=>{selectedCategory='';selectedSubcategory='';render()});$('#faqCategoryGrid')?.addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;selectedCategory=selectedCategory===b.dataset.category?'':b.dataset.category;selectedSubcategory='';const s=$('#faqSearch');if(s)s.value='';render()});$('#faqSubcategories')?.addEventListener('click',e=>{const b=e.target.closest('[data-subcategory]');if(!b)return;selectedSubcategory=selectedSubcategory===b.dataset.subcategory?'':b.dataset.subcategory;render()});discovery.addEventListener('click',e=>{const btn=e.target.closest('.faq-q');if(!btn)return;const item=btn.closest('.faq-item'),open=item?.classList.toggle('open');btn.setAttribute('aria-expanded',open?'true':'false')})}
function renderLabels(){const t=ui(),s=$('#faqSearch');if(s)s.placeholder=t.search;const l=$('.faq-search-label');if(l)l.textContent=t.search;const h=$('#faqSearchHelp');if(h)h.textContent=t.help;const pt=$('#faqPopularTitle');if(pt)pt.textContent=t.popular;const pn=$('#faqPopularNote');if(pn)pn.textContent=t.popularNote;const bt=$('#faqBrowseTitle');if(bt)bt.textContent=t.browse;const bn=$('#faqBrowseNote');if(bn)bn.textContent=t.browseNote;const br=$('#faqBrowseReset');if(br)br.textContent=t.reset}
function renderCategories(){const box=$('#faqCategoryGrid');if(!box)return;box.innerHTML=categoryEntries().map(([key,c])=>{const count=data.faq.filter(x=>x.category===key).length;return`<button type="button" class="faq-category-button${selectedCategory===key?' is-active':''}" data-category="${escapeHtml(key)}"><span>${escapeHtml(pick(c.label))}</span><small>${count} FAQ</small></button>`}).join('');const sub=$('#faqSubcategories');if(!sub)return;if(!selectedCategory){sub.innerHTML='';return}const entries=Object.entries(data.subcategories||{}).filter(([,v])=>v.category===selectedCategory);sub.innerHTML=entries.map(([key,v])=>`<button type="button" class="faq-subcategory-button${selectedSubcategory===key?' is-active':''}" data-subcategory="${escapeHtml(key)}">${escapeHtml(pick(v.label))}</button>`).join('')}
function render(){ensureUi();renderLabels();renderCategories();const q=($('#faqSearch')?.value||'').trim(),popular=$('#faqPopularSection'),browse=$('#faqBrowseSection'),meta=$('#faqResultMeta'),clear=$('#faqSearchClear');clear?.classList.toggle('is-visible',!!q);let items=[];if(q){items=data.faq.map(item=>({item,score:score(item,q)})).filter(x=>x.score>=0).sort((a,b)=>b.score-a.score).map(x=>x.item);if(popular)popular.style.display='none';if(browse)browse.style.display='grid';const cg=$('#faqCategoryGrid');if(cg)cg.style.display='none';const sc=$('#faqSubcategories');if(sc)sc.style.display='none';const reset=$('#faqBrowseReset');if(reset)reset.style.display='none';if(meta){meta.textContent=`${ui().results} — ${ui().found(items.length)}`;meta.classList.add('is-visible')}}else{if(meta)meta.classList.remove('is-visible');if(popular)popular.style.display='grid';if(browse)browse.style.display='grid';const cg=$('#faqCategoryGrid');if(cg)cg.style.display='grid';const sc=$('#faqSubcategories');if(sc)sc.style.display='flex';const reset=$('#faqBrowseReset');if(reset)reset.style.display=selectedCategory?'':'none';const top=data.faq.filter(x=>x.highFrequency);const pl=$('#faqPopularList');if(pl)pl.innerHTML=top.map(faqCard).join('');if(selectedCategory)items=data.faq.filter(x=>x.category===selectedCategory&&(!selectedSubcategory||x.subcategory===selectedSubcategory));else items=[]}const listBox=$('#faqBrowseList');if(listBox){if(items.length)listBox.innerHTML=items.map(faqCard).join('');else if(q||selectedCategory)listBox.innerHTML=`<div class="faq-empty"><strong>${escapeHtml(ui().none)}</strong>${escapeHtml(ui().noneHelp)}</div>`;else listBox.innerHTML=''}}
async function load(){try{const r=await fetch(`${FAQ_URL}?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(r.status);data=await r.json();data.faq=Array.isArray(data.faq)?data.faq:[];render()}catch(e){console.warn('FAQ load failed',e);ensureUi();const box=$('#faqBrowseList');if(box)box.innerHTML='<div class="faq-empty">FAQ data could not be loaded.</div>'}}
function scheduleReloads(){[0,2500,7000,15000].forEach(ms=>setTimeout(load,ms))}
function init(){ensureUi();load();$('#lang')?.addEventListener('change',()=>setTimeout(render,0));new MutationObserver(()=>render()).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});if('BroadcastChannel'in window){const ch=new BroadcastChannel('fde-cms-updates');ch.addEventListener('message',e=>{if(e.data?.type==='faq-updated')scheduleReloads()})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();document.addEventListener('visibilitychange',()=>{if(!document.hidden)load()});window.addEventListener('pageshow',()=>load());
})();
