(()=>{
const add=(lang,values)=>{if(!window.FDE_I18N||!window.FDE_I18N[lang])return;Object.assign(window.FDE_I18N[lang],values)};
add('ja',{
 productsEyebrow:'業務向けデスクトップソフト',strengthJapan:'',madeJapan:'',
 productsHero:'業務ソフトを、必要なところから',whyHero:'技術を導入するだけでなく、現場で使えるところまで届ける',
 productsLead:'在庫管理から始め、必要に応じて承認・帳票・分析へ広げられます。デスクトップ型の業務ソフトを、買い切りまたは保守付きの月額プランで提供します。',
 plansTitle:'2つの製品、2つの契約方法',plansIntro:'各カードで、買い切りと月額プランを切り替えて確認できます。初期表示は買い切りです。',coverageTitle:'対応範囲を比較',howTitle:'導入は3ステップ',
 demoTitle:'IMS Starterの無料デモ',demoDesc:'現在、操作できる無料デモはIMS Starterのみです。デモは別タブで開き、閉じると元のProductsページに戻ります。',
 fdeRoleTitle:'FDEとは何か',fdeRoleIntro:'FDE（Forward Deployed Engineering）は、顧客の業務や制約を理解し、必要な技術を設計・実装して、実際の業務に定着するところまでつなぐ役割です。',
 whyLead:'技術を導入するだけでは、業務は変わりません。FDEは、現場の業務を理解し、技術を実際の仕事の流れに組み込むところまでを担います。',
 backgroundTitle:'デジタル化の課題は、ツール不足だけではない',
 whyClosing:'重要なのは、技術が業務の中で機能すること',whyClosingBody:'FDEは、現場と開発の間に立ち、課題整理から実装、導入後の運用までをつなぎます。',
 aboutHero:'現場で繰り返す課題を、導入しやすい製品に変える',aboutLead:'Kale’s FDEは、小規模な企業で繰り返し発生する業務課題を整理し、標準化したデスクトップソフトウェアとして提供することを目指します。',
 goalDiagramTitle:'誰に、何を、どう届けるのか',goalDiagramBody:'顧客ごとにゼロから受託開発するのではなく、現場に共通する課題を抽出し、複数の企業で使える形に整えて製品として提供します。',
 approachTitle:'必要なものを、必要な大きさで',approachBody:'最初から大規模なシステムへ置き換えるのではなく、業務単位で導入し、必要に応じて広げられる構成を目指します。',
 principlesTitle:'Kale’s FDEが大切にする3つの原則',principlesIntro:'特定製品の機能ではなく、製品を設計・提供するときの基本方針です。',
 contactTitle:'製品について相談する',contactIntro:'よくある質問をご確認いただいたうえで、必要な場合はフォームからお問い合わせください。',faqTitle:'よくある質問',formTitle:'お問い合わせ内容を入力してください',formIntro:'すべて必須項目です。使用するメールサービスを選択して送信してください。',
 fieldMailer:'使用しているメールサービス',mailerOther:'Gmail以外',submitInquiry:'送信する',formNotice:'Gmailを選択した場合はGmailの作成画面へ移動します。Gmail以外は内容確認画面へ進みます。',
 confirmKicker:'内容確認',confirmTitle:'この内容で送信しますか？',confirmBack:'修正する',confirmSend:'送信する',directSendNotice:'Gmail以外の直接送信は、送信用バックエンド接続後に有効になります。',completeTitle:'送信が完了しました',completeBody:'お問い合わせありがとうございます。内容を確認後、返信します。'
});
add('en',{
 productsEyebrow:'Business software from an engineer based in Japan',strengthJapan:'Provided by an engineer based in Japan',madeJapan:'Provided by an engineer based in Japan',
 productsHero:'Business software, starting where you need it',
 productsLead:'Start with inventory management and expand to approvals, documents and analytics when needed. Desktop business software is available as a one-time purchase or a monthly plan with maintenance.',
 plansTitle:'Two products, two ways to buy',coverageTitle:'Compare product coverage',howTitle:'Three steps to get started',
 fdeRoleTitle:'What is FDE?',fdeRoleIntro:'Forward Deployed Engineering starts with understanding a customer’s workflows and constraints, then connects design, implementation and adoption so the technology works in day-to-day operations.',
 backgroundTitle:'The challenge is not simply access to more tools',whyClosing:'What matters is whether technology works inside the business',
 aboutHero:'Turn recurring workflow problems into products that are easier to adopt',goalDiagramTitle:'Who receives what, and how',approachTitle:'The right tool, at the right size',principlesTitle:'Three principles behind Kale’s FDE',
 contactTitle:'Talk to us about a product',contactIntro:'Check the FAQ first. If you still need help, send an inquiry through the form below.',faqTitle:'Frequently asked questions',formTitle:'Enter your inquiry details',formIntro:'All fields are required. Choose your email service, then continue.',fieldMailer:'Email service',mailerOther:'Other',submitInquiry:'Send',formNotice:'Gmail opens the Gmail compose screen in this tab. Other options continue to an on-page confirmation step.',confirmKicker:'Confirm',confirmTitle:'Send this inquiry?',confirmBack:'Edit',confirmSend:'Send',directSendNotice:'Direct sending for non-Gmail inquiries becomes available once a mail backend is connected.',completeTitle:'Inquiry sent',completeBody:'Thank you. We will review your message and reply.'
});
add('zh-CN',{productsEyebrow:'由常驻日本的工程师提供的业务软件',strengthJapan:'由常驻日本的工程师提供',madeJapan:'由常驻日本的工程师提供',productsHero:'从真正需要的业务环节开始',contactIntro:'请先查看常见问题。如仍需咨询，可使用下方表单。',faqTitle:'常见问题',formTitle:'请填写咨询内容',fieldMailer:'使用的邮件服务',mailerOther:'其他',submitInquiry:'发送',confirmTitle:'确认发送此咨询吗？',confirmBack:'返回修改',confirmSend:'发送',directSendNotice:'非Gmail的直接发送将在邮件后端连接后启用。',completeTitle:'发送完成'});
add('zh-TW',{productsEyebrow:'由常駐日本的工程師提供的業務軟體',strengthJapan:'由常駐日本的工程師提供',madeJapan:'由常駐日本的工程師提供',productsHero:'從真正需要的業務環節開始',contactIntro:'請先查看常見問題。如仍需詢問，可使用下方表單。',faqTitle:'常見問題',formTitle:'請填寫詢問內容',fieldMailer:'使用的郵件服務',mailerOther:'其他',submitInquiry:'送出',confirmTitle:'確認送出此詢問嗎？',confirmBack:'返回修改',confirmSend:'送出',directSendNotice:'非Gmail的直接送出將在郵件後端連接後啟用。',completeTitle:'已送出'});
add('ko',{productsEyebrow:'일본을 거점으로 활동하는 엔지니어가 제공하는 업무 소프트웨어',strengthJapan:'일본 거점 엔지니어 제공',madeJapan:'일본 거점 엔지니어 제공',productsHero:'필요한 업무부터 시작하는 소프트웨어',contactIntro:'먼저 FAQ를 확인해 주세요. 추가 문의가 필요하면 아래 양식을 이용해 주세요.',faqTitle:'자주 묻는 질문',formTitle:'문의 내용을 입력해 주세요',fieldMailer:'이메일 서비스',mailerOther:'기타',submitInquiry:'보내기',confirmTitle:'이 내용으로 문의를 보내시겠습니까?',confirmBack:'수정하기',confirmSend:'보내기',directSendNotice:'Gmail 외 직접 전송은 메일 백엔드 연결 후 사용할 수 있습니다.',completeTitle:'전송이 완료되었습니다'});
add('id',{productsEyebrow:'Perangkat lunak bisnis dari engineer yang berbasis di Jepang',strengthJapan:'Disediakan oleh engineer berbasis di Jepang',madeJapan:'Disediakan oleh engineer berbasis di Jepang',productsHero:'Mulai dari proses bisnis yang paling Anda butuhkan',contactIntro:'Periksa FAQ terlebih dahulu. Jika masih memerlukan bantuan, kirim pertanyaan melalui formulir di bawah.',faqTitle:'Pertanyaan umum',formTitle:'Isi detail pertanyaan Anda',fieldMailer:'Layanan email',mailerOther:'Lainnya',submitInquiry:'Kirim',confirmTitle:'Kirim pertanyaan ini?',confirmBack:'Ubah',confirmSend:'Kirim',directSendNotice:'Pengiriman langsung selain Gmail akan aktif setelah backend email terhubung.',completeTitle:'Pesan berhasil dikirim'});
add('ms',{productsEyebrow:'Perisian perniagaan daripada jurutera yang berpangkalan di Jepun',strengthJapan:'Disediakan oleh jurutera berpangkalan di Jepun',madeJapan:'Disediakan oleh jurutera berpangkalan di Jepun',productsHero:'Mulakan dengan proses perniagaan yang paling diperlukan',contactIntro:'Semak FAQ terlebih dahulu. Jika masih memerlukan bantuan, hantarkan pertanyaan melalui borang di bawah.',faqTitle:'Soalan lazim',formTitle:'Masukkan butiran pertanyaan anda',fieldMailer:'Perkhidmatan e-mel',mailerOther:'Lain-lain',submitInquiry:'Hantar',confirmTitle:'Hantar pertanyaan ini?',confirmBack:'Kembali sunting',confirmSend:'Hantar',directSendNotice:'Penghantaran terus selain Gmail akan diaktifkan selepas backend e-mel disambungkan.',completeTitle:'Pertanyaan telah dihantar'});
add('vi',{productsEyebrow:'Phần mềm doanh nghiệp do kỹ sư làm việc tại Nhật Bản cung cấp',strengthJapan:'Được cung cấp bởi kỹ sư làm việc tại Nhật Bản',madeJapan:'Được cung cấp bởi kỹ sư làm việc tại Nhật Bản',productsHero:'Bắt đầu từ nghiệp vụ bạn thực sự cần',contactIntro:'Vui lòng xem FAQ trước. Nếu vẫn cần hỗ trợ, hãy gửi yêu cầu qua biểu mẫu bên dưới.',faqTitle:'Câu hỏi thường gặp',formTitle:'Nhập nội dung liên hệ',fieldMailer:'Dịch vụ email',mailerOther:'Khác',submitInquiry:'Gửi',confirmTitle:'Gửi nội dung này?',confirmBack:'Chỉnh sửa',confirmSend:'Gửi',directSendNotice:'Gửi trực tiếp ngoài Gmail sẽ được bật sau khi kết nối backend email.',completeTitle:'Đã gửi thành công'});
add('th',{productsEyebrow:'ซอฟต์แวร์ธุรกิจจากวิศวกรที่ประจำอยู่ในญี่ปุ่น',strengthJapan:'ให้บริการโดยวิศวกรที่ประจำอยู่ในญี่ปุ่น',madeJapan:'ให้บริการโดยวิศวกรที่ประจำอยู่ในญี่ปุ่น',productsHero:'เริ่มจากงานที่ธุรกิจของคุณต้องการจริง',contactIntro:'โปรดตรวจสอบ FAQ ก่อน หากยังต้องการสอบถาม สามารถใช้แบบฟอร์มด้านล่างได้',faqTitle:'คำถามที่พบบ่อย',formTitle:'กรอกรายละเอียดการติดต่อ',fieldMailer:'บริการอีเมล',mailerOther:'อื่น ๆ',submitInquiry:'ส่ง',confirmTitle:'ยืนยันส่งข้อความนี้หรือไม่?',confirmBack:'แก้ไข',confirmSend:'ส่ง',directSendNotice:'การส่งโดยตรงสำหรับบริการอื่นนอก Gmail จะเปิดใช้งานหลังเชื่อมต่อระบบส่งอีเมล',completeTitle:'ส่งเรียบร้อยแล้ว'});
add('hi',{productsEyebrow:'जापान में आधारित इंजीनियर द्वारा प्रदान किया गया बिज़नेस सॉफ़्टवेयर',strengthJapan:'जापान में आधारित इंजीनियर द्वारा प्रदान',madeJapan:'जापान में आधारित इंजीनियर द्वारा प्रदान',productsHero:'जहाँ ज़रूरत हो, वहीं से शुरुआत करें',contactIntro:'पहले FAQ देखें। यदि फिर भी सहायता चाहिए, तो नीचे दिए फ़ॉर्म से संपर्क करें।',faqTitle:'अक्सर पूछे जाने वाले प्रश्न',formTitle:'अपनी पूछताछ का विवरण भरें',fieldMailer:'ईमेल सेवा',mailerOther:'अन्य',submitInquiry:'भेजें',confirmTitle:'क्या यह पूछताछ भेजें?',confirmBack:'संपादित करें',confirmSend:'भेजें',directSendNotice:'Gmail के अलावा सीधे भेजने की सुविधा ईमेल बैकएंड जुड़ने के बाद सक्रिय होगी।',completeTitle:'पूछताछ भेज दी गई'});
add('ar',{productsEyebrow:'برمجيات أعمال يقدمها مهندس يعمل من اليابان',strengthJapan:'يقدّمها مهندس يعمل من اليابان',madeJapan:'يقدّمها مهندس يعمل من اليابان',productsHero:'ابدأ من العملية التي يحتاجها عملك فعلاً',contactIntro:'راجع الأسئلة الشائعة أولاً. إذا احتجت إلى مساعدة إضافية فاستخدم النموذج أدناه.',faqTitle:'الأسئلة الشائعة',formTitle:'أدخل تفاصيل استفسارك',fieldMailer:'خدمة البريد الإلكتروني',mailerOther:'أخرى',submitInquiry:'إرسال',confirmTitle:'هل تريد إرسال هذا الاستفسار؟',confirmBack:'تعديل',confirmSend:'إرسال',directSendNotice:'سيتم تفعيل الإرسال المباشر لغير Gmail بعد ربط خدمة إرسال بريد خلفية.',completeTitle:'تم إرسال الاستفسار'});
})();