(()=>{
const list=a=>`<ul>${a.map(x=>`<li>${x}</li>`).join('')}</ul>`;
function render(){
 const main=document.querySelector('main');if(!main)return;
 document.documentElement.lang='en';document.documentElement.dir='ltr';
 document.title='FDE IMS License | Rights & Restrictions | Baked Kale';
 main.innerHTML=`<section class="license-hero"><div class="shell license-wrap"><span class="license-status">DRAFT PRODUCT POLICY · IN DEVELOPMENT</span><div class="section-kicker" style="margin-top:22px">FDE IMS License</div><h1 class="display">Source code included.<br>Freedom to customize, not a right to redistribute.</h1><p class="license-lede">FDE IMS License is planned at $313 as a one-time, perpetual internal-use license with source code. The purchasing legal entity may inspect, edit, modify, extend and integrate the software for its own internal business use. Copyright and intellectual-property ownership are not transferred.</p></div></section>
 <section class="license-section"><div class="shell license-wrap"><div class="license-note">FDE IMS is currently under development and not yet formally on sale. This page is a product-policy summary, not the final License Agreement / EULA.</div><div class="license-callout">Customization freedom ≠ Redistribution rights</div></div></section>
 <section class="license-section"><div class="shell license-wrap"><div class="section-kicker">Permitted use</div><h2 class="section-title">Planned permitted use</h2><div class="license-grid"><article class="license-card allow"><h3>Internal use and modification</h3>${list(['Perpetual use','Use within the purchasing legal entity','Install on necessary internal devices','Backups','Inspect, edit and modify source code','Add internal business features','Integrate with internal systems','Use modified versions internally'])}</article><article class="license-card allow"><h3>External developers</h3><p>Source code may be disclosed as necessary to external developers for the purchaser’s own internal development, modification or maintenance.</p>${list(['Confidentiality obligations required','No reuse in other projects','No resale or redistribution by contractors','Purchaser must enforce License conditions'])}</article></div></div></section>
 <section class="license-section"><div class="shell license-wrap"><div class="section-kicker">Restrictions</div><h2 class="section-title">Planned restrictions</h2><div class="license-grid"><article class="license-card prohibit"><h3>Sale and rights granting</h3>${list(['No sale or resale of original or modified versions','No unauthorized transfer','No sublicensing','No redistribution of source, installer or product files'])}</article><article class="license-card prohibit"><h3>Publication and third-party services</h3>${list(['No public GitHub repositories','No publication on websites, social media or public file shares','No third-party SaaS / ASP / hosting provision','No software rental or service bureau','No business that lets third parties use the IMS itself'])}</article></div><div class="license-note" style="margin-top:18px">Using FDE IMS internally while selling your own ordinary products or services to customers is allowed.</div></div></section>
 <section class="license-section"><div class="shell license-wrap"><div class="section-kicker">Entity scope</div><h2 class="section-title">1 License = 1 purchasing legal entity</h2><p>Headquarters, branches, offices and employees within the same legal entity are planned to be covered. Parent companies, subsidiaries, affiliates and other separate legal entities generally require separate Licenses.</p></div></section>
 <section class="license-section" id="switching"><div class="shell license-wrap"><div class="section-kicker">Switching & cancellation</div><h2 class="section-title">License / Updates switching and cancellation</h2><div class="license-grid"><article class="license-card allow"><h3>Moving from License to Updates</h3><p>The planned transition price is $31/month for the first 12 months after moving from License to Updates, then the standard planned price is $62/month. The perpetual License itself is not extinguished.</p></article><article class="license-card"><h3>Cancelling Updates after moving from License</h3><p>Updates access and FDE-managed continuous updates end when the subscription term ends. The previously acquired perpetual License remains, so the customer returns to the License model and may continue using it with customer-managed updates and security.</p></article><article class="license-card"><h3>Cancelling an Updates-only subscription</h3><p>Ongoing update service ends when the subscription term ends. Continued software use, data retention and the version available after cancellation are not yet finalized because the product specification is still under development.</p></article></div></div></section>
 <section class="license-section"><div class="shell license-wrap"><div class="section-kicker">Rights & notices</div><h2 class="section-title">Branding and intellectual property</h2><p>Changing the FDE logo, name or UI for internal customization is not planned to be categorically prohibited. Copyright, License, rights and third-party notices in the source must be retained, and customers may not falsely claim that the original FDE IMS was independently developed by them.</p></div></section>
 <section class="license-section"><div class="shell license-wrap"><div class="section-kicker">AI & third party</div><h2 class="section-title">AI, OSS and third-party components</h2><p>AI coding tools may be used for internal modification where submitted code is contractually or technically excluded from third-party model training. Using FDE IMS code for model training, fine-tuning, third-party training, public datasets or training intended to reproduce a similar product is prohibited. OSS and third-party software remain subject to their own license terms.</p></div></section>`;
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render,{once:true});else render();
})();
