(()=>{
const LANGS=['en','ja','zh-CN','zh-TW','ko','id','ms','vi','th','hi','ar'];const CUR={en:'USD',ja:'JPY','zh-CN':'CNY','zh-TW':'TWD',ko:'KRW',id:'IDR',ms:'MYR',vi:'VND',th:'THB',hi:'INR',ar:'AED'};const LOC={en:'en-US',ja:'ja-JP','zh-CN':'zh-CN','zh-TW':'zh-TW',ko:'ko-KR',id:'id-ID',ms:'ms-MY',vi:'vi-VN',th:'th-TH',hi:'hi-IN',ar:'ar-AE'};const R={JPY:1,USD:.00627731,CNY:.0423289,TWD:.201015,KRW:8.82247,IDR:111.918,MYR:.0256305,VND:164.052,THB:.206395,INR:.594424,AED:.0230533};
const T={
 en:['Purchase overview','FDE IMS is not yet formally on sale. This lightweight page shows only the planned purchase summary.','Selected model','Planned price','What happens at formal sale','Buyer/company details, product version, price and applicable License Agreement / EULA will be confirmed before order submission.','Detailed rights and restrictions','See the current Rights / License page for detailed product-policy information.','View Rights / License','Back to Products','Not yet on sale','one-time','monthly'],
 ja:['購入概要','FDE IMSはまだ正式販売前です。読み込みを軽くするため、このページでは購入予定内容の概要だけを表示します。','選択プラン','予定価格','正式販売時の流れ','注文確定前に購入者・購入法人、製品バージョン、価格、適用されるLicense Agreement / EULAを確認します。','権利・利用条件の詳細','詳細な製品ポリシーはRights / Licenseページを参照してください。','Rights / Licenseを見る','Productsへ戻る','正式販売前','買い切り','月額'],
 'zh-CN':['购买概要','FDE IMS尚未正式销售。为减少加载时间，本页仅显示计划购买概要。','所选方案','计划价格','正式销售时的流程','提交订单前将确认购买者/购买法人、产品版本、价格以及适用的License Agreement / EULA。','权利与限制详情','详细产品政策请参阅Rights / License页面。','查看Rights / License','返回Products','尚未正式销售','一次性','月度'],
 'zh-TW':['購買概要','FDE IMS尚未正式銷售。為縮短載入時間，本頁只顯示預定購買概要。','選擇方案','預定價格','正式銷售時的流程','送出訂單前會確認購買者/購買法人、產品版本、價格與適用的License Agreement / EULA。','權利與限制詳情','詳細產品政策請參閱Rights / License頁面。','查看Rights / License','返回Products','尚未正式銷售','一次性','月費'],
 ko:['구매 개요','FDE IMS는 아직 정식 판매 전입니다. 로딩을 줄이기 위해 이 페이지에는 예정 구매 개요만 표시합니다.','선택 플랜','예정 가격','정식 판매 시 절차','주문 제출 전 구매자/구매 법인, 제품 버전, 가격 및 적용 License Agreement / EULA를 확인합니다.','권리·제한 상세','상세 제품 정책은 Rights / License 페이지를 확인하세요.','Rights / License 보기','Products로 돌아가기','정식 판매 전','일회성','월간'],
 id:['Ringkasan pembelian','FDE IMS belum dijual resmi. Untuk mempercepat pemuatan, halaman ini hanya menampilkan ringkasan pembelian yang direncanakan.','Paket dipilih','Harga rencana','Proses saat penjualan resmi','Sebelum pesanan dikirim, pembeli/badan hukum, versi produk, harga, dan License Agreement / EULA yang berlaku akan dikonfirmasi.','Detail hak dan batasan','Lihat halaman Rights / License untuk kebijakan produk yang lebih rinci.','Lihat Rights / License','Kembali ke Products','Belum dijual resmi','sekali bayar','bulanan'],
 ms:['Ringkasan pembelian','FDE IMS belum dijual secara rasmi. Untuk memendekkan masa pemuatan, halaman ini hanya memaparkan ringkasan pembelian yang dirancang.','Pelan dipilih','Harga dirancang','Proses semasa jualan rasmi','Sebelum pesanan dihantar, pembeli/entiti pembeli, versi produk, harga dan License Agreement / EULA yang terpakai akan disahkan.','Butiran hak dan sekatan','Lihat halaman Rights / License untuk dasar produk terperinci.','Lihat Rights / License','Kembali ke Products','Belum dijual rasmi','sekali bayar','bulanan'],
 vi:['Tổng quan mua hàng','FDE IMS chưa mở bán chính thức. Để tải nhanh hơn, trang này chỉ hiển thị tóm tắt kế hoạch mua hàng.','Gói đã chọn','Giá dự kiến','Quy trình khi mở bán','Trước khi gửi đơn, người mua/pháp nhân mua, phiên bản sản phẩm, giá và License Agreement / EULA áp dụng sẽ được xác nhận.','Chi tiết quyền và hạn chế','Xem trang Rights / License để biết chính sách sản phẩm chi tiết.','Xem Rights / License','Quay lại Products','Chưa mở bán','mua một lần','hàng tháng'],
 th:['ภาพรวมการซื้อ','FDE IMS ยังไม่เปิดขายอย่างเป็นทางการ เพื่อลดเวลาโหลด หน้านี้จะแสดงเพียงสรุปแผนการซื้อ','แผนที่เลือก','ราคาที่วางแผน','ขั้นตอนเมื่อเปิดขาย','ก่อนส่งคำสั่งซื้อจะยืนยันผู้ซื้อ/นิติบุคคล เวอร์ชันผลิตภัณฑ์ ราคา และ License Agreement / EULA ที่ใช้','รายละเอียดสิทธิและข้อจำกัด','ดูนโยบายผลิตภัณฑ์โดยละเอียดที่หน้า Rights / License','ดู Rights / License','กลับไป Products','ยังไม่เปิดขาย','ซื้อครั้งเดียว','รายเดือน'],
 hi:['खरीद अवलोकन','FDE IMS अभी औपचारिक बिक्री पर नहीं है। तेज़ लोडिंग के लिए यह पेज केवल नियोजित खरीद सारांश दिखाता है।','चुनी गई योजना','नियोजित मूल्य','औपचारिक बिक्री पर प्रक्रिया','ऑर्डर भेजने से पहले खरीदार/कानूनी इकाई, उत्पाद संस्करण, मूल्य और लागू License Agreement / EULA की पुष्टि होगी।','अधिकार और प्रतिबंध विवरण','विस्तृत उत्पाद नीति के लिए Rights / License पेज देखें।','Rights / License देखें','Products पर वापस जाएँ','अभी बिक्री नहीं','एकमुश्त','मासिक'],
 ar:['ملخص الشراء','لم يبدأ البيع الرسمي لـ FDE IMS بعد. لتقليل وقت التحميل تعرض هذه الصفحة ملخص الشراء المخطط فقط.','الخطة المختارة','السعر المخطط','الإجراء عند بدء البيع','قبل إرسال الطلب سيتم تأكيد المشتري/الكيان المشتري وإصدار المنتج والسعر وLicense Agreement / EULA المطبق.','تفاصيل الحقوق والقيود','راجع صفحة Rights / License للحصول على سياسة المنتج التفصيلية.','عرض Rights / License','العودة إلى Products','لم يبدأ البيع','دفعة واحدة','شهري']};
function lang(){const v=document.querySelector('#lang')?.value||localStorage.getItem('fde-lang')||'en';return LANGS.includes(v)?v:'en'}function f(j,c){return new Intl.NumberFormat(LOC[lang()]||'en-US',{style:'currency',currency:c,maximumFractionDigits:0}).format(Math.round(j*(R[c]||1)))}function p(j){const l=lang(),c=CUR[l]||'USD';return l==='en'?f(j,'USD'):`${f(j,c)} · ${f(j,'USD')}`}
function render(){const l=lang(),t=T[l]||T.en,q=new URLSearchParams(location.search),monthly=q.get('plan')==='monthly',j=monthly?9800:49800;document.documentElement.lang=l;document.documentElement.dir=l==='ar'?'rtl':'ltr';document.getElementById('liteTitle').textContent=t[0];document.getElementById('liteLead').textContent=t[1];document.getElementById('litePlanLabel').textContent=t[2];document.getElementById('litePlan').textContent=monthly?`Updates — ${t[12]}`:`License — ${t[11]}`;document.getElementById('litePriceLabel').textContent=t[3];document.getElementById('litePrice').textContent=p(j);document.getElementById('liteFlowTitle').textContent=t[4];document.getElementById('liteFlow').textContent=t[5];document.getElementById('liteRightsTitle').textContent=t[6];document.getElementById('liteRights').textContent=t[7];document.getElementById('liteRightsBtn').textContent=t[8];document.getElementById('liteBack').textContent=t[9];document.getElementById('liteStatus').textContent=t[10]}
function init(){const s=document.querySelector('#lang');if(!localStorage.getItem('fde-lang'))localStorage.setItem('fde-lang','en');if(s){s.value=lang();s.addEventListener('change',e=>{localStorage.setItem('fde-lang',e.target.value);render()})}render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();})();