(()=>{
const ENDPOINT=String(window.FDE_CONTACT_API||'').trim();
const RATE_URL='content/pricing-rates.json';
const CATALOG={
 'ims-starter':{name:'IMS Starter',available:true,prices:{'one-time':49800,monthly:4980}},
 'business-dx-pack':{name:'Business DX Pack',available:false,prices:{'one-time':99800,monthly:9800}}
};
const CURRENCY_BY_LANG={ja:'JPY',en:'USD','zh-CN':'CNY','zh-TW':'TWD',ko:'KRW',id:'IDR',ms:'MYR',vi:'VND',th:'THB',hi:'INR',ar:'AED'};
const LOCALE_BY_LANG={ja:'ja-JP',en:'en-US','zh-CN':'zh-CN','zh-TW':'zh-TW',ko:'ko-KR',id:'id-ID',ms:'ms-MY',vi:'vi-VN',th:'th-TH',hi:'hi-IN',ar:'ar-AE'};
const TEXT={
 ja:{quote:'見積書兼注文書',quoteDate:'見積日',validUntil:'有効期限',product:'製品名',plan:'契約方法',price:'価格',total:'注文金額',one:'買い切り',monthly:'月額プラン',month:'/ 月',formTitle:'購入者情報',formIntro:'備考欄以外はすべて必須です。見積内容をご確認のうえ、購入者情報を入力してください。',name:'お名前',company:'企業名',country:'国名',email:'メールアドレス',notes:'備考（任意）',review:'注文内容を確認',confirm:'この内容で注文しますか？',back:'修正する',send:'見積書兼注文書を送信',sending:'送信中…',complete:'注文を受け付けました',completeBody:'見積書兼注文書をメールで送信しました。表示された製品価格が注文金額です。支払い確認後、納品書・領収書・製品インストーラーの案内を送付します。',invalidEmail:'有効なメールアドレスを入力してください。',required:'この項目は必須です。',unavailable:'この製品は現在購入受付前です。',failed:'注文の送信に失敗しました。時間をおいて再度お試しください。',note:'税金・決済手数料・その他の諸費用は、製品価格に含まれています。\n\n外貨表示は、月初に更新される参考為替レートを使用します。\n注文送信だけでは製品は納品されません。'},
 en:{quote:'Quotation & Order Form',quoteDate:'Quote date',validUntil:'Valid until',product:'Product',plan:'Plan',price:'Price',total:'Order total',one:'One-time purchase',monthly:'Monthly plan',month:'/ month',formTitle:'Buyer information',formIntro:'All buyer fields except Notes are required. Review the quotation and enter the buyer information to place the order.',name:'Name',company:'Company',country:'Country',email:'Email address',notes:'Notes (optional)',review:'Review order',confirm:'Place this order?',back:'Edit',send:'Send quotation & order',sending:'Sending…',complete:'Order received',completeBody:'The quotation and order confirmation has been sent by email. The displayed product price is the order total. After payment confirmation, the delivery note, receipt and product installer information will be sent.',invalidEmail:'Enter a valid email address.',required:'This field is required.',unavailable:'This product is not yet available for purchase.',failed:'The order could not be sent. Please try again later.',note:'Taxes, payment fees and other charges are included in the product price.\n\nForeign-currency prices use the reference exchange rate updated at the beginning of each month.\nSubmitting the order does not deliver the software immediately.'}
};
const $=(s,c=document)=>c.querySelector(s);
const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
let rates={JPY:1},rateDate='',productKey='',planKey='',currency='JPY',quoteId='';
const lang=()=>document.documentElement.lang||localStorage.getItem('fde-lang')||'ja';
const tx=k=>(TEXT[lang()]||TEXT.en)[k]||TEXT.en[k];
function params(){const p=new URLSearchParams(location.search);return{product:p.get('product')||'ims-starter',plan:p.get('plan')==='monthly'?'monthly':'one-time'}}
function dateISO(d){return d.toISOString().slice(0,10)}
function displayDate(iso){const d=new Date(`${iso}T00:00:00`);return new Intl.DateTimeFormat(LOCALE_BY_LANG[lang()]||'en-US',{year:'numeric',month:'short',day:'numeric'}).format(d)}
function makeQuoteId(){const d=new Date();const stamp=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`;const rand=crypto.getRandomValues(new Uint32Array(1))[0].toString(16).toUpperCase().padStart(8,'0').slice(0,8);return`BK-${stamp}-${rand}`}
function chooseCurrency(){const l=lang(),local=CURRENCY_BY_LANG[l]||'USD';if(l==='ja'||l==='en')return local;const saved=localStorage.getItem(`fde-price-currency-${l}`);return saved===local||saved==='USD'?saved:local}
function formatPrice(jpy){const n=Math.round(jpy*(rates[currency]||1));return new Intl.NumberFormat(LOCALE_BY_LANG[lang()]||'en-US',{style:'currency',currency,minimumFractionDigits:0,maximumFractionDigits:0}).format(n)}
function planLabel(){return planKey==='monthly'?tx('monthly'):tx('one')}
function applyText(){document.querySelectorAll('[data-order-text]').forEach(el=>{const key=el.dataset.orderText;if(TEXT[lang()]?.[key]||TEXT.en[key])el.textContent=tx(key)});const planNote=$('#quotePlanSuffix');if(planNote)planNote.textContent=planKey==='monthly'?tx('month'):''}
function renderQuote(){const item=CATALOG[productKey];if(!item)return;const today=dateISO(new Date());const valid=new Date();valid.setDate(valid.getDate()+14);const validIso=dateISO(valid);$('#quoteId').textContent=quoteId;$('#quoteDate').textContent=displayDate(today);$('#quoteValid').textContent=displayDate(validIso);$('#quoteProduct').textContent=item.name;$('#quoteProductLine').textContent=item.name;$('#quotePlan').textContent=planLabel();const price=formatPrice(item.prices[planKey]);$('#quotePrice').textContent=price;$('#quoteTotal').textContent=price;$('#rateInfo').textContent=rateDate?`${tx('note')}\n\nExchange-rate reference: ${rateDate}.`:tx('note');applyText();if(!item.available){$('#orderFormCard').innerHTML=`<h2>${tx('unavailable')}</h2><p><a class="button" href="index.html#plans">Products</a></p>`}}
async function loadRates(){try{const r=await fetch(`${RATE_URL}?v=${Date.now()}`,{cache:'no-store'});if(r.ok){const j=await r.json();rates={JPY:1,...(j.rates||{})};rateDate=j.asOf||''}}catch(e){console.warn('Rate load failed',e)}renderQuote()}
function values(){return{name:$('#buyerName').value.trim(),company:$('#buyerCompany').value.trim(),country:$('#buyerCountry').value.trim(),email:$('#buyerEmail').value.trim(),notes:$('#buyerNotes').value.trim()}}
function validate(){const f=$('#orderForm');const required=['buyerName','buyerCompany','buyerCountry'];let ok=true;required.forEach(id=>{const el=$('#'+id);const valid=!!el.value.trim();el.setCustomValidity(valid?'':tx('required'));if(!valid)ok=false});const email=$('#buyerEmail');const emailOk=emailPattern.test(email.value.trim());email.setCustomValidity(emailOk?'':tx('invalidEmail'));if(!emailOk)ok=false;if(!ok||!f.checkValidity()){f.reportValidity();return false}return true}
function summary(){const v=values();const item=CATALOG[productKey];const rows=[[tx('product'),item.name],[tx('plan'),planLabel()],[tx('price'),formatPrice(item.prices[planKey])],[tx('name'),v.name],[tx('company'),v.company],[tx('country'),v.country],[tx('email'),v.email],[tx('notes'),v.notes||'—']];const box=$('#orderSummary');box.innerHTML='';rows.forEach(([a,b])=>{const row=document.createElement('div');row.className='order-summary-row';const k=document.createElement('strong');k.textContent=a;const val=document.createElement('span');val.textContent=b;row.append(k,val);box.appendChild(row)})}
function setIntroVisible(show){const card=$('#orderFormCard');card?.querySelector(':scope > h2')?.toggleAttribute('hidden',!show);card?.querySelector(':scope > p')?.toggleAttribute('hidden',!show)}
function showConfirm(){summary();$('#orderForm').hidden=true;$('#orderConfirm').hidden=false;$('#orderComplete').hidden=true;setIntroVisible(false);$('#orderConfirm').setAttribute('tabindex','-1');$('#orderConfirm').focus({preventScroll:true})}
function showMain(){$('#orderConfirm').hidden=true;$('#orderComplete').hidden=true;$('#orderForm').hidden=false;setIntroVisible(true);$('#buyerName').focus({preventScroll:true})}
async function submitOrder(){if(!ENDPOINT){alert(tx('failed'));return}const btn=$('#orderSend');btn.disabled=true;const old=btn.textContent;btn.textContent=tx('sending');const item=CATALOG[productKey],v=values();try{const res=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({type:'order',quoteId,product:item.name,productKey,plan:planKey,currency,name:v.name,company:v.company,country:v.country,email:v.email,notes:v.notes,lang:lang(),website:''})});const data=await res.json().catch(()=>({}));if(!res.ok||data.ok===false)throw new Error(data.error||res.status);$('#orderConfirm').hidden=true;$('#orderForm').hidden=true;$('#orderComplete').hidden=false;setIntroVisible(false);$('#completeOrderId').textContent=data.orderId||quoteId;$('#orderComplete').setAttribute('tabindex','-1');$('#orderComplete').focus({preventScroll:true})}catch(e){console.warn('Order failed',e);alert(tx('failed'))}finally{btn.disabled=false;btn.textContent=old}}
function moveStatesIntoCard(){const card=$('#orderFormCard'),confirm=$('#orderConfirm'),complete=$('#orderComplete');if(card&&confirm&&complete){card.appendChild(confirm);card.appendChild(complete)}}
function clearValidity(e){e.target.setCustomValidity('')}
function init(){({product:productKey,plan:planKey}=params());if(!CATALOG[productKey])productKey='ims-starter';quoteId=makeQuoteId();currency=chooseCurrency();moveStatesIntoCard();loadRates();applyText();$('#orderForm').addEventListener('submit',e=>{e.preventDefault();if(validate())showConfirm()});$('#orderBack').addEventListener('click',showMain);$('#orderSend').addEventListener('click',submitOrder);['buyerName','buyerCompany','buyerCountry','buyerEmail'].forEach(id=>$('#'+id).addEventListener('input',clearValidity));$('#lang')?.addEventListener('change',()=>setTimeout(()=>{currency=chooseCurrency();renderQuote();applyText()},0));new MutationObserver(()=>{currency=chooseCurrency();renderQuote();applyText()}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();