(()=>{
const LANGS=['en','ja','zh-CN','zh-TW','ko','id','ms','vi','th','hi','ar'];
const LOCAL={en:'USD',ja:'JPY','zh-CN':'CNY','zh-TW':'TWD',ko:'KRW',id:'IDR',ms:'MYR',vi:'VND',th:'THB',hi:'INR',ar:'AED'};
const LOCALE={en:'en-US',ja:'ja-JP','zh-CN':'zh-CN','zh-TW':'zh-TW',ko:'ko-KR',id:'id-ID',ms:'ms-MY',vi:'vi-VN',th:'th-TH',hi:'hi-IN',ar:'ar-AE'};
const RATE={JPY:1,USD:.00627731,CNY:.0423289,TWD:.201015,KRW:8.82247,IDR:111.918,MYR:.0256305,VND:164.052,THB:.206395,INR:.594424,AED:.0230533};
const COPY={
 en:{dev:'IN DEVELOPMENT · NOT YET ON SALE',lead:'FDE IMS is under development. License is the recommended one-time purchase model, followed by the monthly Updates plan.',title:'FDE IMS — Product plans',sub:'Prices on this page are shown only in the local currency associated with the selected display language.',planned:'Planned price',license:'FDE IMS License',updates:'FDE IMS Updates',one:'one-time',month:'/ month',ld:'Perpetual internal-use license with source code. Internal customization is allowed within the purchasing legal entity.',ud:'Monthly plan with ongoing FDE-managed functionality, security and compatibility updates. Source code is not planned to be provided.',buy:'Purchase',rights:'Rights & usage terms',recommended:'Recommended',heroLicense:'License',heroUpdates:'Updates',plannedWord:'planned'},
 ja:{dev:'開発中・正式販売前',lead:'FDE IMSは現在開発中です。買い切り型Licenseを推奨し、その下に月額Updatesプランを表示します。',title:'FDE IMS — 商品プラン',sub:'このページの価格は、選択した表示言語に対応する現地通貨のみで表示します。',planned:'予定価格',license:'FDE IMS License',updates:'FDE IMS Updates',one:'買い切り',month:'/ 月',ld:'ソースコード付きの永続的な自社内部利用Licenseです。購入法人の内部利用範囲でカスタマイズできます。',ud:'FDEが機能・セキュリティ・互換性を継続管理する月額プランです。ソースコード提供は予定していません。',buy:'購入する',rights:'権利・利用条件を見る',recommended:'推奨',heroLicense:'License',heroUpdates:'Updates',plannedWord:'予定'},
 'zh-CN':{dev:'开发中 · 尚未正式销售',lead:'FDE IMS仍在开发中。首先显示推荐的一次性License，其下显示月度Updates计划。',title:'FDE IMS — 产品方案',sub:'本页价格仅按所选显示语言对应的当地货币显示。',planned:'计划价格',license:'FDE IMS License',updates:'FDE IMS Updates',one:'一次性',month:'/ 月',ld:'附源代码的永久内部使用License，可在购买法人内部使用范围内定制。',ud:'由FDE持续管理功能、安全和兼容性更新的月度方案。计划不提供源代码。',buy:'购买',rights:'查看权利与使用条件',recommended:'推荐',heroLicense:'License',heroUpdates:'Updates',plannedWord:'计划'},
 'zh-TW':{dev:'開發中 · 尚未正式銷售',lead:'FDE IMS仍在開發中。先顯示推薦的一次性License，其下顯示月費Updates方案。',title:'FDE IMS — 產品方案',sub:'本頁價格僅以所選顯示語言對應的當地貨幣顯示。',planned:'預定價格',license:'FDE IMS License',updates:'FDE IMS Updates',one:'一次性',month:'/ 月',ld:'附原始碼的永久內部使用License，可在購買法人內部使用範圍內客製化。',ud:'由FDE持續管理功能、安全與相容性更新的月費方案。預計不提供原始碼。',buy:'購買',rights:'查看權利與使用條件',recommended:'推薦',heroLicense:'License',heroUpdates:'Updates',plannedWord:'預定'},
 ko:{dev:'개발 중 · 정식 판매 전',lead:'FDE IMS는 개발 중입니다. 권장 일회성 License를 먼저 표시하고 그 아래에 월간 Updates 플랜을 표시합니다.',title:'FDE IMS — 상품 플랜',sub:'이 페이지의 가격은 선택한 표시 언어에 해당하는 현지 통화로만 표시됩니다.',planned:'예정 가격',license:'FDE IMS License',updates:'FDE IMS Updates',one:'일회성',month:'/ 월',ld:'소스 코드가 포함된 영구 내부 사용 License입니다. 구매 법인의 내부 사용 범위에서 커스터마이즈할 수 있습니다.',ud:'FDE가 기능·보안·호환성 업데이트를 지속 관리하는 월간 플랜입니다. 소스 코드는 제공할 예정이 없습니다.',buy:'구매하기',rights:'권리·이용 조건',recommended:'권장',heroLicense:'License',heroUpdates:'Updates',plannedWord:'예정'},
 id:{dev:'DALAM PENGEMBANGAN · BELUM DIJUAL RESMI',lead:'FDE IMS masih dikembangkan. License sekali bayar yang direkomendasikan ditampilkan terlebih dahulu, lalu paket Updates bulanan.',title:'FDE IMS — Paket produk',sub:'Harga di halaman ini hanya ditampilkan dalam mata uang lokal yang sesuai dengan bahasa tampilan.',planned:'Harga rencana',license:'FDE IMS License',updates:'FDE IMS Updates',one:'sekali bayar',month:'/ bulan',ld:'License penggunaan internal permanen dengan kode sumber. Dapat disesuaikan untuk penggunaan internal badan hukum pembeli.',ud:'Paket bulanan dengan pembaruan fungsi, keamanan, dan kompatibilitas yang dikelola FDE. Kode sumber tidak direncanakan untuk diberikan.',buy:'Beli',rights:'Hak & ketentuan',recommended:'Direkomendasikan',heroLicense:'License',heroUpdates:'Updates',plannedWord:'rencana'},
 ms:{dev:'DALAM PEMBANGUNAN · BELUM DIJUAL RASMI',lead:'FDE IMS masih dibangunkan. License sekali bayar yang disyorkan dipaparkan dahulu, diikuti pelan Updates bulanan.',title:'FDE IMS — Pelan produk',sub:'Harga pada halaman ini hanya dipaparkan dalam mata wang tempatan yang sepadan dengan bahasa paparan.',planned:'Harga dirancang',license:'FDE IMS License',updates:'FDE IMS Updates',one:'sekali bayar',month:'/ bulan',ld:'License penggunaan dalaman kekal dengan kod sumber. Boleh disesuaikan untuk kegunaan dalaman entiti pembeli.',ud:'Pelan bulanan dengan kemas kini fungsi, keselamatan dan keserasian yang diurus FDE. Kod sumber tidak dirancang untuk diberikan.',buy:'Beli',rights:'Hak & syarat',recommended:'Disyorkan',heroLicense:'License',heroUpdates:'Updates',plannedWord:'dirancang'},
 vi:{dev:'ĐANG PHÁT TRIỂN · CHƯA MỞ BÁN',lead:'FDE IMS đang được phát triển. License mua một lần được khuyến nghị hiển thị trước, tiếp theo là gói Updates hàng tháng.',title:'FDE IMS — Gói sản phẩm',sub:'Giá trên trang này chỉ hiển thị bằng tiền tệ địa phương tương ứng với ngôn ngữ hiển thị.',planned:'Giá dự kiến',license:'FDE IMS License',updates:'FDE IMS Updates',one:'mua một lần',month:'/ tháng',ld:'License sử dụng nội bộ vĩnh viễn kèm mã nguồn, có thể tùy chỉnh trong phạm vi nội bộ của pháp nhân mua.',ud:'Gói hàng tháng do FDE quản lý cập nhật chức năng, bảo mật và tương thích. Không dự kiến cung cấp mã nguồn.',buy:'Mua',rights:'Quyền & điều kiện',recommended:'Khuyến nghị',heroLicense:'License',heroUpdates:'Updates',plannedWord:'dự kiến'},
 th:{dev:'อยู่ระหว่างพัฒนา · ยังไม่เปิดขาย',lead:'FDE IMS ยังอยู่ระหว่างพัฒนา โดยแสดง License แบบซื้อครั้งเดียวที่แนะนำก่อน แล้วจึงแสดงแผน Updates รายเดือนด้านล่าง',title:'FDE IMS — แผนผลิตภัณฑ์',sub:'ราคาบนหน้านี้แสดงเฉพาะสกุลเงินท้องถิ่นที่สอดคล้องกับภาษาที่เลือก',planned:'ราคาที่วางแผน',license:'FDE IMS License',updates:'FDE IMS Updates',one:'ซื้อครั้งเดียว',month:'/ เดือน',ld:'License สำหรับใช้ภายในแบบถาวรพร้อมซอร์สโค้ด สามารถปรับแต่งภายในนิติบุคคลผู้ซื้อได้',ud:'แผนรายเดือนที่ FDE ดูแลการอัปเดตฟังก์ชัน ความปลอดภัย และความเข้ากันได้ โดยไม่มีแผนให้ซอร์สโค้ด',buy:'ซื้อ',rights:'สิทธิและเงื่อนไข',recommended:'แนะนำ',heroLicense:'License',heroUpdates:'Updates',plannedWord:'วางแผน'},
 hi:{dev:'विकासाधीन · अभी बिक्री नहीं',lead:'FDE IMS विकासाधीन है। अनुशंसित एकमुश्त License पहले दिखाया जाता है, उसके नीचे मासिक Updates योजना।',title:'FDE IMS — उत्पाद योजनाएँ',sub:'इस पृष्ठ पर मूल्य केवल चयनित प्रदर्शन भाषा से संबंधित स्थानीय मुद्रा में दिखाए जाते हैं।',planned:'नियोजित मूल्य',license:'FDE IMS License',updates:'FDE IMS Updates',one:'एकमुश्त',month:'/ माह',ld:'सोर्स कोड सहित स्थायी आंतरिक उपयोग License। खरीदार कानूनी इकाई के आंतरिक उपयोग के लिए कस्टमाइज़ किया जा सकता है।',ud:'मासिक योजना जिसमें FDE कार्यक्षमता, सुरक्षा और संगतता अपडेट संभालता है। सोर्स कोड देने की योजना नहीं है।',buy:'खरीदें',rights:'अधिकार व शर्तें',recommended:'अनुशंसित',heroLicense:'License',heroUpdates:'Updates',plannedWord:'नियोजित'},
 ar:{dev:'قيد التطوير · غير متاح للبيع بعد',lead:'لا يزال FDE IMS قيد التطوير. يظهر License الموصى به للدفع مرة واحدة أولاً، ثم خطة Updates الشهرية تحته.',title:'FDE IMS — خطط المنتج',sub:'تُعرض الأسعار في هذه الصفحة فقط بالعملة المحلية المرتبطة بلغة العرض المحددة.',planned:'السعر المخطط',license:'FDE IMS License',updates:'FDE IMS Updates',one:'دفعة واحدة',month:'/ شهر',ld:'License دائم للاستخدام الداخلي مع الشفرة المصدرية، ويمكن تخصيصه للاستخدام الداخلي للكيان المشتري.',ud:'خطة شهرية تدير فيها FDE تحديثات الوظائف والأمان والتوافق باستمرار. لا يُخطط لتوفير الشفرة المصدرية.',buy:'شراء',rights:'الحقوق والشروط',recommended:'موصى به',heroLicense:'License',heroUpdates:'Updates',plannedWord:'مخطط'}
};
function lang(){const v=localStorage.getItem('fde-lang')||'en';return LANGS.includes(v)?v:'en'}
function fmt(jpy,l){const c=LOCAL[l]||'USD',v=Math.round(jpy*(RATE[c]||1));return new Intl.NumberFormat(LOCALE[l]||'en-US',{style:'currency',currency:c,maximumFractionDigits:0}).format(v)}
function render(){const root=document.querySelector('#plans .shell');if(!root)return;const l=lang(),c=COPY[l]||COPY.en;root.innerHTML=`<div class="clean-plans-head"><strong>${c.dev}</strong><p>${c.lead}</p></div><div class="section-head"><div><div class="section-kicker">FDE IMS</div><h2 class="section-title">${c.title}</h2></div><p class="section-copy">${c.sub}</p></div><div class="clean-plan-stack"><article class="clean-plan-card recommended"><div class="clean-plan-top"><span>License</span><b>${c.recommended}</b></div><h3>${c.license}</h3><div class="clean-plan-label">${c.planned}</div><div class="clean-plan-price">${fmt(49800,l)} <small>${c.one}</small></div><p>${c.ld}</p><div class="clean-plan-actions"><a class="button dark" href="order.html?plan=license">${c.buy}</a><a class="button" href="license.html">${c.rights}</a></div></article><article class="clean-plan-card"><div class="clean-plan-top"><span>Updates</span></div><h3>${c.updates}</h3><div class="clean-plan-label">${c.planned}</div><div class="clean-plan-price">${fmt(9800,l)} <small>${c.month}</small></div><p>${c.ud}</p><div class="clean-plan-actions"><a class="button dark" href="order.html?plan=monthly">${c.buy}</a><a class="button" href="license.html">${c.rights}</a></div></article></div>`;
 const hero=document.querySelector('.products-hero .strength-row');if(hero)hero.innerHTML=`<span>${c.heroLicense} — ${fmt(49800,l)} ${c.plannedWord}</span><span>${c.heroUpdates} — ${fmt(9800,l)} ${c.month} ${c.plannedWord}</span>`;
}
function init(){render();document.querySelector('#lang')?.addEventListener('change',()=>setTimeout(render,0));window.addEventListener('pageshow',render)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();