(()=>{
const ROOT='https://kale1205.github.io/fde-site/';
const SUPPORTED=['ja','en','zh-CN','zh-TW','ko','id','ms','vi','th','hi','ar'];
const SEO={
 ja:{title:'Kale’s FDE | IMS在庫管理ソフト | Baked Kale',description:'Baked Kaleが提供するKale’s FDE。IMS Starter（Inventory Management System）を中心に、在庫管理・承認・帳票・分析に対応するデスクトップ業務ソフトを提供します。',line:'Baked Kale / IMS Starter — Inventory Management System'},
 en:{title:'Kale’s FDE | IMS Inventory Management Software | Baked Kale',description:'Kale’s FDE by Baked Kale provides IMS Starter inventory management software and practical desktop business systems for inventory, approvals, documents and analytics.',line:'Baked Kale / IMS Starter — Inventory Management System'},
 'zh-CN':{title:'Kale’s FDE | IMS 库存管理软件 | Baked Kale',description:'Baked Kale 的 Kale’s FDE 提供 IMS Starter 库存管理软件，以及库存、审批、单据和分析等桌面业务系统。',line:'Baked Kale / IMS Starter — Inventory Management System'},
 'zh-TW':{title:'Kale’s FDE | IMS 庫存管理軟體 | Baked Kale',description:'Baked Kale 的 Kale’s FDE 提供 IMS Starter 庫存管理軟體，以及庫存、審批、單據與分析等桌面業務系統。',line:'Baked Kale / IMS Starter — Inventory Management System'},
 ko:{title:'Kale’s FDE | IMS 재고 관리 소프트웨어 | Baked Kale',description:'Baked Kale의 Kale’s FDE는 IMS Starter 재고 관리 소프트웨어와 재고·승인·문서·분석을 위한 데스크톱 업무 시스템을 제공합니다.',line:'Baked Kale / IMS Starter — Inventory Management System'},
 id:{title:'Kale’s FDE | Software IMS Manajemen Inventaris | Baked Kale',description:'Kale’s FDE dari Baked Kale menyediakan IMS Starter untuk manajemen inventaris serta sistem desktop untuk persetujuan, dokumen, dan analitik.',line:'Baked Kale / IMS Starter — Inventory Management System'},
 ms:{title:'Kale’s FDE | Perisian IMS Pengurusan Inventori | Baked Kale',description:'Kale’s FDE oleh Baked Kale menyediakan IMS Starter untuk pengurusan inventori serta sistem desktop untuk kelulusan, dokumen dan analitik.',line:'Baked Kale / IMS Starter — Inventory Management System'},
 vi:{title:'Kale’s FDE | Phần mềm IMS quản lý tồn kho | Baked Kale',description:'Kale’s FDE của Baked Kale cung cấp IMS Starter để quản lý tồn kho cùng hệ thống desktop cho phê duyệt, chứng từ và phân tích.',line:'Baked Kale / IMS Starter — Inventory Management System'},
 th:{title:'Kale’s FDE | ซอฟต์แวร์ IMS จัดการสินค้าคงคลัง | Baked Kale',description:'Kale’s FDE โดย Baked Kale ให้บริการ IMS Starter สำหรับจัดการสินค้าคงคลัง รวมถึงระบบเดสก์ท็อปสำหรับการอนุมัติ เอกสาร และการวิเคราะห์',line:'Baked Kale / IMS Starter — Inventory Management System'},
 hi:{title:'Kale’s FDE | IMS इन्वेंटरी मैनेजमेंट सॉफ्टवेयर | Baked Kale',description:'Baked Kale का Kale’s FDE, IMS Starter इन्वेंटरी मैनेजमेंट सॉफ्टवेयर और अनुमोदन, दस्तावेज़ व विश्लेषण के लिए डेस्कटॉप बिज़नेस सिस्टम प्रदान करता है।',line:'Baked Kale / IMS Starter — Inventory Management System'},
 ar:{title:'Kale’s FDE | برنامج IMS لإدارة المخزون | Baked Kale',description:'تقدم Kale’s FDE من Baked Kale برنامج IMS Starter لإدارة المخزون وأنظمة أعمال مكتبية للموافقات والمستندات والتحليلات.',line:'Baked Kale / IMS Starter — Inventory Management System'}
};
const qs=s=>document.querySelector(s);
function currentLang(){const v=qs('#lang')?.value||localStorage.getItem('fde-lang')||document.documentElement.lang||'ja';return SUPPORTED.includes(v)?v:'ja'}
function upsertMeta(selector,attrs){let el=qs(selector);if(!el){el=document.createElement('meta');document.head.appendChild(el)}Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));return el}
function upsertCanonical(url){let el=qs('link[rel="canonical"]');if(!el){el=document.createElement('link');el.rel='canonical';document.head.appendChild(el)}el.href=url}
function addJsonLd(id,data){let el=document.getElementById(id);if(!el){el=document.createElement('script');el.id=id;el.type='application/ld+json';document.head.appendChild(el)}el.textContent=JSON.stringify(data)}
function ensureStyle(){if(document.getElementById('fde-seo-style'))return;const s=document.createElement('style');s.id='fde-seo-style';s.textContent='.seo-identity-line{margin:7px 0 12px;font-size:12px;font-weight:800;letter-spacing:.04em;color:var(--green-deep,#095f3b)}';document.head.appendChild(s)}
function homepage(){const l=currentLang(),copy=SEO[l]||SEO.ja;document.title=copy.title;document.body?.setAttribute('data-default-title',copy.title);const md=qs('meta[name="description"]');if(md)md.content=copy.description;else upsertMeta('meta[name="description"]',{name:'description',content:copy.description});upsertMeta('meta[property="og:title"]',{property:'og:title',content:copy.title});upsertMeta('meta[property="og:description"]',{property:'og:description',content:copy.description});upsertMeta('meta[property="og:type"]',{property:'og:type',content:'website'});upsertMeta('meta[property="og:url"]',{property:'og:url',content:ROOT});upsertMeta('meta[name="twitter:card"]',{name:'twitter:card',content:'summary'});upsertMeta('meta[name="twitter:title"]',{name:'twitter:title',content:copy.title});upsertMeta('meta[name="twitter:description"]',{name:'twitter:description',content:copy.description});upsertCanonical(ROOT);ensureStyle();const eyebrow=qs('.products-hero .eyebrow');if(eyebrow){let line=qs('.products-hero .seo-identity-line');if(!line){line=document.createElement('div');line.className='seo-identity-line';eyebrow.insertAdjacentElement('afterend',line)}line.textContent=copy.line}
 addJsonLd('fde-seo-jsonld',{'@context':'https://schema.org','@graph':[{'@type':'Organization','@id':ROOT+'#organization','name':'Baked Kale','alternateName':'Kale’s FDE','url':ROOT,'logo':ROOT+'assets/baked-kale-logo.svg','sameAs':['https://www.instagram.com/kale1999_/']},{'@type':'WebSite','@id':ROOT+'#website','url':ROOT,'name':'Kale’s FDE','alternateName':'Baked Kale','publisher':{'@id':ROOT+'#organization'}},{'@type':'WebPage','@id':ROOT+'#webpage','url':ROOT,'name':copy.title,'description':copy.description,'isPartOf':{'@id':ROOT+'#website'},'about':[{'@type':'Thing','name':'IMS Starter'},{'@type':'Thing','name':'Inventory Management System'},{'@type':'Thing','name':'Inventory management software'}]}]});
}
function apply(){const p=location.pathname;if(p.endsWith('/fde-site/')||p.endsWith('/fde-site/index.html')||p.endsWith('/index.html'))homepage()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply,{once:true});else apply();
qs('#lang')?.addEventListener('change',()=>setTimeout(apply,0));new MutationObserver(()=>apply()).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
})();
