(()=>{
const supported=['ja','en','zh-CN','zh-TW','ko','id','ms','vi','th','hi','ar'];
const qs=(s,c=document)=>c.querySelector(s);const qsa=(s,c=document)=>[...c.querySelectorAll(s)];
let lang=localStorage.getItem('fde-lang')||'ja';if(!supported.includes(lang))lang='ja';
const dict=()=>((window.FDE_I18N&&window.FDE_I18N[lang])||{});const t=(k,f)=>dict()[k]??f;
function applyLang(){const d=dict();document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';qsa('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(d[k]!=null)el.textContent=d[k]});qsa('[data-i18n-html]').forEach(el=>{const k=el.dataset.i18nHtml;if(d[k]!=null)el.innerHTML=d[k]});qsa('[data-i18n-placeholder]').forEach(el=>{const k=el.dataset.i18nPlaceholder;if(d[k]!=null)el.setAttribute('placeholder',d[k])});const sel=qs('#lang');if(sel)sel.value=lang;const md=qs('meta[name="description"]');if(md&&d.metaDescription)md.content=d.metaDescription;}
window.FDE_setLanguage=n=>{if(!supported.includes(n))return;lang=n;localStorage.setItem('fde-lang',n);applyLang()};
function toggleCard(card){card.classList.toggle('flipped')}
function updateDemoKpis(){const vals=qsa('[data-stock-value]').map(c=>parseInt(c.textContent,10)||0);const total=qs('#kpiItems'),low=qs('#kpiLow');if(total)total.textContent=qsa('#inventoryBody tr').length;if(low)low.textContent=vals.filter(v=>v<30).length;qsa('#inventoryBody tr').forEach(r=>{const cell=qs('[data-stock-value]',r),status=qs('[data-stock-status]',r);if(cell&&status)status.textContent=(parseInt(cell.textContent,10)||0)<30?'Low':'Healthy'})}
function inquiryText(form){const g=id=>qs('#'+id,form);const val=id=>g(id)?.value.trim()||'';const product=g('product')?.value||'';const labels={name:g('name')?.previousElementSibling?.textContent||'Name',company:g('company')?.previousElementSibling?.textContent||'Company',country:g('country')?.previousElementSibling?.textContent||'Country',contact:g('contact')?.previousElementSibling?.textContent||'Contact',product:g('product')?.previousElementSibling?.textContent||'Product',message:g('message')?.previousElementSibling?.textContent||'Message'};return `${labels.name}: ${val('name')}\n${labels.company}: ${val('company')}\n${labels.country}: ${val('country')}\n${labels.contact}: ${val('contact')}\n${labels.product}: ${product}\n\n${labels.message}:\n${val('message')}`}
function openDemo(){const w=window.open('demo.html','KalesFDE_IMS_Demo');if(w)w.focus();else window.location.href='demo.html'}
function closeDemo(){if(window.opener&&!window.opener.closed){window.opener.focus();window.close();return}window.location.href='index.html#demo'}
function missingRequired(form){const fields=qsa('[required]',form);const missing=[];fields.forEach(el=>{const v=(el.value||'').trim();if(!v||!el.checkValidity()){const label=el.previousElementSibling?.textContent?.trim()||el.name||'Field';missing.push(label);el.classList.add('field-error')}else el.classList.remove('field-error')});return missing}
document.addEventListener('DOMContentLoaded',()=>{
 applyLang();const sel=qs('#lang');if(sel)sel.addEventListener('change',e=>window.FDE_setLanguage(e.target.value));
 const mt=qs('.mobile-toggle'),nav=qs('.main-nav'),header=qs('.site-header');if(mt&&nav){mt.addEventListener('click',e=>{e.stopPropagation();if(!nav.classList.contains('open')){nav.classList.add('open');mt.setAttribute('aria-expanded','true')}});document.addEventListener('click',e=>{if(nav.classList.contains('open')&&!header.contains(e.target)){nav.classList.remove('open');mt.setAttribute('aria-expanded','false')}});nav.addEventListener('click',e=>e.stopPropagation())}
 qsa('[data-demo-open]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();openDemo()}));const close=qs('#closeDemo');if(close)close.addEventListener('click',closeDemo);
 qsa('.plan-card').forEach(card=>{card.addEventListener('click',e=>{if(e.target.closest('a,button'))return;toggleCard(card)});card.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('a,button')){e.preventDefault();toggleCard(card)}});qsa('[data-flip]',card).forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();toggleCard(card)}))});
 qsa('.faq-q').forEach(btn=>btn.addEventListener('click',()=>btn.closest('.faq-item').classList.toggle('open')));
 const search=qs('#faqSearch');if(search)search.addEventListener('input',()=>{const v=search.value.trim().toLocaleLowerCase();let shown=0;qsa('.faq-item').forEach(item=>{const q=(qs('.faq-q',item)?.textContent||'').toLocaleLowerCase();const hit=!v||q.includes(v);item.style.display=hit?'':'none';if(hit)shown++});const empty=qs('#faqEmpty');if(empty)empty.style.display=shown?'none':'block'});
 const demoSearch=qs('#demoSearch');if(demoSearch)demoSearch.addEventListener('input',()=>{const v=demoSearch.value.trim().toLowerCase();qsa('#inventoryBody tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(v)?'':'none')});
 qsa('[data-stock]').forEach(btn=>btn.addEventListener('click',()=>{const cell=btn.closest('tr')?.querySelector('[data-stock-value]');if(!cell)return;let n=parseInt(cell.textContent,10)||0;n=Math.max(0,n+(btn.dataset.stock==='in'?5:-5));cell.textContent=n;updateDemoKpis()}));
 const reset=qs('#demoReset');if(reset)reset.addEventListener('click',()=>{qsa('[data-stock-value]').forEach((c,i)=>c.textContent=[326,84,18,41,210][i]??c.textContent);if(demoSearch){demoSearch.value='';demoSearch.dispatchEvent(new Event('input'))}updateDemoKpis()});updateDemoKpis();
 const form=qs('#contactForm');if(form){qsa('input,select,textarea',form).forEach(el=>el.addEventListener('input',()=>el.classList.remove('field-error')));form.addEventListener('submit',e=>{e.preventDefault();const missing=missingRequired(form);if(missing.length){alert(`${t('missingRequiredAlert','未入力または入力形式に問題がある必須項目があります。')}\n\n${missing.join('\n')}`);return}const body=inquiryText(form);const product=qs('#product',form)?.value||'Inquiry';const subject=`Kale’s FDE Inquiry — ${product}`;const mailer=qs('#mailer',form)?.value;if(mailer==='gmail'){const url=`https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent('reyouinjune@gmail.com')}&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;const w=window.open(url,'_blank','noopener');if(!w)window.location.href=url}else{window.location.href=`mailto:reyouinjune@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`}})}
});
})();