(()=>{
const supported=['ja','en','zh-CN','zh-TW','ko','id','ms','vi','th','hi','ar'];
const qs=(s,c=document)=>c.querySelector(s);const qsa=(s,c=document)=>[...c.querySelectorAll(s)];
let lang=localStorage.getItem('fde-lang')||'ja';if(!supported.includes(lang))lang='ja';
const dict=()=>((window.FDE_I18N&&window.FDE_I18N[lang])||{});const t=(k,f)=>dict()[k]??f;
const PRICE_BASE_JPY=[49800,4980,99800,9800];
const PRICE_RATES={JPY:1,USD:0.00627731,CNY:0.0423289,TWD:0.201015,KRW:8.82247,IDR:111.918,MYR:0.0256305,VND:164.052,THB:0.206395,INR:0.594424,AED:0.0230533};
const PRICE_CURRENCY_BY_LANG={ja:'JPY',en:'USD','zh-CN':'CNY','zh-TW':'TWD',ko:'KRW',id:'IDR',ms:'MYR',vi:'VND',th:'THB',hi:'INR',ar:'AED'};
const PRICE_LOCALE_BY_LANG={ja:'ja-JP',en:'en-US','zh-CN':'zh-CN','zh-TW':'zh-TW',ko:'ko-KR',id:'id-ID',ms:'ms-MY',vi:'vi-VN',th:'th-TH',hi:'hi-IN',ar:'ar-AE'};
const PRICE_LABELS={
 ja:{currency:'表示通貨',note:''},
 en:{currency:'Price currency',note:'Reference conversion from JPY using rates as of 2026-08-16. Final amount is confirmed in the quotation.'},
 'zh-CN':{currency:'价格货币',note:'参考换算（汇率基准：2026-08-16）。最终金额以报价为准。'},
 'zh-TW':{currency:'價格貨幣',note:'參考換算（匯率基準：2026-08-16）。最終金額以報價為準。'},
 ko:{currency:'가격 통화',note:'참고 환산 가격(환율 기준: 2026-08-16). 최종 금액은 견적에서 확정됩니다.'},
 id:{currency:'Mata uang harga',note:'Konversi perkiraan (kurs acuan: 2026-08-16). Harga akhir dikonfirmasi pada penawaran.'},
 ms:{currency:'Mata wang harga',note:'Anggaran penukaran (kadar rujukan: 2026-08-16). Harga akhir disahkan dalam sebut harga.'},
 vi:{currency:'Đơn vị tiền tệ',note:'Giá quy đổi tham khảo (tỷ giá ngày 2026-08-16). Giá cuối cùng được xác nhận trong báo giá.'},
 th:{currency:'สกุลเงินราคา',note:'ราคาแปลงโดยประมาณ (อัตราอ้างอิง 2026-08-16) ราคาสุดท้ายยืนยันในใบเสนอราคา'},
 hi:{currency:'मूल्य मुद्रा',note:'अनुमानित रूपांतरण (संदर्भ दर: 2026-08-16)। अंतिम मूल्य कोटेशन में तय होगा।'},
 ar:{currency:'عملة السعر',note:'تحويل تقريبي (سعر الصرف المرجعي: 2026-08-16). يتم تأكيد السعر النهائي في عرض السعر.'}
};
function polishJapaneseHeadings(){if(lang!=='ja')return;qsa('h1,h2,h3,.section-title,.display,.strong').forEach(el=>{if(el.children.length===0){el.textContent=el.textContent.replace(/[。．]\s*$/,'').trim()}else{const last=el.lastChild;if(last&&last.nodeType===3)last.textContent=last.textContent.replace(/[。．]\s*$/,'')}})}
function ensurePricingStyles(){if(document.getElementById('fde-pricing-currency-style'))return;const st=document.createElement('style');st.id='fde-pricing-currency-style';st.textContent='.currency-tools{display:flex;align-items:center;justify-content:flex-end;gap:12px;margin:-4px 0 22px;padding:13px 15px;border:1px solid var(--line);background:#f7faf8}.currency-tools label{font-size:11px;font-weight:900;letter-spacing:.06em;color:var(--green-deep)}.currency-tools select{min-width:150px;padding:10px 34px 10px 12px;border:1px solid #b9c8bf;background:#fff;color:var(--ink);font:inherit;font-size:12px;font-weight:800}.currency-fx-note{margin:-10px 0 24px;color:var(--muted);font-size:11px;line-height:1.7;text-align:right}.currency-fixed{display:inline-flex;align-items:center;justify-content:center;min-width:76px;padding:9px 12px;border:1px solid #b9c8bf;background:#fff;color:var(--ink);font-size:12px;font-weight:900}@media(max-width:760px){.currency-tools{justify-content:space-between;align-items:center;margin-top:0}.currency-tools select{min-width:128px}.currency-fx-note{text-align:left;margin-top:-10px}.plan-price{white-space:nowrap}}';document.head.appendChild(st)}
function ensureCurrencyUi(){const plans=qs('#plans .shell'),grid=qs('#plans .plan-grid');if(!plans||!grid)return null;ensurePricingStyles();let tools=qs('#fdeCurrencyTools',plans);if(!tools){tools=document.createElement('div');tools.id='fdeCurrencyTools';tools.className='currency-tools';tools.innerHTML='<label for="fdeCurrencySelect"></label><select id="fdeCurrencySelect" aria-label="Price currency"></select>';plans.insertBefore(tools,grid)}let note=qs('#fdeCurrencyNote',plans);if(!note){note=document.createElement('div');note.id='fdeCurrencyNote';note.className='currency-fx-note';plans.insertBefore(note,grid)}return{tools,note,select:qs('#fdeCurrencySelect',tools),label:qs('label',tools)}}
function priceCurrency(){const local=PRICE_CURRENCY_BY_LANG[lang]||'USD';if(lang==='ja'||lang==='en')return local;const saved=localStorage.getItem(`fde-price-currency-${lang}`);return saved==='USD'||saved===local?saved:local}
function formatPrice(jpy,currency){const rate=PRICE_RATES[currency]||1;const value=Math.round(jpy*rate);return new Intl.NumberFormat(PRICE_LOCALE_BY_LANG[lang]||'en-US',{style:'currency',currency,minimumFractionDigits:0,maximumFractionDigits:0}).format(value)}
function updateLocalizedPricing(){const prices=qsa('#plans .plan-price');if(!prices.length)return;const ui=ensureCurrencyUi();const local=PRICE_CURRENCY_BY_LANG[lang]||'USD';const currency=priceCurrency();prices.forEach((el,i)=>{const amount=formatPrice(PRICE_BASE_JPY[i]??0,currency);if(el.firstChild&&el.firstChild.nodeType===3)el.firstChild.nodeValue=amount+' ';else el.insertBefore(document.createTextNode(amount+' '),el.firstChild)});if(!ui)return;const copy=PRICE_LABELS[lang]||PRICE_LABELS.en;ui.label.textContent=copy.currency;ui.note.textContent=copy.note;if(lang==='ja'||lang==='en'){ui.tools.hidden=true;ui.note.hidden=lang==='ja';return}ui.tools.hidden=false;ui.note.hidden=false;ui.select.innerHTML=`<option value="${local}">${local}</option><option value="USD">USD</option>`;ui.select.value=currency;if(!ui.select.dataset.bound){ui.select.dataset.bound='1';ui.select.addEventListener('change',e=>{localStorage.setItem(`fde-price-currency-${lang}`,e.target.value);updateLocalizedPricing()})}}
function applyLang(){const d=dict();document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';qsa('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(d[k]!=null)el.textContent=d[k]});qsa('[data-i18n-html]').forEach(el=>{const k=el.dataset.i18nHtml;if(d[k]!=null)el.innerHTML=d[k]});qsa('[data-i18n-placeholder]').forEach(el=>{const k=el.dataset.i18nPlaceholder;if(d[k]!=null)el.setAttribute('placeholder',d[k])});qsa('[data-origin-note]').forEach(el=>el.hidden=lang==='ja');const sel=qs('#lang');if(sel)sel.value=lang;const md=qs('meta[name="description"]');if(md&&d.metaDescription)md.content=d.metaDescription;qsa('.display br').forEach(br=>br.replaceWith(document.createTextNode(' ')));polishJapaneseHeadings();updateLocalizedPricing()}
window.FDE_setLanguage=n=>{if(!supported.includes(n))return;lang=n;localStorage.setItem('fde-lang',n);applyLang()};
function toggleCard(card){card.classList.toggle('flipped')}
function updateDemoKpis(){const vals=qsa('[data-stock-value]').map(c=>parseInt(c.textContent,10)||0);const total=qs('#kpiItems'),low=qs('#kpiLow');if(total)total.textContent=qsa('#inventoryBody tr').length;if(low)low.textContent=vals.filter(v=>v<30).length;qsa('#inventoryBody tr').forEach(r=>{const cell=qs('[data-stock-value]',r),status=qs('[data-stock-status]',r);if(cell&&status)status.textContent=(parseInt(cell.textContent,10)||0)<30?'Low':'Healthy'})}
function inquiryText(form){const g=id=>qs('#'+id,form);const val=id=>g(id)?.value.trim()||'';const product=g('product')?.value||'';const labels={name:g('name')?.previousElementSibling?.textContent||'Name',company:g('company')?.previousElementSibling?.textContent||'Company',country:g('country')?.previousElementSibling?.textContent||'Country',contact:g('contact')?.previousElementSibling?.textContent||'Contact',product:g('product')?.previousElementSibling?.textContent||'Product',message:g('message')?.previousElementSibling?.textContent||'Message'};return `${labels.name}: ${val('name')}\n${labels.company}: ${val('company')}\n${labels.country}: ${val('country')}\n${labels.contact}: ${val('contact')}\n${labels.product}: ${product}\n\n${labels.message}:\n${val('message')}`}
function inquiryPayload(form){const value=id=>qs('#'+id,form)?.value.trim()||'';return{mailer:value('mailer'),name:value('name'),company:value('company'),country:value('country'),contact:value('contact'),product:value('product'),message:value('message'),recipient:'reyouinjune@gmail.com'}}
function renderConfirmation(form){const summary=qs('#confirmSummary');if(!summary)return;const p=inquiryPayload(form);const fields=[[t('fieldName','お名前'),p.name],[t('fieldCompany','企業名'),p.company],[t('fieldCountry','国名'),p.country],[t('fieldContact','返信先メールアドレス'),p.contact],[t('fieldProduct','製品名'),p.product],[t('fieldMessage','お問い合わせ内容'),p.message]];summary.innerHTML='';fields.forEach(([label,value])=>{const row=document.createElement('div');row.className='confirm-row';const dt=document.createElement('strong');dt.textContent=label;const dd=document.createElement('span');dd.textContent=value;row.append(dt,dd);summary.appendChild(row)})}
function openDemo(){const w=window.open('demo.html','KalesFDE_IMS_Demo');if(w)w.focus();else window.location.href='demo.html'}
function closeDemo(){if(window.opener&&!window.opener.closed){window.opener.focus();window.close();return}window.location.href='index.html#demo'}
function missingRequired(form){const fields=qsa('[required]',form);const missing=[];fields.forEach(el=>{const v=(el.value||'').trim();if(!v||!el.checkValidity()){const label=el.previousElementSibling?.textContent?.trim()||el.name||'Field';missing.push(label);el.classList.add('field-error')}else el.classList.remove('field-error')});return missing}
async function sendDirectInquiry(form){const endpoint=document.body.dataset.contactEndpoint||window.FDE_CONTACT_ENDPOINT||'';if(!endpoint)throw new Error('CONTACT_ENDPOINT_NOT_CONFIGURED');const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(inquiryPayload(form))});if(!res.ok)throw new Error(`HTTP_${res.status}`);return res}
document.addEventListener('DOMContentLoaded',()=>{
 applyLang();const sel=qs('#lang');if(sel)sel.addEventListener('change',e=>window.FDE_setLanguage(e.target.value));
 const mt=qs('.mobile-toggle'),nav=qs('.main-nav'),header=qs('.site-header');if(mt&&nav){mt.addEventListener('click',e=>{e.stopPropagation();if(!nav.classList.contains('open')){nav.classList.add('open');mt.setAttribute('aria-expanded','true')}});document.addEventListener('click',e=>{if(nav.classList.contains('open')&&!header.contains(e.target)){nav.classList.remove('open');mt.setAttribute('aria-expanded','false')}});nav.addEventListener('click',e=>e.stopPropagation())}
 qsa('[data-demo-open]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();openDemo()}));const close=qs('#closeDemo');if(close)close.addEventListener('click',closeDemo);
 qsa('.plan-card').forEach(card=>{card.addEventListener('click',e=>{if(e.target.closest('a,button'))return;toggleCard(card)});card.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('a,button')){e.preventDefault();toggleCard(card)}});qsa('[data-flip]',card).forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();toggleCard(card)}))});
 qsa('.faq-q').forEach(btn=>btn.addEventListener('click',()=>btn.closest('.faq-item').classList.toggle('open')));
 const search=qs('#faqSearch');if(search)search.addEventListener('input',()=>{const v=search.value.trim().toLocaleLowerCase();let shown=0;qsa('.faq-item').forEach(item=>{const q=(qs('.faq-q',item)?.textContent||'').toLocaleLowerCase();const hit=!v||q.includes(v);item.style.display=hit?'':'none';if(hit)shown++});const empty=qs('#faqEmpty');if(empty)empty.style.display=shown?'none':'block'});
 const demoSearch=qs('#demoSearch');if(demoSearch)demoSearch.addEventListener('input',()=>{const v=demoSearch.value.trim().toLowerCase();qsa('#inventoryBody tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(v)?'':'none')});
 qsa('[data-stock]').forEach(btn=>btn.addEventListener('click',()=>{const cell=btn.closest('tr')?.querySelector('[data-stock-value]');if(!cell)return;let n=parseInt(cell.textContent,10)||0;n=Math.max(0,n+(btn.dataset.stock==='in'?5:-5));cell.textContent=n;updateDemoKpis()}));
 const reset=qs('#demoReset');if(reset)reset.addEventListener('click',()=>{qsa('[data-stock-value]').forEach((c,i)=>c.textContent=[326,84,18,41,210][i]??c.textContent);if(demoSearch){demoSearch.value='';demoSearch.dispatchEvent(new Event('input'))}updateDemoKpis()});updateDemoKpis();
 const form=qs('#contactForm'),confirm=qs('#inquiryConfirm'),complete=qs('#inquiryComplete'),back=qs('#confirmBack'),send=qs('#confirmSend');
 if(form){qsa('input,select,textarea',form).forEach(el=>el.addEventListener('input',()=>el.classList.remove('field-error')));form.addEventListener('submit',e=>{e.preventDefault();const missing=missingRequired(form);if(missing.length){alert(`${t('missingRequiredAlert','未入力または入力形式に問題がある必須項目があります。')}\n\n${missing.join('\n')}`);return}const body=inquiryText(form);const product=qs('#product',form)?.value||'Inquiry';const subject=`Kale’s FDE Inquiry — ${product}`;const mailer=qs('#mailer',form)?.value;if(mailer==='gmail'){const url=`https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent('reyouinjune@gmail.com')}&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;window.location.assign(url);return}renderConfirmation(form);form.hidden=true;if(confirm){confirm.hidden=false;confirm.scrollIntoView({behavior:'smooth',block:'start'})}})}
 if(back&&form&&confirm)back.addEventListener('click',()=>{confirm.hidden=true;form.hidden=false;form.scrollIntoView({behavior:'smooth',block:'start'})});
 if(send&&form&&confirm&&complete)send.addEventListener('click',async()=>{send.disabled=true;send.classList.add('disabled');try{await sendDirectInquiry(form);confirm.hidden=true;complete.hidden=false;complete.scrollIntoView({behavior:'smooth',block:'start'});form.reset()}catch(err){if(String(err.message)==='CONTACT_ENDPOINT_NOT_CONFIGURED'){alert(t('directSendNotice','直接送信には送信用バックエンドの接続が必要です。'))}else{alert(t('sendFailed','送信に失敗しました。時間をおいてもう一度お試しください。'))}}finally{send.disabled=false;send.classList.remove('disabled')}});
});
})();