import baseWorker from './index-v3.js';

const PAID_STATUSES=new Set(['payment_confirmed','preparing_delivery','delivered']);
const SUPPORTED_LANGS=new Set(['ja','en','zh-CN','zh-TW','ko','id','ms','vi','th','hi','ar']);
const STATUS_JA={order_received:'注文受付',billing_preparation:'支払い案内準備',awaiting_payment:'支払い待ち',payment_confirmed:'支払い確認済み',preparing_delivery:'納品準備',delivered:'納品完了'};
const I18N={
 en:{quote:'Quotation & Order',invoice:'Invoice',delivery:'Delivery Note',receipt:'Receipt',issueDate:'Issue date',billTo:'Bill to',orderId:'Order ID',product:'Product',plan:'Plan',status:'Status',validUntil:'Valid until',currency:'Currency',description:'Description',amount:'Amount',one:'One-time purchase',monthly:'Monthly plan',specialDiscount:'Special discount',quotedTotal:'Quoted total',invoiceTotal:'Amount due',orderTotal:'Order total',receiptAmount:'Amount received',issuer:'Issuer',service:'Service',orderNotes:'Order notes',software:'Kale’s FDE software product',discountDesc:'Special discount applied to this order',quoteNote:'Taxes, payment fees and other charges are included in the product price. Payment instructions will be provided separately.',invoiceNote:'We hereby invoice the amount shown above. Payment instructions are provided separately.',deliveryNote:'The product above is delivered under this order.',receiptNote:'The amount above has been received as payment for the software product.',statuses:{order_received:'Order received',billing_preparation:'Payment preparation',awaiting_payment:'Awaiting payment',payment_confirmed:'Payment confirmed',preparing_delivery:'Preparing delivery',delivered:'Delivered'}},
 'zh-CN':{quote:'报价单兼订单',invoice:'请款发票',delivery:'交货单',receipt:'收据',issueDate:'开具日期',billTo:'收件方',orderId:'订单编号',product:'产品',plan:'方案',status:'状态',validUntil:'有效期至',currency:'币种',description:'内容',amount:'金额',one:'一次性购买',monthly:'月度方案',specialDiscount:'特别优惠',quotedTotal:'报价总额',invoiceTotal:'应付金额',orderTotal:'订单总额',receiptAmount:'实收金额',issuer:'开具方',service:'服务',orderNotes:'订单备注',software:'Kale’s FDE 软件产品',discountDesc:'本订单适用的特别优惠',quoteNote:'税费、支付手续费及其他相关费用均已包含在产品价格中。付款方式将另行通知。',invoiceNote:'现向您请款上述金额。付款方式将另行通知。',deliveryNote:'上述产品依据本订单交付。',receiptNote:'已收到上述软件产品款项。',statuses:{order_received:'订单已受理',billing_preparation:'付款准备',awaiting_payment:'等待付款',payment_confirmed:'付款已确认',preparing_delivery:'准备交付',delivered:'已交付'}},
 'zh-TW':{quote:'報價單兼訂單',invoice:'請款發票',delivery:'交貨單',receipt:'收據',issueDate:'開立日期',billTo:'收件方',orderId:'訂單編號',product:'產品',plan:'方案',status:'狀態',validUntil:'有效期限',currency:'幣別',description:'內容',amount:'金額',one:'買斷',monthly:'月費方案',specialDiscount:'特別優惠',quotedTotal:'報價總額',invoiceTotal:'應付金額',orderTotal:'訂單總額',receiptAmount:'實收金額',issuer:'開立方',service:'服務',orderNotes:'訂單備註',software:'Kale’s FDE 軟體產品',discountDesc:'本訂單適用的特別優惠',quoteNote:'稅金、付款手續費及其他相關費用皆已包含在產品價格中。付款方式將另行通知。',invoiceNote:'現向您請款上述金額。付款方式將另行通知。',deliveryNote:'上述產品依本訂單交付。',receiptNote:'已收到上述軟體產品款項。',statuses:{order_received:'訂單已受理',billing_preparation:'付款準備',awaiting_payment:'等待付款',payment_confirmed:'付款已確認',preparing_delivery:'準備交付',delivered:'已交付'}},
 ko:{quote:'견적서 겸 주문서',invoice:'청구서',delivery:'납품서',receipt:'영수증',issueDate:'발행일',billTo:'수신처',orderId:'주문번호',product:'제품',plan:'계약 방식',status:'상태',validUntil:'유효기간',currency:'통화',description:'내용',amount:'금액',one:'일회성 구매',monthly:'월간 플랜',specialDiscount:'특별 할인',quotedTotal:'견적 금액',invoiceTotal:'청구 금액',orderTotal:'주문 금액',receiptAmount:'수령 금액',issuer:'발행자',service:'서비스',orderNotes:'주문 비고',software:'Kale’s FDE 소프트웨어 제품',discountDesc:'이 주문에 적용된 특별 할인',quoteNote:'세금, 결제 수수료 및 기타 비용은 제품 가격에 포함되어 있습니다. 결제 방법은 별도로 안내합니다.',invoiceNote:'상기 금액을 청구합니다. 결제 방법은 별도로 안내합니다.',deliveryNote:'상기 제품을 본 주문에 따라 납품합니다.',receiptNote:'상기 금액을 소프트웨어 제품 대금으로 수령했습니다.',statuses:{order_received:'주문 접수',billing_preparation:'결제 안내 준비',awaiting_payment:'결제 대기',payment_confirmed:'결제 확인',preparing_delivery:'납품 준비',delivered:'납품 완료'}},
 id:{quote:'Penawaran & Pesanan',invoice:'Invoice',delivery:'Surat Jalan',receipt:'Kuitansi',issueDate:'Tanggal terbit',billTo:'Ditujukan kepada',orderId:'ID Pesanan',product:'Produk',plan:'Paket',status:'Status',validUntil:'Berlaku hingga',currency:'Mata uang',description:'Deskripsi',amount:'Jumlah',one:'Pembelian satu kali',monthly:'Paket bulanan',specialDiscount:'Diskon khusus',quotedTotal:'Total penawaran',invoiceTotal:'Jumlah tagihan',orderTotal:'Total pesanan',receiptAmount:'Jumlah diterima',issuer:'Penerbit',service:'Layanan',orderNotes:'Catatan pesanan',software:'Produk perangkat lunak Kale’s FDE',discountDesc:'Diskon khusus yang diterapkan pada pesanan ini',quoteNote:'Pajak, biaya pembayaran, dan biaya lainnya sudah termasuk dalam harga produk. Petunjuk pembayaran akan diberikan secara terpisah.',invoiceNote:'Kami menagihkan jumlah yang tercantum di atas. Petunjuk pembayaran diberikan secara terpisah.',deliveryNote:'Produk di atas dikirim berdasarkan pesanan ini.',receiptNote:'Jumlah di atas telah diterima sebagai pembayaran produk perangkat lunak.',statuses:{order_received:'Pesanan diterima',billing_preparation:'Persiapan pembayaran',awaiting_payment:'Menunggu pembayaran',payment_confirmed:'Pembayaran dikonfirmasi',preparing_delivery:'Menyiapkan pengiriman',delivered:'Terkirim'}},
 ms:{quote:'Sebut Harga & Pesanan',invoice:'Invois',delivery:'Nota Penghantaran',receipt:'Resit',issueDate:'Tarikh terbit',billTo:'Kepada',orderId:'ID Pesanan',product:'Produk',plan:'Pelan',status:'Status',validUntil:'Sah sehingga',currency:'Mata wang',description:'Keterangan',amount:'Jumlah',one:'Pembelian sekali bayar',monthly:'Pelan bulanan',specialDiscount:'Diskaun khas',quotedTotal:'Jumlah sebut harga',invoiceTotal:'Jumlah perlu dibayar',orderTotal:'Jumlah pesanan',receiptAmount:'Jumlah diterima',issuer:'Pengeluar',service:'Perkhidmatan',orderNotes:'Nota pesanan',software:'Produk perisian Kale’s FDE',discountDesc:'Diskaun khas yang digunakan untuk pesanan ini',quoteNote:'Cukai, yuran pembayaran dan caj lain telah termasuk dalam harga produk. Arahan pembayaran akan diberikan secara berasingan.',invoiceNote:'Kami menuntut bayaran bagi jumlah yang dinyatakan di atas. Arahan pembayaran diberikan secara berasingan.',deliveryNote:'Produk di atas dihantar berdasarkan pesanan ini.',receiptNote:'Jumlah di atas telah diterima sebagai bayaran bagi produk perisian.',statuses:{order_received:'Pesanan diterima',billing_preparation:'Persediaan pembayaran',awaiting_payment:'Menunggu pembayaran',payment_confirmed:'Pembayaran disahkan',preparing_delivery:'Menyediakan penghantaran',delivered:'Dihantar'}},
 vi:{quote:'Báo giá kiêm Đơn hàng',invoice:'Hóa đơn yêu cầu thanh toán',delivery:'Phiếu giao hàng',receipt:'Biên nhận',issueDate:'Ngày phát hành',billTo:'Người nhận',orderId:'Mã đơn hàng',product:'Sản phẩm',plan:'Gói',status:'Trạng thái',validUntil:'Có hiệu lực đến',currency:'Tiền tệ',description:'Nội dung',amount:'Số tiền',one:'Mua một lần',monthly:'Gói hàng tháng',specialDiscount:'Giảm giá đặc biệt',quotedTotal:'Tổng báo giá',invoiceTotal:'Số tiền phải trả',orderTotal:'Tổng đơn hàng',receiptAmount:'Số tiền đã nhận',issuer:'Bên phát hành',service:'Dịch vụ',orderNotes:'Ghi chú đơn hàng',software:'Sản phẩm phần mềm Kale’s FDE',discountDesc:'Giảm giá đặc biệt áp dụng cho đơn hàng này',quoteNote:'Thuế, phí thanh toán và các chi phí khác đã được bao gồm trong giá sản phẩm. Hướng dẫn thanh toán sẽ được cung cấp riêng.',invoiceNote:'Chúng tôi yêu cầu thanh toán số tiền nêu trên. Hướng dẫn thanh toán được cung cấp riêng.',deliveryNote:'Sản phẩm trên được bàn giao theo đơn hàng này.',receiptNote:'Đã nhận số tiền trên cho sản phẩm phần mềm.',statuses:{order_received:'Đã nhận đơn hàng',billing_preparation:'Chuẩn bị thanh toán',awaiting_payment:'Chờ thanh toán',payment_confirmed:'Đã xác nhận thanh toán',preparing_delivery:'Chuẩn bị giao hàng',delivered:'Đã giao hàng'}},
 th:{quote:'ใบเสนอราคาและคำสั่งซื้อ',invoice:'ใบแจ้งหนี้',delivery:'ใบส่งของ',receipt:'ใบเสร็จ',issueDate:'วันที่ออก',billTo:'ผู้รับ',orderId:'รหัสคำสั่งซื้อ',product:'ผลิตภัณฑ์',plan:'แผน',status:'สถานะ',validUntil:'ใช้ได้ถึง',currency:'สกุลเงิน',description:'รายละเอียด',amount:'จำนวนเงิน',one:'ซื้อครั้งเดียว',monthly:'แผนรายเดือน',specialDiscount:'ส่วนลดพิเศษ',quotedTotal:'ยอดเสนอราคา',invoiceTotal:'ยอดที่ต้องชำระ',orderTotal:'ยอดคำสั่งซื้อ',receiptAmount:'จำนวนเงินที่ได้รับ',issuer:'ผู้ออกเอกสาร',service:'บริการ',orderNotes:'หมายเหตุคำสั่งซื้อ',software:'ผลิตภัณฑ์ซอฟต์แวร์ Kale’s FDE',discountDesc:'ส่วนลดพิเศษสำหรับคำสั่งซื้อนี้',quoteNote:'ภาษี ค่าธรรมเนียมการชำระเงิน และค่าใช้จ่ายอื่น ๆ รวมอยู่ในราคาผลิตภัณฑ์แล้ว จะแจ้งวิธีชำระเงินแยกต่างหาก',invoiceNote:'ขอเรียกเก็บเงินตามจำนวนที่ระบุด้านบน โดยจะแจ้งวิธีชำระเงินแยกต่างหาก',deliveryNote:'ส่งมอบผลิตภัณฑ์ข้างต้นตามคำสั่งซื้อนี้',receiptNote:'ได้รับชำระเงินตามจำนวนข้างต้นสำหรับผลิตภัณฑ์ซอฟต์แวร์แล้ว',statuses:{order_received:'รับคำสั่งซื้อแล้ว',billing_preparation:'เตรียมการชำระเงิน',awaiting_payment:'รอการชำระเงิน',payment_confirmed:'ยืนยันการชำระเงินแล้ว',preparing_delivery:'เตรียมส่งมอบ',delivered:'ส่งมอบแล้ว'}},
 hi:{quote:'कोटेशन एवं ऑर्डर',invoice:'इनवॉइस',delivery:'डिलीवरी नोट',receipt:'रसीद',issueDate:'जारी करने की तारीख',billTo:'प्राप्तकर्ता',orderId:'ऑर्डर ID',product:'उत्पाद',plan:'योजना',status:'स्थिति',validUntil:'वैधता',currency:'मुद्रा',description:'विवरण',amount:'राशि',one:'एकमुश्त खरीद',monthly:'मासिक योजना',specialDiscount:'विशेष छूट',quotedTotal:'कोटेशन कुल',invoiceTotal:'देय राशि',orderTotal:'ऑर्डर कुल',receiptAmount:'प्राप्त राशि',issuer:'जारीकर्ता',service:'सेवा',orderNotes:'ऑर्डर नोट्स',software:'Kale’s FDE सॉफ़्टवेयर उत्पाद',discountDesc:'इस ऑर्डर पर लागू विशेष छूट',quoteNote:'कर, भुगतान शुल्क और अन्य शुल्क उत्पाद मूल्य में शामिल हैं। भुगतान निर्देश अलग से दिए जाएंगे।',invoiceNote:'ऊपर दर्शाई गई राशि का इनवॉइस जारी किया जाता है। भुगतान निर्देश अलग से दिए जाएंगे।',deliveryNote:'ऊपर दिया गया उत्पाद इस ऑर्डर के अनुसार डिलीवर किया जाता है।',receiptNote:'ऊपर दी गई राशि सॉफ़्टवेयर उत्पाद के भुगतान के रूप में प्राप्त हुई है।',statuses:{order_received:'ऑर्डर प्राप्त',billing_preparation:'भुगतान तैयारी',awaiting_payment:'भुगतान की प्रतीक्षा',payment_confirmed:'भुगतान की पुष्टि',preparing_delivery:'डिलीवरी की तैयारी',delivered:'डिलीवर किया गया'}},
 ar:{quote:'عرض السعر والطلب',invoice:'فاتورة',delivery:'مذكرة تسليم',receipt:'إيصال',issueDate:'تاريخ الإصدار',billTo:'إلى',orderId:'رقم الطلب',product:'المنتج',plan:'الخطة',status:'الحالة',validUntil:'صالح حتى',currency:'العملة',description:'الوصف',amount:'المبلغ',one:'شراء لمرة واحدة',monthly:'خطة شهرية',specialDiscount:'خصم خاص',quotedTotal:'إجمالي عرض السعر',invoiceTotal:'المبلغ المستحق',orderTotal:'إجمالي الطلب',receiptAmount:'المبلغ المستلم',issuer:'الجهة المصدرة',service:'الخدمة',orderNotes:'ملاحظات الطلب',software:'منتج برمجي من Kale’s FDE',discountDesc:'خصم خاص مطبق على هذا الطلب',quoteNote:'الضرائب ورسوم الدفع والرسوم الأخرى مشمولة في سعر المنتج. سيتم تقديم تعليمات الدفع بشكل منفصل.',invoiceNote:'نصدر فاتورة بالمبلغ الموضح أعلاه. سيتم تقديم تعليمات الدفع بشكل منفصل.',deliveryNote:'يتم تسليم المنتج أعلاه بموجب هذا الطلب.',receiptNote:'تم استلام المبلغ أعلاه كدفعة مقابل المنتج البرمجي.',statuses:{order_received:'تم استلام الطلب',billing_preparation:'إعداد الدفع',awaiting_payment:'بانتظار الدفع',payment_confirmed:'تم تأكيد الدفع',preparing_delivery:'تجهيز التسليم',delivered:'تم التسليم'}}
};

function clean(v,max=4000){return String(v??'').trim().slice(0,max)}
function esc(v){return clean(v,20000).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;')}
function cors(origin,allowedOrigin){const allow=origin&&origin===allowedOrigin?origin:allowedOrigin;return{'Access-Control-Allow-Origin':allow,'Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type','Access-Control-Expose-Headers':'Content-Disposition','Vary':'Origin'}}
function json(data,status,origin,allowedOrigin){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8',...cors(origin,allowedOrigin)}})}
function validOrderId(v){return /^BK-\d{8}-[A-F0-9]{8}$/i.test(v)}
function dateOnly(v){if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?String(v).slice(0,10):d.toISOString().slice(0,10)}
function money(value,currency){try{return new Intl.NumberFormat('en-US',{style:'currency',currency:clean(currency,10)||'JPY',minimumFractionDigits:0,maximumFractionDigits:0}).format(Math.round(Number(value)||0))}catch{return`${Math.round(Number(value)||0).toLocaleString('en-US')} ${clean(currency,10)||''}`.trim()}}
async function readJson(env,key){const raw=await env.ORDER_STATUS?.get(key);if(!raw)return null;try{return JSON.parse(raw)}catch{return null}}
function tr(order){const lang=SUPPORTED_LANGS.has(order?.lang)?order.lang:'ja';return{lang,t:I18N[lang]||null}}
function bi(ja,translated,lang){if(lang==='ja'||!translated||translated===ja)return esc(ja);return `<span class="ja">${esc(ja)}</span><br><span class="translated">${esc(translated)}</span>`}
function planPair(plan,ctx){const ja=plan==='monthly'?'月額プラン':'買い切り';const translated=ctx.t?(plan==='monthly'?ctx.t.monthly:ctx.t.one):ja;return bi(ja,translated,ctx.lang)}
function statusPair(status,ctx){const ja=STATUS_JA[status]||status||'注文受付';const translated=ctx.t?.statuses?.[status]||ja;return bi(ja,translated,ctx.lang)}
function documentMeta(type,order,status,ctx){
 const suffix=order.orderId.replace(/^BK-/,'');
 if(type==='quote_order')return{ja:'見積書兼注文書',translated:ctx.t?.quote,number:`Q-${suffix}`,date:order.quoteDate||dateOnly(order.createdAt),validUntil:order.validUntil||'',badge:'ORDER'};
 if(type==='invoice')return{ja:'請求書',translated:ctx.t?.invoice,number:`INV-${suffix}`,date:dateOnly(status?.updatedAt||new Date()),validUntil:'',badge:'INVOICE'};
 if(type==='delivery_note')return{ja:'納品書',translated:ctx.t?.delivery,number:`DN-${suffix}`,date:dateOnly(status?.updatedAt||new Date()),validUntil:'',badge:'DELIVERY'};
 return{ja:'領収書',translated:ctx.t?.receipt,number:`RCPT-${suffix}`,date:dateOnly(status?.updatedAt||new Date()),validUntil:'',badge:'PAID'};
}
function documentHtml(type,order,status){
 const ctx=tr(order),meta=documentMeta(type,order,status,ctx),c=order.customer||{};
 const amountJa=type==='quote_order'?'見積価格':type==='invoice'?'請求金額':type==='receipt'?'領収金額':'注文金額';
 const amountTr=type==='quote_order'?ctx.t?.quotedTotal:type==='invoice'?ctx.t?.invoiceTotal:type==='receipt'?ctx.t?.receiptAmount:ctx.t?.orderTotal;
 const noteJa=type==='quote_order'?'税金・決済手数料・その他の諸費用は製品価格に含まれています。支払い方法は別途ご案内します。':type==='invoice'?'上記金額をご請求します。支払い方法は別途ご案内します。':type==='receipt'?'上記金額を製品代金として領収しました。':'上記製品を本注文に基づき納品します。';
 const noteTr=type==='quote_order'?ctx.t?.quoteNote:type==='invoice'?ctx.t?.invoiceNote:type==='receipt'?ctx.t?.receiptNote:ctx.t?.deliveryNote;
 const originalPrice=order.originalPrice||status?.originalPrice||order.price||status?.price||'';
 const finalPrice=order.price||status?.price||originalPrice;
 const discount=Math.max(0,Number(order.specialDiscount??status?.specialDiscount??0)||0);
 const discountDisplay=money(discount,order.currency||status?.currency||'JPY');
 const discountRow=discount>0?`<tr class="discount"><td><b>${bi('特別割引',ctx.t?.specialDiscount,ctx.lang)}</b><br>${bi('本注文に適用する特別割引',ctx.t?.discountDesc,ctx.lang)}</td><td>—</td><td class="amount">-${esc(discountDisplay)}</td></tr>`:'';
 const dir=ctx.lang==='ar'?'rtl':'ltr';
 return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><style>
 @page{size:A4;margin:14mm 14mm 16mm}*{box-sizing:border-box}body{margin:0;color:#17251f;font-family:'Noto Sans CJK JP','IPA Gothic',sans-serif;font-size:10.5px;line-height:1.55}.translated{color:#4f6158;font-size:.94em;direction:${dir};unicode-bidi:isolate}.ja{font-weight:650}.top{display:flex;justify-content:space-between;gap:24px;border-bottom:3px solid #0e7a4b;padding-bottom:15px;margin-bottom:20px}.brand small{display:block;color:#65736c;font-size:9px;letter-spacing:.12em;text-transform:uppercase}.brand strong{display:block;font-size:20px;margin-top:2px}.doc{text-align:right}.badge{display:inline-block;border:1px solid #0e7a4b;color:#0e7a4b;padding:3px 8px;font-size:9px;font-weight:700;letter-spacing:.1em}.doc h1{font-size:19px;margin:7px 0 0;line-height:1.35}.doc p{margin:2px 0;color:#65736c}.to{margin:0 0 18px}.to small{color:#65736c}.to strong{display:block;font-size:15px;margin-top:3px}.meta{display:grid;grid-template-columns:1fr 1fr;gap:8px 20px;padding:12px 14px;background:#f1f6f2;border:1px solid #d7e1da;margin-bottom:16px}.meta div span{display:block;color:#65736c;font-size:9px}.meta div b{font-size:10.5px}.table{width:100%;border-collapse:collapse;margin-bottom:16px}.table th,.table td{padding:9px;border-bottom:1px solid #d7e1da;text-align:left;vertical-align:top}.table th{background:#eef6f1;font-size:9px;color:#65736c}.table td.amount{font-size:14px;font-weight:800;text-align:right}.table .discount td{background:#fafcfb}.table .discount td.amount{color:#0e7a4b}.total{display:flex;justify-content:flex-end;margin:16px 0}.totalbox{min-width:300px;border-top:2px solid #17251f;border-bottom:2px solid #17251f;padding:11px 0;display:flex;justify-content:space-between;align-items:baseline;gap:20px}.totalbox span{font-size:10px;color:#65736c}.totalbox strong{font-size:19px}.discount-summary{display:flex;justify-content:flex-end;margin-top:-8px}.discount-summary div{min-width:300px;display:flex;justify-content:space-between;color:#65736c;font-size:10px}.note{margin-top:20px;padding:13px 15px;border-left:4px solid #0e7a4b;background:#eef6f1}.issuer{margin-top:24px;display:flex;justify-content:space-between;gap:20px;border-top:1px solid #d7e1da;padding-top:14px}.issuer small{display:block;color:#65736c}.issuer strong{font-size:12px}.footer{margin-top:16px;color:#65736c;font-size:8.5px;text-align:right}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}
 </style></head><body><header class="top"><div class="brand"><small>Baked Kale</small><strong>Kale’s FDE</strong><small>Forward Deployed Engineering</small></div><div class="doc"><span class="badge">${esc(meta.badge)}</span><h1>${bi(meta.ja,meta.translated,ctx.lang)}</h1><p>No. <span class="mono">${esc(meta.number)}</span></p><p>${bi('発行日',ctx.t?.issueDate,ctx.lang)}: ${esc(meta.date)}</p></div></header>
 <section class="to"><small>${bi('宛先',ctx.t?.billTo,ctx.lang)}</small><strong>${esc(c.company||c.name||'Customer')} 御中</strong><div>${esc(c.name||'')} ${c.email?`&lt;${esc(c.email)}&gt;`:''}${c.country?` / ${esc(c.country)}`:''}</div></section>
 <section class="meta"><div><span>${bi('注文番号',ctx.t?.orderId,ctx.lang)}</span><b class="mono">${esc(order.orderId)}</b></div><div><span>${bi('製品',ctx.t?.product,ctx.lang)}</span><b>${esc(order.product)}</b></div><div><span>${bi('契約方法',ctx.t?.plan,ctx.lang)}</span><b>${planPair(order.plan,ctx)}</b></div><div><span>${bi('注文状況',ctx.t?.status,ctx.lang)}</span><b>${statusPair(status?.status||'order_received',ctx)}</b></div>${meta.validUntil?`<div><span>${bi('有効期限',ctx.t?.validUntil,ctx.lang)}</span><b>${esc(meta.validUntil)}</b></div>`:''}<div><span>${bi('通貨',ctx.t?.currency,ctx.lang)}</span><b>${esc(order.currency||status?.currency||'')}</b></div></section>
 <table class="table"><thead><tr><th>${bi('内容',ctx.t?.description,ctx.lang)}</th><th>${bi('契約',ctx.t?.plan,ctx.lang)}</th><th style="text-align:right">${bi('金額',ctx.t?.amount,ctx.lang)}</th></tr></thead><tbody><tr><td><b>${esc(order.product)}</b><br>${bi('Kale’s FDE ソフトウェア製品',ctx.t?.software,ctx.lang)}</td><td>${planPair(order.plan,ctx)}</td><td class="amount">${esc(originalPrice)}</td></tr>${discountRow}</tbody></table>
 ${discount>0?`<div class="discount-summary"><div><span>${bi('特別割引',ctx.t?.specialDiscount,ctx.lang)}</span><strong>-${esc(discountDisplay)}</strong></div></div>`:''}
 <div class="total"><div class="totalbox"><span>${bi(amountJa,amountTr,ctx.lang)}</span><strong>${esc(finalPrice)}</strong></div></div>
 <section class="note">${bi(noteJa,noteTr,ctx.lang)}</section>
 ${order.notes?`<section class="note"><b>${bi('注文備考',ctx.t?.orderNotes,ctx.lang)}</b><br>${esc(order.notes).replaceAll('\n','<br>')}</section>`:''}
 <section class="issuer"><div><small>${bi('発行者',ctx.t?.issuer,ctx.lang)}</small><strong>Baked Kale / Kale’s FDE</strong><div>Japan - Nara Prefecture</div></div><div style="text-align:right"><small>${bi('サービス',ctx.t?.service,ctx.lang)}</small><strong>Forward Deployed Engineering</strong><div class="mono">${esc(order.orderId)}</div></div></section>
 <div class="footer">Generated from the Kale’s FDE order record / Kale’s FDE注文台帳から生成</div></body></html>`;
}
async function generatePdf(env,type,order,status){
 if(!env.BROWSER?.quickAction)throw new Error('BROWSER_NOT_CONFIGURED');
 const rendered=await env.BROWSER.quickAction('pdf',{html:documentHtml(type,order,status),pdfOptions:{format:'a4',printBackground:true,preferCSSPageSize:true,margin:{top:'0px',bottom:'0px',left:'0px',right:'0px'}}});
 if(!rendered?.ok)throw new Error(`PDF_RENDER_${rendered?.status||500}`);
 return rendered.arrayBuffer();
}

export default{
 async fetch(request,env,ctx){
  const origin=request.headers.get('Origin')||'',allowedOrigin=env.ALLOWED_ORIGIN||'https://kale1205.github.io';
  const url=new URL(request.url);
  if(request.method==='GET'&&url.pathname.endsWith('/health'))return json({ok:true,service:'kales-fde-contact',version:'documents-v2',browserConfigured:!!env.BROWSER,orderStatusConfigured:!!env.ORDER_STATUS},200,origin,allowedOrigin);
  if(request.method==='OPTIONS')return baseWorker.fetch(request,env,ctx);
  if(request.method!=='POST')return baseWorker.fetch(request,env,ctx);
  let raw=null;try{raw=await request.clone().json()}catch{}
  const type=clean(raw?.type,40);
  if(type!=='admin_pdf')return baseWorker.fetch(request,env,ctx);
  if(origin&&origin!==allowedOrigin)return json({ok:false,error:'ORIGIN_NOT_ALLOWED'},403,origin,allowedOrigin);
  if(!env.ADMIN_FULFILLMENT_KEY)return json({ok:false,error:'ADMIN_FULFILLMENT_NOT_CONFIGURED'},503,origin,allowedOrigin);
  if(clean(raw?.adminKey,300)!==env.ADMIN_FULFILLMENT_KEY)return json({ok:false,error:'ADMIN_AUTH_FAILED'},403,origin,allowedOrigin);
  if(!env.ORDER_STATUS)return json({ok:false,error:'ORDER_STATUS_NOT_CONFIGURED'},503,origin,allowedOrigin);
  const orderId=clean(raw?.orderId,40).toUpperCase(),documentType=clean(raw?.documentType,40);
  if(!validOrderId(orderId)||!['quote_order','invoice','delivery_note','receipt'].includes(documentType))return json({ok:false,error:'INVALID_PDF_REQUEST'},400,origin,allowedOrigin);
  const order=await readJson(env,`admin-order:${orderId}`),status=await readJson(env,`order:${orderId}`);
  if(!order)return json({ok:false,error:'ADMIN_ORDER_NOT_FOUND'},404,origin,allowedOrigin);
  if(['delivery_note','receipt'].includes(documentType)&&!PAID_STATUSES.has(status?.status))return json({ok:false,error:'PAYMENT_NOT_CONFIRMED'},409,origin,allowedOrigin);
  try{
   const bytes=await generatePdf(env,documentType,order,status);
   const names={quote_order:'quotation-order',invoice:'invoice',delivery_note:'delivery-note',receipt:'receipt'};
   return new Response(bytes,{status:200,headers:{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="${names[documentType]}-${orderId}.pdf"`,'Cache-Control':'no-store',...cors(origin,allowedOrigin)}});
  }catch(error){console.error('PDF generation failed',error);const code=String(error?.message||'PDF_GENERATION_FAILED');return json({ok:false,error:code},code==='BROWSER_NOT_CONFIGURED'?503:502,origin,allowedOrigin)}
 }
};
