import baseWorker from './index-v11.js';

const BREVO_URL='https://api.brevo.com/v3/smtp/email';
const PORTAL_URL='https://kale1205.github.io/fde-site/customer.html';
const FLOW=['order_received','billing_preparation','awaiting_payment','payment_confirmed','preparing_delivery','delivered'];
const SUPPORTED=new Set(['ja','en','zh-CN','zh-TW','ko','id','ms','vi','th','hi','ar']);

const COPY={
 ja:{subject:'注文状況を更新しました',title:'注文状況が更新されました',hello:'様',current:'現在の状況',explain:'現状について',action:'お客様にお願いすること',flow:'注文フロー',portal:'注文状況を確認する',order:'注文番号',product:'製品',message:'運営からのメッセージ',footer:'このメールは注文ステータスの変更に伴う自動通知です。',cancelled:'キャンセル済み',statuses:{order_received:['注文受付','ご注文を受け付け、見積書兼注文書を送信済みです。','見積内容と注文情報をご確認ください。相違がある場合はContactからお知らせください。'],billing_preparation:['請求準備','請求書と支払い方法のご案内を準備しています。','現時点で操作は不要です。請求・支払い案内のメールをお待ちください。'],awaiting_payment:['支払い待ち','請求・支払い案内が完了し、ご入金をお待ちしている段階です。','請求内容と支払い方法をご確認のうえ、お支払いをお願いします。'],payment_confirmed:['支払い確認済み','お支払いを確認しました。現在、納品準備へ進んでいます。','現時点で操作は不要です。納品のご案内をお待ちください。'],preparing_delivery:['納品準備','納品書・領収書・製品インストーラーの準備を進めています。','現時点で操作は不要です。納品メールをお待ちください。'],delivered:['納品完了','納品書・領収書・製品インストーラーのご案内を送信しました。','納品メールをご確認し、必要な書類を保管のうえ、インストーラーから製品をご利用ください。'],cancelled:['キャンセル済み','この注文はキャンセルされました。注文履歴はCustomer Portalに残ります。','キャンセルに心当たりがない場合はContactからお問い合わせください。']}},
 en:{subject:'Order status updated',title:'Your order status has been updated',hello:'',current:'Current status',explain:'What is happening now',action:'What you need to do',flow:'Order flow',portal:'Check order status',order:'Order ID',product:'Product',message:'Message from our team',footer:'This is an automatic notification triggered by an order status change.',cancelled:'Cancelled',statuses:{order_received:['Order received','We received your order and sent the quotation and order form.','Please review the quotation and your order details. Contact us if anything is incorrect.'],billing_preparation:['Billing preparation','We are preparing your invoice and payment instructions.','No action is required yet. Please wait for the billing and payment email.'],awaiting_payment:['Awaiting payment','Billing instructions have been prepared and we are waiting for your payment.','Please review the invoice and payment instructions, then complete payment.'],payment_confirmed:['Payment confirmed','Your payment has been confirmed and we are moving to delivery preparation.','No action is required now. Please wait for the delivery email.'],preparing_delivery:['Preparing delivery','We are preparing the delivery note, receipt and product installer.','No action is required now. Please wait for the delivery email.'],delivered:['Delivered','The delivery note, receipt and product installer information have been sent.','Please check the delivery email, keep the documents you need, and use the installer to start using the product.'],cancelled:['Cancelled','This order has been cancelled. The order history remains available in the Customer Portal.','If you did not expect this cancellation, please contact us.']}},
 'zh-CN':{subject:'订单状态已更新',title:'您的订单状态已更新',hello:'',current:'当前状态',explain:'当前进度说明',action:'您需要做什么',flow:'订单流程',portal:'查看订单状态',order:'订单编号',product:'产品',message:'运营方留言',footer:'此邮件因订单状态变更而自动发送。',cancelled:'已取消',statuses:{order_received:['订单已受理','我们已收到您的订单，并已发送报价单兼订单。','请确认报价和订单信息。如有错误，请通过Contact联系我们。'],billing_preparation:['账单准备','我们正在准备发票和付款方式说明。','目前无需操作，请等待账单和付款说明邮件。'],awaiting_payment:['等待付款','账单和付款说明已准备完成，目前正在等待您的付款。','请确认发票和付款方式，并完成付款。'],payment_confirmed:['付款已确认','我们已确认您的付款，正在进入交付准备阶段。','目前无需操作，请等待交付邮件。'],preparing_delivery:['准备交付','我们正在准备交货单、收据和产品安装程序。','目前无需操作，请等待交付邮件。'],delivered:['已交付','交货单、收据和产品安装程序信息已发送。','请查看交付邮件，妥善保存所需文件，并通过安装程序开始使用产品。'],cancelled:['已取消','此订单已取消，订单记录仍会保留在Customer Portal中。','如果您并未申请取消，请联系我们。']}},
 'zh-TW':{subject:'訂單狀態已更新',title:'您的訂單狀態已更新',hello:'',current:'目前狀態',explain:'目前進度說明',action:'您需要進行的操作',flow:'訂單流程',portal:'查看訂單狀態',order:'訂單編號',product:'產品',message:'營運方留言',footer:'此郵件因訂單狀態變更而自動寄送。',cancelled:'已取消',statuses:{order_received:['訂單已受理','我們已收到您的訂單，並已寄送報價單兼訂單。','請確認報價與訂單資訊。如有錯誤，請透過Contact聯絡我們。'],billing_preparation:['帳務準備','我們正在準備發票與付款方式說明。','目前不需要操作，請等待帳務與付款說明郵件。'],awaiting_payment:['等待付款','帳務與付款說明已準備完成，目前正在等待您的付款。','請確認發票與付款方式，並完成付款。'],payment_confirmed:['付款已確認','我們已確認您的付款，目前正進入交付準備階段。','目前不需要操作，請等待交付郵件。'],preparing_delivery:['準備交付','我們正在準備交貨單、收據與產品安裝程式。','目前不需要操作，請等待交付郵件。'],delivered:['已交付','交貨單、收據與產品安裝程式資訊已寄送。','請確認交付郵件、妥善保存需要的文件，並使用安裝程式開始使用產品。'],cancelled:['已取消','此訂單已取消，訂單紀錄仍保留於Customer Portal。','若您並未預期此取消，請與我們聯絡。']}},
 ko:{subject:'주문 상태가 업데이트되었습니다',title:'주문 상태가 업데이트되었습니다',hello:'님',current:'현재 상태',explain:'현재 진행 상황',action:'고객님이 하실 일',flow:'주문 흐름',portal:'주문 상태 확인',order:'주문번호',product:'제품',message:'운영팀 메시지',footer:'이 메일은 주문 상태 변경에 따라 자동 발송되었습니다.',cancelled:'취소됨',statuses:{order_received:['주문 접수','주문을 접수했으며 견적서 겸 주문서를 발송했습니다.','견적 내용과 주문 정보를 확인해 주세요. 오류가 있으면 Contact로 알려 주세요.'],billing_preparation:['청구 준비','청구서와 결제 방법 안내를 준비하고 있습니다.','현재 별도 조치는 필요하지 않습니다. 청구 및 결제 안내 메일을 기다려 주세요.'],awaiting_payment:['결제 대기','청구 및 결제 안내가 준비되었으며 결제를 기다리고 있습니다.','청구서와 결제 방법을 확인한 뒤 결제를 완료해 주세요.'],payment_confirmed:['결제 확인','결제를 확인했으며 납품 준비 단계로 진행 중입니다.','현재 별도 조치는 필요하지 않습니다. 납품 메일을 기다려 주세요.'],preparing_delivery:['납품 준비','납품서, 영수증, 제품 설치 프로그램을 준비하고 있습니다.','현재 별도 조치는 필요하지 않습니다. 납품 메일을 기다려 주세요.'],delivered:['납품 완료','납품서, 영수증, 제품 설치 프로그램 안내를 발송했습니다.','납품 메일을 확인하고 필요한 문서를 보관한 후 설치 프로그램으로 제품을 이용해 주세요.'],cancelled:['취소됨','이 주문은 취소되었습니다. 주문 이력은 Customer Portal에 남아 있습니다.','예상하지 못한 취소라면 Contact로 문의해 주세요.']}},
 id:{subject:'Status pesanan diperbarui',title:'Status pesanan Anda telah diperbarui',hello:'',current:'Status saat ini',explain:'Yang sedang terjadi',action:'Yang perlu Anda lakukan',flow:'Alur pesanan',portal:'Periksa status pesanan',order:'ID Pesanan',product:'Produk',message:'Pesan dari tim kami',footer:'Email ini dikirim otomatis karena perubahan status pesanan.',cancelled:'Dibatalkan',statuses:{order_received:['Pesanan diterima','Kami telah menerima pesanan Anda dan mengirimkan penawaran serta formulir pesanan.','Periksa penawaran dan detail pesanan. Hubungi kami melalui Contact jika ada kesalahan.'],billing_preparation:['Persiapan tagihan','Kami sedang menyiapkan invoice dan petunjuk pembayaran.','Belum ada tindakan yang diperlukan. Tunggu email tagihan dan pembayaran.'],awaiting_payment:['Menunggu pembayaran','Petunjuk tagihan dan pembayaran telah disiapkan dan kami menunggu pembayaran Anda.','Periksa invoice dan petunjuk pembayaran, lalu selesaikan pembayaran.'],payment_confirmed:['Pembayaran dikonfirmasi','Pembayaran Anda telah dikonfirmasi dan kami masuk ke tahap persiapan pengiriman.','Tidak ada tindakan yang diperlukan saat ini. Tunggu email pengiriman.'],preparing_delivery:['Menyiapkan pengiriman','Kami sedang menyiapkan surat jalan, kuitansi, dan installer produk.','Tidak ada tindakan yang diperlukan saat ini. Tunggu email pengiriman.'],delivered:['Terkirim','Informasi surat jalan, kuitansi, dan installer produk telah dikirim.','Periksa email pengiriman, simpan dokumen yang diperlukan, lalu gunakan installer untuk mulai menggunakan produk.'],cancelled:['Dibatalkan','Pesanan ini telah dibatalkan. Riwayat pesanan tetap tersedia di Customer Portal.','Jika Anda tidak mengharapkan pembatalan ini, silakan hubungi kami.']}},
 ms:{subject:'Status pesanan dikemas kini',title:'Status pesanan anda telah dikemas kini',hello:'',current:'Status semasa',explain:'Perkembangan semasa',action:'Tindakan yang perlu anda ambil',flow:'Aliran pesanan',portal:'Semak status pesanan',order:'ID Pesanan',product:'Produk',message:'Mesej daripada pasukan kami',footer:'E-mel ini dihantar secara automatik apabila status pesanan berubah.',cancelled:'Dibatalkan',statuses:{order_received:['Pesanan diterima','Kami telah menerima pesanan anda dan menghantar sebut harga serta borang pesanan.','Sila semak sebut harga dan butiran pesanan. Hubungi kami melalui Contact jika ada kesilapan.'],billing_preparation:['Persediaan bil','Kami sedang menyediakan invois dan arahan pembayaran.','Tiada tindakan diperlukan buat masa ini. Sila tunggu e-mel bil dan pembayaran.'],awaiting_payment:['Menunggu pembayaran','Arahan bil dan pembayaran telah disediakan dan kami sedang menunggu pembayaran anda.','Sila semak invois dan arahan pembayaran, kemudian lengkapkan pembayaran.'],payment_confirmed:['Pembayaran disahkan','Pembayaran anda telah disahkan dan kami sedang beralih ke persediaan penghantaran.','Tiada tindakan diperlukan sekarang. Sila tunggu e-mel penghantaran.'],preparing_delivery:['Menyediakan penghantaran','Kami sedang menyediakan nota penghantaran, resit dan pemasang produk.','Tiada tindakan diperlukan sekarang. Sila tunggu e-mel penghantaran.'],delivered:['Dihantar','Maklumat nota penghantaran, resit dan pemasang produk telah dihantar.','Sila semak e-mel penghantaran, simpan dokumen yang diperlukan dan gunakan pemasang untuk mula menggunakan produk.'],cancelled:['Dibatalkan','Pesanan ini telah dibatalkan. Sejarah pesanan kekal tersedia dalam Customer Portal.','Jika anda tidak menjangkakan pembatalan ini, sila hubungi kami.']}},
 vi:{subject:'Trạng thái đơn hàng đã được cập nhật',title:'Trạng thái đơn hàng của bạn đã được cập nhật',hello:'',current:'Trạng thái hiện tại',explain:'Tình trạng hiện tại',action:'Việc bạn cần làm',flow:'Quy trình đơn hàng',portal:'Kiểm tra trạng thái đơn hàng',order:'Mã đơn hàng',product:'Sản phẩm',message:'Tin nhắn từ đội ngũ vận hành',footer:'Email này được gửi tự động khi trạng thái đơn hàng thay đổi.',cancelled:'Đã hủy',statuses:{order_received:['Đã nhận đơn hàng','Chúng tôi đã nhận đơn hàng và gửi báo giá kiêm đơn hàng.','Vui lòng kiểm tra báo giá và thông tin đơn hàng. Nếu có sai sót, hãy liên hệ qua Contact.'],billing_preparation:['Chuẩn bị hóa đơn','Chúng tôi đang chuẩn bị hóa đơn và hướng dẫn thanh toán.','Hiện chưa cần thao tác. Vui lòng chờ email hóa đơn và thanh toán.'],awaiting_payment:['Chờ thanh toán','Hướng dẫn hóa đơn và thanh toán đã sẵn sàng và chúng tôi đang chờ thanh toán của bạn.','Vui lòng kiểm tra hóa đơn và hướng dẫn thanh toán, sau đó hoàn tất thanh toán.'],payment_confirmed:['Đã xác nhận thanh toán','Chúng tôi đã xác nhận thanh toán và đang chuyển sang chuẩn bị giao hàng.','Hiện chưa cần thao tác. Vui lòng chờ email giao hàng.'],preparing_delivery:['Chuẩn bị giao hàng','Chúng tôi đang chuẩn bị phiếu giao hàng, biên nhận và bộ cài sản phẩm.','Hiện chưa cần thao tác. Vui lòng chờ email giao hàng.'],delivered:['Đã giao hàng','Thông tin phiếu giao hàng, biên nhận và bộ cài sản phẩm đã được gửi.','Vui lòng kiểm tra email giao hàng, lưu các tài liệu cần thiết và dùng bộ cài để bắt đầu sử dụng sản phẩm.'],cancelled:['Đã hủy','Đơn hàng này đã bị hủy. Lịch sử đơn hàng vẫn có trong Customer Portal.','Nếu bạn không mong đợi việc hủy này, vui lòng liên hệ với chúng tôi.']}},
 th:{subject:'อัปเดตสถานะคำสั่งซื้อแล้ว',title:'สถานะคำสั่งซื้อของคุณได้รับการอัปเดตแล้ว',hello:'',current:'สถานะปัจจุบัน',explain:'สถานการณ์ปัจจุบัน',action:'สิ่งที่คุณต้องดำเนินการ',flow:'ขั้นตอนคำสั่งซื้อ',portal:'ตรวจสอบสถานะคำสั่งซื้อ',order:'รหัสคำสั่งซื้อ',product:'ผลิตภัณฑ์',message:'ข้อความจากทีมงาน',footer:'อีเมลนี้ถูกส่งโดยอัตโนมัติเมื่อสถานะคำสั่งซื้อมีการเปลี่ยนแปลง',cancelled:'ยกเลิกแล้ว',statuses:{order_received:['รับคำสั่งซื้อแล้ว','เราได้รับคำสั่งซื้อและส่งใบเสนอราคาและคำสั่งซื้อแล้ว','โปรดตรวจสอบใบเสนอราคาและข้อมูลคำสั่งซื้อ หากมีข้อผิดพลาดโปรดติดต่อผ่าน Contact'],billing_preparation:['เตรียมใบแจ้งหนี้','เรากำลังเตรียมใบแจ้งหนี้และคำแนะนำการชำระเงิน','ขณะนี้ยังไม่ต้องดำเนินการ โปรดรออีเมลเกี่ยวกับใบแจ้งหนี้และการชำระเงิน'],awaiting_payment:['รอการชำระเงิน','คำแนะนำเกี่ยวกับใบแจ้งหนี้และการชำระเงินพร้อมแล้ว และเรากำลังรอการชำระเงินของคุณ','โปรดตรวจสอบใบแจ้งหนี้และวิธีชำระเงิน แล้วดำเนินการชำระเงิน'],payment_confirmed:['ยืนยันการชำระเงินแล้ว','เราได้ยืนยันการชำระเงินและกำลังเข้าสู่ขั้นตอนเตรียมการส่งมอบ','ขณะนี้ไม่ต้องดำเนินการ โปรดรออีเมลการส่งมอบ'],preparing_delivery:['เตรียมส่งมอบ','เรากำลังเตรียมใบส่งของ ใบเสร็จ และตัวติดตั้งผลิตภัณฑ์','ขณะนี้ไม่ต้องดำเนินการ โปรดรออีเมลการส่งมอบ'],delivered:['ส่งมอบแล้ว','ได้ส่งข้อมูลใบส่งของ ใบเสร็จ และตัวติดตั้งผลิตภัณฑ์แล้ว','โปรดตรวจสอบอีเมลการส่งมอบ เก็บเอกสารที่จำเป็น และใช้ตัวติดตั้งเพื่อเริ่มใช้งานผลิตภัณฑ์'],cancelled:['ยกเลิกแล้ว','คำสั่งซื้อนี้ถูกยกเลิกแล้ว ประวัติคำสั่งซื้อยังคงอยู่ใน Customer Portal','หากคุณไม่ได้คาดว่าจะมีการยกเลิก โปรดติดต่อเรา']}},
 hi:{subject:'ऑर्डर की स्थिति अपडेट हुई',title:'आपके ऑर्डर की स्थिति अपडेट हुई है',hello:'',current:'वर्तमान स्थिति',explain:'अभी क्या हो रहा है',action:'आपको क्या करना है',flow:'ऑर्डर प्रक्रिया',portal:'ऑर्डर की स्थिति देखें',order:'ऑर्डर ID',product:'उत्पाद',message:'हमारी टीम का संदेश',footer:'यह ईमेल ऑर्डर की स्थिति बदलने पर स्वतः भेजा गया है।',cancelled:'रद्द',statuses:{order_received:['ऑर्डर प्राप्त','हमने आपका ऑर्डर प्राप्त कर लिया है और कोटेशन व ऑर्डर फ़ॉर्म भेज दिया है।','कृपया कोटेशन और ऑर्डर विवरण की जाँच करें। कोई त्रुटि हो तो Contact के माध्यम से बताएं।'],billing_preparation:['बिलिंग तैयारी','हम इनवॉइस और भुगतान निर्देश तैयार कर रहे हैं।','अभी कोई कार्रवाई आवश्यक नहीं है। कृपया बिलिंग और भुगतान ईमेल की प्रतीक्षा करें।'],awaiting_payment:['भुगतान की प्रतीक्षा','बिलिंग और भुगतान निर्देश तैयार हैं और हम आपके भुगतान की प्रतीक्षा कर रहे हैं।','कृपया इनवॉइस और भुगतान निर्देश देखें और भुगतान पूरा करें।'],payment_confirmed:['भुगतान की पुष्टि','आपके भुगतान की पुष्टि हो गई है और हम डिलीवरी की तैयारी कर रहे हैं।','अभी कोई कार्रवाई आवश्यक नहीं है। कृपया डिलीवरी ईमेल की प्रतीक्षा करें।'],preparing_delivery:['डिलीवरी की तैयारी','हम डिलीवरी नोट, रसीद और उत्पाद इंस्टॉलर तैयार कर रहे हैं।','अभी कोई कार्रवाई आवश्यक नहीं है। कृपया डिलीवरी ईमेल की प्रतीक्षा करें।'],delivered:['डिलीवर किया गया','डिलीवरी नोट, रसीद और उत्पाद इंस्टॉलर की जानकारी भेज दी गई है।','कृपया डिलीवरी ईमेल देखें, आवश्यक दस्तावेज सुरक्षित रखें और इंस्टॉलर से उत्पाद का उपयोग शुरू करें।'],cancelled:['रद्द','यह ऑर्डर रद्द कर दिया गया है। ऑर्डर इतिहास Customer Portal में उपलब्ध रहेगा।','यदि आपने इस रद्दीकरण की अपेक्षा नहीं की थी, तो कृपया हमसे संपर्क करें।']}},
 ar:{subject:'تم تحديث حالة الطلب',title:'تم تحديث حالة طلبك',hello:'',current:'الحالة الحالية',explain:'ما الذي يحدث الآن',action:'ما الذي عليك فعله',flow:'مسار الطلب',portal:'التحقق من حالة الطلب',order:'رقم الطلب',product:'المنتج',message:'رسالة من فريقنا',footer:'تم إرسال هذه الرسالة تلقائياً بسبب تغيير حالة الطلب.',cancelled:'ملغي',statuses:{order_received:['تم استلام الطلب','استلمنا طلبك وأرسلنا عرض السعر ونموذج الطلب.','يرجى مراجعة عرض السعر وتفاصيل الطلب. إذا وجدت أي خطأ فتواصل معنا عبر Contact.'],billing_preparation:['إعداد الفاتورة','نحن نجهز الفاتورة وتعليمات الدفع.','لا يلزم اتخاذ إجراء حالياً. يرجى انتظار رسالة الفاتورة والدفع.'],awaiting_payment:['بانتظار الدفع','تم إعداد الفاتورة وتعليمات الدفع ونحن بانتظار دفعتك.','يرجى مراجعة الفاتورة وتعليمات الدفع ثم إتمام الدفع.'],payment_confirmed:['تم تأكيد الدفع','تم تأكيد دفعتك ونحن ننتقل إلى مرحلة تجهيز التسليم.','لا يلزم اتخاذ إجراء حالياً. يرجى انتظار رسالة التسليم.'],preparing_delivery:['تجهيز التسليم','نحن نجهز مذكرة التسليم والإيصال ومثبت المنتج.','لا يلزم اتخاذ إجراء حالياً. يرجى انتظار رسالة التسليم.'],delivered:['تم التسليم','تم إرسال معلومات مذكرة التسليم والإيصال ومثبت المنتج.','يرجى مراجعة رسالة التسليم والاحتفاظ بالمستندات المطلوبة واستخدام المثبت لبدء استخدام المنتج.'],cancelled:['ملغي','تم إلغاء هذا الطلب. سيظل سجل الطلب متاحاً في Customer Portal.','إذا لم تكن تتوقع هذا الإلغاء، يرجى التواصل معنا.']}}
};

function clean(v,max=5000){return String(v??'').trim().slice(0,max)}
function escapeHtml(v){return clean(v,20000).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;')}
function validOrderId(v){return /^BK-\d{8}-[A-F0-9]{8}$/i.test(v)}
function validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)}
async function readJson(env,key){const raw=await env.ORDER_STATUS?.get(key);if(!raw)return null;try{return JSON.parse(raw)}catch{return null}}
async function sendBrevo(env,payload){if(!env.BREVO_API_KEY||!env.FROM_EMAIL)throw new Error('EMAIL_NOT_CONFIGURED');const res=await fetch(BREVO_URL,{method:'POST',headers:{'Content-Type':'application/json','api-key':env.BREVO_API_KEY,'Accept':'application/json'},body:JSON.stringify(payload)});if(!res.ok){const body=await res.text().catch(()=>'');throw new Error(`BREVO_${res.status}:${body.slice(0,250)}`)}return res.json().catch(()=>({}))}
async function sendWithRetry(env,payload){let last;for(let i=0;i<2;i++){try{return await sendBrevo(env,payload)}catch(e){last=e;if(i===0)await new Promise(r=>setTimeout(r,180))}}throw last}
function flowHtml(status,lang,copy){
 if(status==='cancelled')return `<div style="margin:18px 0;padding:14px 16px;border:1px solid #d99;background:#fff6f6;color:#9b2929;font-weight:800">${escapeHtml(copy.cancelled)}</div>`;
 const current=FLOW.indexOf(status);
 return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;margin:14px 0 20px"><tbody>${FLOW.map((key,i)=>{const label=copy.statuses[key]?.[0]||key;const done=i<current,active=i===current;const mark=done?'✓':active?'●':'○';const bg=active?'#eef6f1':'#ffffff';const border=active?'#0e7a4b':'#d7e1da';const color=active?'#0e7a4b':done?'#40564a':'#8a9690';return `<tr><td width="38" valign="top" style="padding:5px 0;text-align:center;color:${color};font-size:17px;font-weight:800">${mark}</td><td style="padding:8px 12px;border:1px solid ${border};background:${bg};color:${color};font-weight:${active?'800':'650'}">${escapeHtml(label)}</td></tr>${i<FLOW.length-1?'<tr><td style="text-align:center;color:#b7c1bb;line-height:12px">│</td><td></td></tr>':''}`}).join('')}</tbody></table>`;
}
function emailHtml(order,statusRecord){
 const lang=SUPPORTED.has(order?.lang)?order.lang:'ja',copy=COPY[lang]||COPY.en,status=statusRecord?.status||'order_received',s=copy.statuses[status]||COPY.en.statuses[status]||[status,'',''],name=clean(order?.customer?.name,120),custom=clean(statusRecord?.message,1200),dir=lang==='ar'?'rtl':'ltr';
 return `<!doctype html><html><body style="margin:0;background:#f3f6f4;font-family:Arial,'Noto Sans','Hiragino Kaku Gothic ProN','Yu Gothic',sans-serif;color:#17251f"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:24px 12px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:720px;background:#fff;border:1px solid #d7e1da"><tr><td style="padding:26px 28px;border-top:5px solid #0e7a4b" dir="${dir}"><div style="font-size:11px;letter-spacing:.12em;color:#65736c">Baked Kale / Kale’s FDE</div><h1 style="margin:8px 0 6px;font-size:24px;line-height:1.35">${escapeHtml(copy.title)}</h1>${name?`<p style="margin:0 0 18px">${escapeHtml(name)} ${escapeHtml(copy.hello)}</p>`:''}<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;background:#f7faf8;border:1px solid #d7e1da"><tr><td style="padding:12px 14px;width:38%"><small style="color:#65736c">${escapeHtml(copy.order)}</small><br><strong>${escapeHtml(order.orderId)}</strong></td><td style="padding:12px 14px"><small style="color:#65736c">${escapeHtml(copy.product)}</small><br><strong>${escapeHtml(order.product||statusRecord?.product||'')}</strong></td></tr></table><div style="margin:20px 0;padding:16px 18px;background:#0e7a4b;color:#fff"><div style="font-size:11px;opacity:.85">${escapeHtml(copy.current)}</div><div style="font-size:22px;font-weight:800;margin-top:4px">${escapeHtml(s[0])}</div></div><h2 style="font-size:15px;margin:22px 0 8px">${escapeHtml(copy.flow)}</h2>${flowHtml(status,lang,copy)}<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;margin-top:14px"><tr><td style="padding:14px 16px;border:1px solid #d7e1da"><strong>${escapeHtml(copy.explain)}</strong><div style="margin-top:7px;line-height:1.75;color:#44564d">${escapeHtml(s[1])}</div></td></tr><tr><td style="padding:14px 16px;border:1px solid #d7e1da;border-top:0;background:#eef6f1"><strong>${escapeHtml(copy.action)}</strong><div style="margin-top:7px;line-height:1.75">${escapeHtml(s[2])}</div></td></tr></table>${custom?`<div style="margin-top:16px;padding:14px 16px;border-left:4px solid #0e7a4b;background:#fafcfb"><strong>${escapeHtml(copy.message)}</strong><div style="margin-top:6px;line-height:1.7">${escapeHtml(custom).replaceAll('\n','<br>')}</div></div>`:''}<div style="text-align:center;margin:24px 0 8px"><a href="${PORTAL_URL}" style="display:inline-block;background:#17251f;color:#fff;text-decoration:none;padding:12px 20px;font-weight:700">${escapeHtml(copy.portal)}</a></div><p style="margin:22px 0 0;color:#65736c;font-size:11px;line-height:1.6">${escapeHtml(copy.footer)}<br>Baked Kale / Kale’s FDE</p></td></tr></table></td></tr></table></body></html>`;
}
async function sendStatusEmail(env,order,statusRecord){const email=clean(order?.customer?.email,254).toLowerCase();if(!validEmail(email))throw new Error('BUYER_EMAIL_NOT_AVAILABLE');const lang=SUPPORTED.has(order?.lang)?order.lang:'ja',copy=COPY[lang]||COPY.en,label=(copy.statuses[statusRecord.status]||[statusRecord.status])[0];return sendWithRetry(env,{sender:{name:env.FROM_NAME||"Kale’s FDE",email:env.FROM_EMAIL},to:[{email,name:clean(order?.customer?.name,120)||undefined}],subject:`[Kale’s FDE] ${copy.subject}: ${label} | ${order.orderId}`,htmlContent:emailHtml(order,statusRecord)})}
async function mergeJsonResponse(response,extra){const ct=response.headers.get('Content-Type')||'';if(!ct.includes('application/json'))return response;try{const data=await response.clone().json();return new Response(JSON.stringify({...data,...extra}),{status:response.status,headers:response.headers})}catch{return response}}

export default{
 async fetch(request,env,ctx){
  if(request.method!=='POST')return baseWorker.fetch(request,env,ctx);
  let raw=null;try{raw=await request.clone().json()}catch{}
  const type=clean(raw?.type,60);
  if(!['admin_order_update','status_update','admin_order_cancel','fulfillment'].includes(type))return baseWorker.fetch(request,env,ctx);
  const orderId=clean(raw?.orderId,40).toUpperCase();
  if(!validOrderId(orderId))return baseWorker.fetch(request,env,ctx);
  const before=await readJson(env,`order:${orderId}`);
  const response=await baseWorker.fetch(request,env,ctx);
  if(!response.ok)return response;
  const after=await readJson(env,`order:${orderId}`);
  const changed=!!after&&before?.status!==after.status;
  if(!changed)return mergeJsonResponse(response,{statusChanged:false,statusEmailSent:false});
  const order=await readJson(env,`admin-order:${orderId}`);
  if(!order)return mergeJsonResponse(response,{statusChanged:true,statusEmailSent:false,statusEmailError:'ADMIN_ORDER_NOT_FOUND'});
  try{await sendStatusEmail(env,order,after);return mergeJsonResponse(response,{statusChanged:true,statusEmailSent:true})}
  catch(error){console.error('Status notification email failed',error);return mergeJsonResponse(response,{statusChanged:true,statusEmailSent:false,statusEmailError:String(error?.message||'STATUS_EMAIL_FAILED')})}
 }
};
